### ISSUE TITLE
Support Elixir 1.3 native date types

### ISSUE THREAD

**Issue by hubertlepicki** [elixir-ecto/postgrex#192]
Should Postgrex work with native date types directly? 😃

**Comment by josevalim** [comment]
That would be backwards incompatible but maybe for now Postgrex could ship with an encoder module that works with the new Elixir data types?

**Comment by hubertlepicki** [comment]
I guess it could be configuration option rather than auto detection.

**Comment by josevalim** [comment]
Yes, we will use the extensions configuration we have today.

**Comment by ericmj** [comment]
We can bump postgrex to support 1.2 only. But it's too early to support 1.3 date types now since they are not released yet and it would be backwards compatible.

If you would like to add an optional extension module that supports them it would be appreciated.

**Comment by hubertlepicki** [comment]
@ericmj would you like new extensions, i.e. NativeDate to replace Date, NativeTime for Time and NativeTimestamp for example?

Because the alternative would be to amend existing extensions to encode/decode types differently depending on options passed to them.

**Comment by ericmj** [comment]
I prefer new extensions over adding options to the existing ones.

**Comment by hubertlepicki** [comment]
Got it. Would result in cleaner code this way.

@josevalim you agree? You mentioned configuration options so I have a hunch you would go with different approach?

**Comment by ericmj** [comment]
New extensions is better either way, because adding options to the existing ones would be even more verbose configuration. We can add a top-level option to `Postgrex.start_link` but that's orthogonal to the discussion of new extensions vs. adding options to existing ones.

**Comment by hubertlepicki** [comment]
Alright, let me start do some work on those, I'll propose a PR soon(ish).

I have one more related question: how do you think we should treat datetime with zones vs. without zones? PostgreSQL supports both table columns. The new Elixir types support zone info (albeit not complete). We could make it so the zone info is carried over back and forth from PostgreSQL if the underlying type specifies it, probably. Should I do it?

**Comment by ericmj** [comment]
In postgres timezone is always normalized to the timezone configured on the client connection. If you actually need to get the original timezone value you need to use a custom data type or store it in a secondary column which is out of scope for a driver. Projects like calecto solves this problem.

**Comment by hubertlepicki** [comment]
@ericmj I have question to this part:

"In postgres timezone is always normalized to the timezone configured on the client connection."

In my experience, I am always getting the time in UTC. For example: 

```
iex(6)> Postgrex.query!(pid, "SELECT NOW()", [])           
%Postgrex.Result{columns: ["now"], command: :select, connection_id: 11299,
 num_rows: 1,
 rows: [[%Postgrex.Timestamp{day: 4, hour: 20, min: 0, month: 6, sec: 33,
    usec: 870926, year: 2016}]]}
```

While the local time is 22:00, the values I am getting are in UTC.

Does this mean thatn when using Postgrex, we always are getting UTC dates, and this is what we should also send to database - or it's somehow configurable (I could not find how)?

**Comment by ericmj** [comment]
I'm on my phone but if you google "PostgreSQL set time zone" you will find
instructions. Your database is probably configured to use utc by default.

On Saturday, 4 June 2016, Hubert Łępicki <notifications@github.com> wrote:

> @ericmj <https://github.com/ericmj> I have question to this part:
>
> "In postgres timezone is always normalized to the timezone configured on
> the client connection."
>
> In my experience, I am always getting the time in UTC. For example:
>
> iex(6)> Postgrex.query!(pid, "SELECT NOW()", [])
> %Postgrex.Result{columns: ["now"], command: :select, connection_id: 11299,
>  num_rows: 1,
>  rows: [[%Postgrex.Timestamp{day: 4, hour: 20, min: 0, month: 6, sec: 33,
>     usec: 870926, year: 2016}]]}
>
> While the local time is 22:00, the values I am getting are in UTC.
>
> Does this mean thatn when using Postgrex, we always are getting UTC dates,
> and this is what we should also send to database - or it's somehow
> configurable (I could not find how)?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ericmj/postgrex/issues/192#issuecomment-223775537>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATV2izy9AM5yE-ZFGc9H-ctjSrEDQTdks5qIdq1gaJpZM4Ip-BZ>
> .
>


-- 
Eric Meadows-Jönsson

**Comment by lau** [comment]
The postgres type "timestamp without time zone" should be `NaiveDateTime`.

Postgres' "timestamp with time zone" is a datetime in UTC. AFAIK Postgres does not store any timezone information in the database except that "this value is in UTC". These should be returned as a `DateTime` structs in UTC.

But if postgres is configure to another time zone than UTC, it will return a datetime "shifted" to another zone. E.g. 23:50:00 might become 1:50:00 on the following day.

This could be handled by either not allowing using Postgrex with the connection timezone set to anything other than UTC. Maybe it could be enforced by a check when postgrex first connects? As a user of Postgrex I would want such a feature, because I would never personally want it to be set to something else than UTC. And I cannot think of a situation where it would be a good idea for anyone.

Alternatively if a "timestamp with time zone" is received from the database e.g. `2004-10-19 01:23:54+02`, it would have to be changed to `2004-10-18 23:23:54+00` when making a `%DateTime{time_zone: "Etc/UTC"}` struct. Also when select, inserting or updating "timestamps with timezones" we would have to make sure that if the connection is set to a non-UTC time zone that e.g. `2004-10-18 23:23:54+00` would not be interpreted as `2004-10-18 23:23:54+02` by postgres.

**Comment by ericmj** [comment]
Even if we did receive time zone information ( we don't) from the database
we shouldn't use it to build the DateTime struct because the offset changes
as you change time zone configuration.

On Wednesday, 8 June 2016, Lau Taarnskov <notifications@github.com> wrote:

> The postgres type "timestamp without time zone" should be NaiveDateTime.
>
> Postgres' "timestamp with time zone" is a datetime in UTC. AFAIK Postgres
> does not store any timezone information in the database except that "this
> value is in UTC". These should be returned as a DateTime structs in UTC.
>
> But if postgres is configure to another time zone than UTC, it will return
> a datetime "shifted" to another zone. E.g. 23:50:00 might become 1:50:00 on
> the following day.
>
> This could be handled by either not allowing using Postgrex with the
> connection timezone set to anything other than UTC. Maybe it could be
> enforced by a check when postgrex first connects? As a user of Postgrex I
> would want such a feature, because I would never personally want it to be
> set to something else than UTC. And I cannot think of a situation where it
> would be a good idea for anyone.
>
> Alternatively if a "timestamp with time zone" is received from the
> database e.g. 2004-10-19 01:23:54+02, it would have to be changed to 2004-10-18
> 23:23:54+00 when making a %DateTime{time_zone: "Etc/UTC"} struct. Also
> when select, inserting or updating "timestamps with timezones" we would
> have to make sure that if the connection is set to a non-UTC time zone that
> e.g. 2004-10-18 23:23:54+00 would not be interpreted as 2004-10-18
> 23:23:54+02 by postgres.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ericmj/postgrex/issues/192#issuecomment-224446492>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATV2gVvBIDW4hkbLJs87mrp-LhZGroQks5qJgFYgaJpZM4Ip-BZ>
> .
>


-- 
Eric Meadows-Jönsson

**Comment by ericmj** [comment]
We don't receive from the database because we use the binary data format. But with the text format we only get the offset from UTC the database or connection has been configured to use. Because, as you said, postgres doesn't store the offset it feels wrong to use the current offset to build the DateTime struct.

**Comment by hubertlepicki** [comment]
Alright so I think the behavior of the binary protocol is to *always* return dates in UTC, it also expects the dates to be sent in UTC. This is important to say "between" queries, and you can get yourself into trouble if you don't do that. For example my system's PostgreSQL is configured to "Poland" time zone, and using PSQL or other clients that do text protocol we get local timestamps. When using binary protocol/Postgrex, the dates are in UTC:

```
iex(1)> {:ok, pid} = Postgrex.start_link(hostname: "localhost", database: "foo_dev")
{:ok, #PID<0.320.0>}
iex(2)> Postgrex.query!(pid, "SELECT NOW()", [])   
%Postgrex.Result{columns: ["now"], command: :select, connection_id: 17939,
 num_rows: 1,
 rows: [[%Postgrex.Timestamp{day: 8, hour: 8, min: 43, month: 6, sec: 2,
    usec: 397131, year: 2016}]]}


➜  foo git:(refactor_it) psql bankie_dev
psql (9.5.3)
Type "help" for help.

foo_dev=# select NOW();
              now              
-------------------------------
 2016-06-08 10:43:16.845292+02
(1 row)

```

This sort of suggests to me that we should either enforce that dates are sent in UTC format or *convert* those. Since conversion is currently only possible using third party libraries as Timex (it's not anywhere in standard library on Elixir 1.3), I suggest we require the dates/times sent back and forth to be in UTC time zone, or be all naive.

What do you think?

**Comment by ericmj** [comment]
That sounds reasonable. So we should do the following: Accept naive
datetimes and assume they are UTC. Accept datetimes with time zone only if
they are UTC. Always return datetimes with time zone in UTC. And finally
document that the driver assumes the database or connection is configured
to use UTC.

I also need to do some checks when I get back from vacation to see that we
don't get any surprises when using timestamp vs timestamptz, but iirc the
two types are equivalent in binary format when in UTC.

On Wednesday, 8 June 2016, Hubert Łępicki <notifications@github.com> wrote:

> Alright so I think the behavior of the binary protocol is to *always*
> return dates in UTC, it also expects the dates to be sent in UTC. This is
> important to say "between" queries, and you can get yourself into trouble
> if you don't do that. For example my system's PostgreSQL is configured to
> "Poland" time zone, and using PSQL or other clients that do text protocol
> we get local timestamps. When using binary protocol/Postgrex, the dates are
> in UTC:
>
> iex(1)> {:ok, pid} = Postgrex.start_link(hostname: "localhost", database: "foo_dev")
> {:ok, #PID<0.320.0>}
> iex(2)> Postgrex.query!(pid, "SELECT NOW()", [])
> %Postgrex.Result{columns: ["now"], command: :select, connection_id: 17939,
>  num_rows: 1,
>  rows: [[%Postgrex.Timestamp{day: 8, hour: 8, min: 43, month: 6, sec: 2,
>     usec: 397131, year: 2016}]]}
>
>
> ➜  foo git:(refactor_it) psql bankie_dev
> psql (9.5.3)
> Type "help" for help.
>
> foo_dev=# select NOW();
>               now
> -------------------------------
>  2016-06-08 10:43:16.845292+02
> (1 row)
>
>
> This sort of suggests to me that we should either enforce that dates are
> sent in UTC format or *convert* those. Since conversion is currently only
> possible using third party libraries as Timex (it's not anywhere in
> standard library on Elixir 1.3), I suggest we require the dates/times sent
> back and forth to be in UTC time zone, or be all naive.
>
> What do you think?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ericmj/postgrex/issues/192#issuecomment-224528333>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATV2tNy0DqtxAYNlRJbgMOEGdNgcjcCks5qJoJpgaJpZM4Ip-BZ>
> .
>


-- 
Eric Meadows-Jönsson

**Comment by hubertlepicki** [comment]
Good discussion, thank you all :)

**Comment by fishcakez** [comment]
@hubertlepicki ping :smile:

**Comment by fishcakez** [comment]
@hubertlepicki I thought you wanted to pick this up, is this still the case?
