### ISSUE TITLE
Support oid query and necassary types

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/postgrex#208]
Example: `SELECT typname FROM pg_type WHERE oid = …;`

\cc @ericmj

**Comment by ericmj** [comment]
We should try to support the types of all columns in the `pg_type` table.

**Comment by fishcakez** [comment]
Apart from the `char` type, which can be handled by raw extension as a string of single codepoint, I think the other types can only use the text format but do not make sense as text (`aclitem`, `_aclitem`, `pg_node_tree`). Should we add support for `char` and require the others to be cast as text?

**Comment by fishcakez** [comment]
I've added support for the special `"char"` type, I think the others only have text format. @ericmj @michalmuskala could you please check what types you'd like support for.

**Comment by ericmj** [comment]
If they are text only there isn't much we can do unfortunately. I think we can close this for now.
