### ISSUE TITLE
Error connecting to test database

### ISSUE THREAD

**Issue by tyre** [elixir-ecto/postgrex#21]
I see this error off and on when running tests. Sometimes they all run fine and other times I see:

```
1) test decode basic types (QueryTest)
     test/query_test.exs:16
     ** (MatchError) no match of right hand side value: {:error, %Postgrex.Error{message: "tcp connect: nxdomain", postgres: nil}}
     stacktrace:
       test/query_test.exs:8: QueryTest.__ex_unit_setup_0/1
       test/query_test.exs:1: QueryTest.__ex_unit__/2
```

Google shows a few threads related to dns settings, but I'm not sure why those would change from time to time.

**Comment by jaketrent** [comment]
I had the same nxdomain problem.  It turned out that my issue was the the env var PGHOST=/tmp, which is the first url that postgrex is using to connect to the db.  I got around this by setting `hostname: "localhost"` in my config.exs.
