### ISSUE TITLE
How to deal with timeout in a long running operation?

### ISSUE THREAD

**Issue by alfredbaudisch** [elixir-ecto/postgrex#227]
I needed to insert more than 350 million rows, but Postgrex kept timing out:

`21:10:22.721 [error] Postgrex.Protocol (#PID<0.272.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.308.0> timed out because it checked out the connection for longer than 15000ms`

`** (Postgrex.Error) tcp recv: closed`

How can I increase the time?

**Comment by ericmj** [comment]
Check the `:timeout` options https://hexdocs.pm/ecto/Ecto.Repo.html.

I would strongly recommend chunking your rows so that each insert takes <15000ms. It's very likely that you will hit the query limits with 350 million rows anyway.
