### ISSUE TITLE
JSON extensions initialised twice, without a library for the second time

### ISSUE THREAD

**Issue by mset** [elixir-ecto/postgrex#229]
I have been unsuccessful in making the JSON extension work (inserting an embedded schema into a json (:map) field), getting an error when calling _Repo.update_ after calling _Changeset,put_embed_. The error says that the library var in the  _library.encode!_ call is nil.

I believe everything is set up correctly in the project, so tried some debugging and found that in the _types.ex_, in the _prepare_extensions_ function, the Postgrex.Extensions.JSON is initialised twice - once with the Poison library and without [library: nil] for the second time.

Is that an error on my part or is the code misbehaving?
I am using a standard Postgres 9.5.4.

Cheers,
Marek

**Comment by josevalim** [comment]
Can you please include your Postgrex version? Can you let us know how postgrex is configured? Can you please let us know the error message with stacktrace?

When opening a bug report, please include as much information as possible, it makes our lives much easier.

**Comment by mset** [comment]
Here is the requested info. Let me know if more would be beneficial.

It's a stand-alone project, NOT using Phoenix.

**Deps in mix.exs include:**
Postgrex: ~> 0.11.2
Ecto: ~> 2.0.4
Poison: ~> 2.0

Ecto with the Postgres adapter is configured and working correctly, that is until I try to update an existing record with an embedded schema.

**Config contains:**
config :ffc_comp, FfcComp.Repo,
  adapter: Ecto.Adapters.Postgres,
  extensions: [{Postgrex.Extensions.JSON, library: Poison}]

The error is output upon calling _Repo.update!(changeset)_

> ** (UndefinedFunctionError) function nil.encode!/1 is undefined or private
>                     nil.encode!(%{id: "127a7849-61e3-4a41-951a-d2264151c81c", rasp_resolution: 2})
>          (postgrex) lib/postgrex/extensions/json.ex:39: Postgrex.Extensions.JSON.encode/4
>          (postgrex) lib/postgrex/query.ex:131: DBConnection.Query.Postgrex.Query.do_encode/4
>          (postgrex) lib/postgrex/query.ex:68: DBConnection.Query.Postgrex.Query.encode/3
>     (db_connection) lib/db_connection.ex:859: DBConnection.describe_execute/4
>     (db_connection) lib/db_connection.ex:930: anonymous fn/4 in DBConnection.run_meter/5
>     (db_connection) lib/db_connection.ex:463: DBConnection.prepare_execute/4
>                     lib/ecto/adapters/postgres/connection.ex:82: Ecto.Adapters.Postgres.Connection.execute/4

**Comment by josevalim** [comment]
Ecto already specifies a JSON extension that defaults to Poison when using postgrex. So you can safely removing the extensions line.

**Comment by mset** [comment]
Yes, I thought so. 

I did try it without the config _extension:_ line but the error appears regardless.

However, when I run it without the `extensions: [{Postgrex.Extensions.JSON, library: Poison}]` line in the config, then the _prepare_extensions_ function in _types.ex_ does not contain the JSON extension duplicity and _opts_ contains `[library: nil]`.

The Postgrex documentation mentions that some manual configuration is required (https://hexdocs.pm/postgrex/readme.html#extensions). I am not calling `Postgrex.start_link` manually as I assume that Ecto starts Postgrex for me. Perhaps I am missing something?

**Comment by josevalim** [comment]
Unless you set the :ecto :json_library to nil, it should work: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/adapters/postgres/connection.ex#L12-L14

Otherwise, please provide an application that reproduces the error, so we can check it out and further investigate.

**Comment by mset** [comment]
Thanks for the pointer and your help, José, it's much appreciated.

I don't have it anywhere in the config, however when I include `config :ecto, :json_library, Poison` in the config file, it starts to work, which is good news.

Looking at this line - https://github.com/elixir-ecto/ecto/blame/master/lib/ecto/adapters/postgres/connection.ex#L12 - where does the `:json_library` key get set to get the default value of _Poison_? Still trying to figure out why it does not work without the special config item..

**Comment by josevalim** [comment]
If adding the configuration by hand is fixing it, it is probably because you did not add `:ecto` to your list of applications in `def application` inside your mix.exs.

**Comment by mset** [comment]
That is true and I can confirm that it works now even without the special config value. Thanks a lot.

I have just noticed that `:ecto` needs to be in `def application` in the ecto github README. I went by the _Getting Started_ guide which does not have that info. Happy to add it there if you confirm that this is now the way to use ecto.

**Comment by josevalim** [comment]
Yes, please do send a PR then! We almost always should add our depednencies to the list of applications!

**Comment by mset** [comment]
Will do. Thanks for the info and for your time!
