### ISSUE TITLE
use of enum type is not documented

### ISSUE THREAD

**Issue by ballPointPenguin** [elixir-ecto/postgrex#231]
support for enum types was added in [0.8.0](https://github.com/elixir-ecto/postgrex/blob/master/CHANGELOG.md#v080-2015-02-26), however there is no mention of enum anywhere in the [documentation](https://hexdocs.pm/postgrex/readme.html).

**Comment by ericmj** [comment]
Can you send a PR that adds it here? https://github.com/elixir-ecto/postgrex#data-representation

**Comment by ballPointPenguin** [comment]
I took a shot at it. 
https://github.com/elixir-ecto/postgrex/pull/232
