### ISSUE TITLE
citext should use `send` from TypeInfo instead of `type`

### ISSUE THREAD

**Issue by evadne** [elixir-ecto/postgrex#233]
%Postgrex.TypeInfo{array_elem: 0, base_type: 0, comp_elems: [],
     input: "domain_in", oid: 54427, output: "citextout", receive: "domain_recv",
     send: "citextsend", type: "nonempty_citext"}

Example:

    CREATE DOMAIN nonempty_citext AS citext
        CONSTRAINT nonempty_citext_check CHECK ((VALUE <> ''::citext));

**Comment by fishcakez** [comment]
Fixed in https://github.com/elixir-ecto/postgrex/commit/f36416e2b16e887ceb7f66eff215df9abab66001
