### ISSUE TITLE
Upgrade ecto from 1.0 to 2.0 get a DBConnection error.

### ISSUE THREAD

**Issue by EmmaHL** [elixir-ecto/postgrex#240]
iex(4)> import Ecto.Query                                
nil
iex(5)> MyApp.Repo.all(from u in MyApp.User, select: u.id)
[]
iex(6)> 
09:49:05.552 [error] Postgrex.Protocol (#PID<0.232.0>) disconnected: ** (DBConnection.ConnectionError) owner #PID<0.236.0> timed out because it owned the connection for longer than 15000ms

Do you have any idea? thanks in advance.

**Comment by josevalim** [comment]
It seems you are using the ownership pool and the ownership has a timeout value to not allow connections to be checked out for very long. You may want to set `ownership_timeout: :infinity` for such cases in your repo configuration.

**Comment by EmmaHL** [comment]
Thank you josevalim, it works. but I tried this before, I set a big integer like 150000ms, it not works, do you know why?

**Comment by josevalim** [comment]
No idea why, sorry. :S

**Comment by fishcakez** [comment]
@EmmaHL can you create a simple project that reproduces this?
