### ISSUE TITLE
How to load a custom created Type?

### ISSUE THREAD

**Issue by gjaldon** [elixir-ecto/postgrex#248]
Hi there!

I have an Ecto extension that I'm trying to update to support Ecto 2.0 but am encountering a problem. I run a `"CREATE TYPE SOME_TYPE AS ENUM ('#{types}')"` query. My user-defined type is not getting loaded by Postgrex and get the following error:

```
 ** (ArgumentError) no extension found for oid `376414`
     stacktrace:
       (postgrex) lib/postgrex/types.ex:276: Postgrex.Types.fetch!/2
       (postgrex) lib/postgrex/types.ex:191: Postgrex.Types.encoder/2
       (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
       (postgrex) lib/postgrex/query.ex:101: DBConnection.Query.Postgrex.Query.encoders/2
       (postgrex) lib/postgrex/query.ex:48: DBConnection.Query.Postgrex.Query.describe/2
       (db_connection) lib/db_connection.ex:858: DBConnection.describe_execute/4
       (db_connection) lib/db_connection.ex:930: anonymous fn/4 in DBConnection.run_meter/5
       (db_connection) lib/db_connection.ex:987: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:463: DBConnection.prepare_execute/4
       (ecto) lib/ecto/adapters/postgres/connection.ex:82: Ecto.Adapters.Postgres.Connection.execute/4
       (ecto) lib/ecto/adapters/sql.ex:228: Ecto.Adapters.SQL.sql_call/6
       (ecto) lib/ecto/adapters/sql.ex:426: Ecto.Adapters.SQL.struct/6
       (ecto) lib/ecto/repo/schema.ex:391: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:187: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:118: Ecto.Repo.Schema.insert!/4
       test/pg/postgres_test.exs:19: (test)
```

Before upgrading to Ecto-2.0, the fix for this was to restart the `Repo` server. Doing that no longer works after the ugprade. 

The PR to upgrade to Ecto 2.0 for my extension is at https://github.com/gjaldon/ecto_enum/pull/17/files#r77555055 in case you'd like to take a look.

**Comment by ericmj** [comment]
What postgrex version are you using? New types should be picked up when postgrex reconnects.

**Comment by fishcakez** [comment]
To expand on @ericmj's reply:

In Ecto ~> 1.0 need to restart both the repo and the `:postgrex` application, the same will work in Ecto ~> 2.0. Alternatively upgrade to Ecto ~> 2.0.5 and postgrex ~> 0.12.1, then you shouldn't need to restart anything. It's possible a couple of queries will fail before it gets resolved.

**Comment by fishcakez** [comment]
@gjaldon ping? Would like to release 1.0 and want to check this feature is working as intended. Otherwise we may need a backwards incompatible change to fix it.

**Comment by fishcakez** [comment]
@gjaldon any news?

**Comment by fishcakez** [comment]
Apparently this issue is resolved by upgrading: https://github.com/gjaldon/ecto_enum/pull/22. Can you confirm?

**Comment by gjaldon** [comment]
@fishcakez finally looked into it. The issue is now resolved with an upgrade. Thank you!
