### ISSUE TITLE
Postgrex failed to recover from dropped DB connection

### ISSUE THREAD

**Issue by mfeckie** [elixir-ecto/postgrex#255]
I'm not sure that this issue lies with Postgrex, but sharing in case other had similar issues.

Have a production app that's been running rock solid for some months.  Over the weekend it seems that connection to the DB was dropped.

Logs show:

```
Postgrex.Protocol (#PID<0.1486.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect: non-existing domain - :nxdomain
Postgrex.Protocol (#PID<0.1513.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect: non-existing domain - :nxdomain
Postgrex.Protocol (#PID<0.1493.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect: non-existing domain - :nxdomain
```

Problem was resolved by stopping the release and restarting it.  The server was not rebooted, this was the only intervention required to resolve the issue.

It's running on `Ubuntu 16.04.1 LTS`, packaged using `exrm` and `edeliver`.

I can provide additional information if anyone has any thoughts.

It's likely that this isn't actually postgrex related, so feel free to close the issue.

**Comment by ericmj** [comment]
As I said on slack this is unlikely to be a postgrex since the error is returned from the os tcp stack.

This could be an OS issue, a DNS caching issue or something else. You can check the docs for inet_res: http://erlang.org/doc/man/inet_res.html.

I am closing this since it's not actionable on this repo. Feel free to continue the discussion though or reopen if anyone knows anything we can improve in postgrex.

**Comment by LegitStack** [comment]
I'm having a similar problem in windows after installing elixir and the phoenix framework. 

[error] Postgrex.Protocol (#PID<0.233.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
[error] Postgrex.Protocol (#PID<0.29.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
[error] Postgrex.Protocol (#PID<0.234.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused

**Comment by fishcakez** [comment]
@LegitStack the opening post was an issue with DNS, whereas the lookup (for localhost) is a success for you but the ip/port is not accepting connections.

**Comment by ijunaid8989** [comment]
@mfeckie how you solved this issue?
