### ISSUE TITLE
Add option to create `UNLOGGED` tables in test environment

### ISSUE THREAD

**Issue by hauleth** [elixir-ecto/postgrex#260]
This one should give performance boost to write-heavy test suites. As test databases are in general short-lived there should be no harm when such strategy would be used.

**Comment by fishcakez** [comment]
Postgrex itself shouldn't affect how you create tables. Is this for `Ecto.Adapters.Postgres`? If so, can you open the issue in Ecto instead?

**Comment by ericmj** [comment]
Closing this because drivers do not affect table creation. Feel free to post here if you have any questions.
