### ISSUE TITLE
cannot connect to remote postgres

### ISSUE THREAD

**Issue by blset** [elixir-ecto/postgrex#261]
It seems impossible to connect to a server on a private ip machine

I guess the ip is not understood as an ip ?
but without the quotes it is a syntax error

config :xoci, Xoci.Repo,                                                             
 15   adapter: Ecto.Adapters.Postgres,                                                   
 16   host: "10.8.0.2",                                                                  
 17   username: "user",                                                                   
 18   password: "pass",                                                                   
 19   database: "prod",                                                             
 20   pool_size: 20      

I cannot run mix ecto.migrate from a mix directory 

nor iex -S mix

I receive the error (invalid_password): password authentification failed for user user

Note that I have the same error if I configure the postgres user with trust and no password

but connection is ok with psql, so this is not a postgres problem

thanks

**Comment by blset** [comment]
I make it work with PGHOST=10.8.0.2 mix ecto.migrate, and removing the host section
but then how do you specifiy the ip in the config section?

**Comment by fishcakez** [comment]
@blset the config is`:hostname`. Do we have `:host` documented somewhere?

**Comment by fishcakez** [comment]
The default is `"localhost"` so likely fails to connect to your local database.

**Comment by blset** [comment]
thanks it was because of host instead of hostname

**Comment by blset** [comment]
it is host in rails config files that's why...

**Comment by fishcakez** [comment]
@blset ah, I think we had to listed as `:host` in Ecto for a while :smile:
