### ISSUE TITLE
`:null` option not honoured by super extensions

### ISSUE THREAD

**Issue by fishcakez** [elixir-ecto/postgrex#262]
Super extensions (e.g. `Postgrex.Extensions.Array`) always use `nil` for null values. For consistency I think this means we should drop support `:null` from `query` and other functions and only allow in `start_link`. `:null` would work like `:decode_binary` and requires a type server key element.

/cc @talentdeficit

**Comment by talentdeficit** [comment]
would specifying it in `start_link` override in the super extensions? if so this is fine with me. i believe i only added it because it was easy, not because it was necessary

**Comment by fishcakez** [comment]
@talentdeficit yes it would, that's what meant by "like `:decode_binary`".

**Comment by fishcakez** [comment]
This is handled in #263.
