### ISSUE TITLE
Using `Postgrex.Types.define` is slow

### ISSUE THREAD

**Issue by karlseguin** [elixir-ecto/postgrex#273]
Maybe I'm doing something wrong, but it adds around 4second to our startup time, which is painful when you're in a tdd or any other type of iterative development. It's unbearable.

**Comment by michalmuskala** [comment]
How are you calling it? Normally it's called at compile time in only one file, so it's just a one-off thing, that shouldn't be that annoying. Unless you somehow recompile that file over and over again.

**Comment by fishcakez** [comment]
Unfortunately we are trading compile time for runtime speed. Are you calling `define` when starting your application? Does https://github.com/elixir-ecto/postgrex/commit/245882784de7b03dc14d352eca00762930e7047d help you?

**Comment by fishcakez** [comment]
For example: https://github.com/elixir-ecto/postgrex/blob/506fd7eb5fcc96f96db8c1829d43d09a5ebf7d3a/lib/postgrex/default_types.ex

**Comment by karlseguin** [comment]
Thanks. That helped. It was inside the `start_link` of a worker
