### ISSUE TITLE
Connection Pooling

### ISSUE THREAD

**Issue by dax0** [elixir-ecto/postgrex#276]
How does connection pooling work exactly? I see some reference to DBConnection for :pool but not clear on how to increase the size

**Comment by fishcakez** [comment]
Setting the pool size depends on the pool, the docs for each pool are in DBConnection. The default pool is `DBConnection.Connection` which is always a single connection. Other built in pools have the `:pool_size` configuration, e.g. `pool: DBConnection.Poolboy, pool_size: 10`.
