### ISSUE TITLE
Postgrex default extensions get overridden

### ISSUE THREAD

**Issue by venkatd** [elixir-ecto/postgrex#277]
I currently define my types like:

```elixir
ecto_extensions = Ecto.Adapters.Postgres.extensions()
custom_extensions = [{Postgrex.Types.Ltree, :copy}]
extensions = ecto_extensions ++ custom_extensions

Postgrex.Types.define(Turtle.PostgresTypes, extensions)
```

And in my config.test.exs
```elixir
config :turtle, ES.EventRepo,
  adapter: Ecto.Adapters.Postgres,
  hostname: "localhost",
  database: "turtle_test",
  username: "postgres",
  password: "",
  pool_size: 10,
  types: Turtle.PostgresTypes
```

My tests raise an error `     ** (RuntimeError) type jsonb can not be handled by the configured extensions`

Which originates from here: https://github.com/elixir-ecto/postgrex/blob/b1c0d7e4fd517b56fbd3bcdb7f2ee21e107c2665/lib/postgrex/protocol.ex#L910

Versions:
- ecto 2.1.1
- postgrex 0.13.0

**Comment by venkatd** [comment]
Narrowed it down a bit further.

The if I uncomment the `JSONB` extension my code works:
```ecto_extensions = Ecto.Adapters.Postgres.extensions()
custom_extensions = [{Postgrex.Types.Ltree, :copy}]##, {Postgrex.Extensions.JSONB, decode_binary: :copy, json: Poison}]
extensions = ecto_extensions ++ custom_extensions

Postgrex.Types.define(Turtle.PostgresTypes, extensions)
```

**Comment by josevalim** [comment]
@venkatd try this:

```elixir
      Postgrex.Types.define(MyApp.PostgresTypes,
                            [MyExtension.Foo, MyExtensionBar] ++ Ecto.Adapters.Postgres.extensions(),
                            json: Poison)
```

As mentioned here: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/adapters/postgres.ex#L75-L77

We should probably make the error message clearer. :)

**Comment by venkatd** [comment]
The following worked, thanks!

```elixir
Postgrex.Types.define(Turtle.PostgresTypes,
                      [{Postgrex.Types.Ltree, :copy}] ++ Ecto.Adapters.Postgres.extensions(),
                      json: Poison)
```

**Comment by fishcakez** [comment]
Error improved for json (and others slightly) in https://github.com/elixir-ecto/postgrex/commit/671c7f01ea12b6b4f7f2904580688572251c1bce.
