### ISSUE TITLE
Switch json encoder to `encode_to_iodata!`

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/postgrex#282]
Right now postgrex requires the `encode!/1` and `decode!/1` functions for the json encoder. It also does does not specify types of arguments or return values.

I propose changing the function to `encode_to_iodata!/` for encoding and documenting that the function should return iodata. Similarly, the decode function should be able to accept iodata - this leaves us bigger interface for the future, even if we'll be only using full binaries for now. Receiving iodata in the encode phase, should be beneficial for performance - especially memory pressure.

This is obviously a breaking change, but it's impact remains fairly limited. For people using Poison, no change is required since Poison already satisfies the new interface. For people using custom json encoders, the change should be fairly easy (renaming a single function) and easy to catch - the errors would show up rather early if changelog entry is missed on update.
Another benefit is that this aligns the interface of the encoder in postgrex, with the interface of the encoder in phoenix. People using both projects could now use the same custom json encoder in both places.

**Comment by josevalim** [comment]
:+1:. We should also do it before we release 1.0.
