### ISSUE TITLE
:crypto should be part of postgrex's applications list

### ISSUE THREAD

**Issue by allanmongej** [elixir-ecto/postgrex#287]
I was facing the issue below when trying to deploy my app, the issue is generated because :crypto is not part of postgrex's application list.

I added :crypto to my application list as a temporal solution.

Postgrex version 0.13.0

07:22:32.646 [info]  Application simple exited: exited in: Simple.App.start(:normal, [])
    ** (EXIT) exited in: :gen_server.call(#PID<0.873.0>, {:checkout, #Reference<0.0.1.154>, true, :infinity}, 5000)
        ** (EXIT) an exception was raised:
            ** (UndefinedFunctionError) function :crypto.hash/2 is undefined (module :crypto is not available)
                :crypto.hash(:md5, ["user", "password"])
                (postgrex) lib/postgrex/protocol.ex:583: Postgrex.Protocol.auth_md5/4
                (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
                (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
                (connection) lib/connection.ex:622: Connection.enter_connect/5
                (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

**Comment by fishcakez** [comment]
Fixed in https://github.com/elixir-ecto/postgrex/commit/e14fbdd6c8f57bfbdc0aa001dfba8a186b04775b as doing patch release.
