### ISSUE TITLE
use .pgpass file on connection

### ISSUE THREAD

**Issue by jmarca** [elixir-ecto/postgrex#289]
Putting in a feature request to support the .pgpass file, as described here:  https://www.postgresql.org/docs/current/static/libpq-pgpass.html

According to the docs for start_link:

```
:hostname - Server hostname (default: PGHOST env variable, then localhost);
:port - Server port (default: PGPORT env variable, then 5432);
:database - Database (default: PGDATABASE env variable; otherwise required);
:username - Username (default: PGUSER env variable, then USER env var);
:password - User password (default: PGPASSWORD env variable); 
```

Would be great if I could also rely on the .pgpass file, as most other languages' psql connectors can do.

Brand new to elixir, just testing things out, so I can't contribute code for this.

**Comment by jmarca** [comment]
Note this may be a bug in how the default phoenix app uses this library...I haven't been able to figure that out yet.

**Comment by jmarca** [comment]
Looking more at how *this* library connects to postgres, it seems *not* to use the libpq library.  

If that is indeed the case, then perhaps the best solution will be to translate the libpq C into elixir here.  The relevant code is tucked into `src/interfaces/libpq/fe-connect.c`, in the function "PasswordFromFile".  I'll give it a shot, as it would be a nice small task to start learning elixir.

Any problems with this approach?

(If this lib *does* use the libpq library already, then I have no clue how to read this code)

**Comment by ericmj** [comment]
> Looking more at how this library connects to postgres, it seems not to use the libpq library.

Correct, this library implements the protocol itself.

**Comment by josevalim** [comment]
I am sorry for the delay on this. We have decided to not support pgpass as part of Postgrex. I would recommend somebody to do a `pgpass` library that can read those files and then you just need to call Postgrex. Something like: `Postgrex.start_link(PGPass.read(..., ...))`.

Thank you and apologies for closing this after we showed interest on the work. :heart:
