### ISSUE TITLE
Naming the Postgrex.Notifications server

### ISSUE THREAD

**Issue by bopjesvla** [elixir-ecto/postgrex#293]
As described by https://elixirforum.com/t/supervising-postgrex-notifications-process/722:

> Hello!
> 
> I have a use case involving a reactive application that reacts to postgres events using NOTIFY. I found this [example](https://elixirforum.com/clicks/track?url=https%3A%2F%2Fmedium.com%2F%40kaisersly%2Fpostgrex-notifications-759574f5796e%23.vpm3ju3ji&post_id=4620&topic_id=722) on how to set it up using postgrex, but I found it weird that it was starting the Postgrex.Notifications process as a child within the Posts.PgListener process (the last code example).
> 
> What would be the advantages to do this as opposed to having the Supervisor start and own the Postgrex.Notifications process?
> 
> Also, I was facing some challenges supervising it on the top level because the current implementation doesn't seem to support the name binding. In situations like these, is it more preferable to update the implementation to support name binding, or is there a way to extract the pid out of the supervisor (so that other processes can talk to it)?
> 
> Thanks!

Given that no one came up with a solution, shouldn't Postgrex.Notifications.start_link support the name option?

**Comment by ericmj** [comment]
Can you show your code? `Postgrex.Notifications` should support that option.

**Comment by bopjesvla** [comment]
Can't whip together a full test case right now, this'll have to do:

```elixir
iex(11)> config
[adapter: Ecto.Adapters.Postgres, username: "postgres",
 password: "postgres", database: "test_dev", hostname: "localhost",
 pool_size: 10, name: :test]
iex(12)> {:ok, pid} = Postgrex.Notifications.start_link config
{:ok, #PID<0.465.0>}
iex(13)> send pid, "hey"
"hey"
[info] Postgrex.Protocol #PID<0.465.0> received unexpected message: "hey"
iex(14)> send :test, "hey"
** (ArgumentError) argument error
    :erlang.send(:test, "hey")
iex(14)> send pid, "hey"
"hey"
[info] Postgrex.Protocol #PID<0.465.0> received unexpected message: "hey"
iex(15)> Postgrex.Notifications.listen :test, "test"
** (exit) exited in: :gen_server.call(:test, {:listen, "test"}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib) gen_server.erl:212: :gen_server.call/3
iex(15)>Postgrex.Notifications.listen pid, "test"
{:ok, #Reference<0.0.1.5355>}
iex(16)>
```

**Comment by ericmj** [comment]
You are right. Options should also be passed as a third argument here: https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/notifications.ex#L27.

Any thoughts on this @fishcakez?

**Comment by fishcakez** [comment]
All the specs use `pid`. Looks like this is just legacy behaviour when it was separated out. I think it is fine to add a name if we update specs and any docs too.
