### ISSUE TITLE
Postgrex compillation error

### ISSUE THREAD

**Issue by webdev4u** [elixir-ecto/postgrex#302]
CentOS Linux release 7.3.1611 (Core)

Hex:    0.15.0
Elixir: 1.5.0-dev
OTP:    19.2

Built with: Elixir 1.3.4 and OTP 18.3.4.4

When run mix deps.compile get error on postgrex:
==> postgrex
Compiling 62 files (.ex)

== Compilation error on file lib/postgrex/extensions/timestamptz.ex ==
** (ArgumentError) invalid Unix time 9224318016000
    (elixir) lib/calendar.ex:1522: DateTime.from_unix!/2
    lib/postgrex/extensions/timestamptz.ex:13: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

**Comment by josevalim** [comment]
It has been fixed on latest Postgrex. Just update your dependency. Also note this issue only happens in Elixir master.
