### ISSUE TITLE
Postgrex cannot handle extensions defined inside a schema

### ISSUE THREAD

**Issue by asabil** [elixir-ecto/postgrex#303]
Postgrex seems to fail at decoding extensions defined indeed a schema.

If for example the`citext` extension is defined inside a schema:
```
CREATE EXTENSION citext WITH SCHEMA foo;
```

Postgrex will fail with the following error:

```
** (RuntimeError) type `citext` can not be handled by the configured extensions
    (ecto) lib/ecto/adapters/postgres/connection.ex:99: Ecto.Adapters.Postgres.Connection.execute/4
    (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:561: Ecto.Adapters.SQL.struct/7
    (ecto) lib/ecto/repo/schema.ex:467: Ecto.Repo.Schema.apply/4
    (ecto) lib/ecto/repo/schema.ex:205: anonymous fn/13 in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/repo/schema.ex:684: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
    (db_connection) lib/db_connection.ex:1365: DBConnection.transaction_nested/2
    (db_connection) lib/db_connection.ex:1225: DBConnection.transaction_meter/3
```

This does not occur when the extension is created in the `public` schema.

**Comment by ericmj** [comment]
The reason is because the sender/receiver functions, which postgrex use to identify which type to decode, are namespaced with the schema: `foo.citextsend`. We can probably try to match out the schema if it exists.

What's the use case for creating an extension under a schema?

**Comment by josevalim** [comment]
@asabil ping.

**Comment by josevalim** [comment]
Closing this due to no follow up.

**Comment by dpick** [comment]
I believe I'm hitting this bug as well.

```
iex(3)> Etl.Repos.SourceRepo.run_query!("select * from orders.promo_codes limit 1")                                                    
[debug] QUERY ERROR db=41.2ms                                                                                                          
select * from orders.promo_codes limit 1 []                                                                                            
[error] Postgrex.Protocol (#PID<0.341.0>) disconnected: ** (RuntimeError) type `citext` can not be handled by the types module Ecto.Adapters.Postgres.TypeModule                                                                                                              
** (RuntimeError) type `citext` can not be handled by the types module Ecto.Adapters.Postgres.TypeModule                               
    (ecto) lib/ecto/adapters/postgres/connection.ex:92: Ecto.Adapters.Postgres.Connection.execute/4                                    
    (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6                                                                  
    (ecto) lib/ecto/adapters/sql.ex:198: Ecto.Adapters.SQL.query!/5                                                                    
```

Unfortunately, I'm connecting to an existing database so I have no control over the fact that the extension is installed inside of the schema (although I agree it's an odd practice).

**Comment by coryasilva** [comment]
Does setting the default search_path in the postgres.conf help?

**Comment by isaacsanders** [comment]
If you set the search path as part of the `after_connect`, each connection will be bootstrapped with the appropriate search path.

**Comment by josevalim** [comment]
Closing per the above, as search_path seems to be enough to solve the issue. Please let us know if otherwise.

**Comment by brunomalvestuto** [comment]
Changing search_path in the postgres.conf does solve the issue, unfortunately for managed environments such as Google Cloud SQL this is not an option.

I tried to set the search_path in the repo after_connect option, but I guess the type checks take place before the after_connect.

`after_connect: {Postgrex, :query!, ["SET search_path TO myschema", []]}`

And I got:

```
** (Postgrex.QueryError) type `citext` can not be handled by the types module Postgrex.DefaultTypes
(ecto_sql) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
(ecto_sql) lib/ecto/adapters/sql.ex:526: Ecto.Adapters.SQL.execute/5
(ecto) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
(ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
(ecto) lib/ecto/repo/queryable.ex:112: Ecto.Repo.Queryable.one/3
```

**Comment by michalmuskala** [comment]
I believe you need to still keep `public` in the search path instead of setting it to that schema only, for example:

```
SET search_path TO myschema,public
```

**Comment by brunomalvestuto** [comment]
@michalmuskala thanks for answering. I tried what you suggested but I am still getting the same error.

It seems it expects the extension to be created in the public schema.

```
CREATE EXTENSION IF NOT EXISTS citext with SCHEMA public;
ALTER TABLE myschema.users ALTER COLUMN email TYPE public.citext;
```

It looks a bit messy but it works around the problem.
