### ISSUE TITLE
Timeout when using pgpool

### ISSUE THREAD

**Issue by mkaszubowski** [elixir-ecto/postgrex#305]
(Related to: https://github.com/elixir-ecto/postgrex/pull/304)

When using Postgrex (with Ecto) without the `:prepare` option set to `:unnamed`, all the queries seem to time out. 

```elixir
** (DBConnection.ConnectionError) tcp recv: closed
    (ecto) lib/ecto/adapters/postgres/connection.ex:86: Ecto.Adapters.Postgres.Connection.prepare_execute/5
    (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
17:04:47.236 [error] Postgrex.Protocol (#PID<0.1471.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1441.0> timed out because it checked out the connection for longer than 15000ms
```
When the option is set, the queries are performed correctly. 

Using `psql` with the same connection url as the one in Ecto works correctly, too. 

After doing some research, I found this bug reported for pgpool: http://www.pgpool.net/mantisbt/print_bug_page.php?bug_id=190 but it is reported for the version 3.5.1 and seems to be solved be attached patch. The fix is present in the version 3.5.2 which I'm using. 

Of course, I'd be happy to provide more details of my setup if it could be helpful.

## Used versions: 
- `postgrex`: 0.13.0
- `ecto`: 2.1.3

with postgres 9.4 and pgpool 3.5.2 with master/slave setup and streaming replication.

**Comment by fishcakez** [comment]
Any chance of minimal test case? no worries if you dont have one.

**Comment by mkaszubowski** [comment]
When it comes to Elixir part, I'm doing a simple `Repo.all(Schema)`. 

I'm not yet sure how to provide the setup for postgres/pgpool. I was mainly following the article here: https://www.itenlight.com/blog/2016/05/18/PostgreSQL+HA+with+pgpool-II+-+Part+1  but it's quite long and not all the steps are required (e.g. the failover). 

I'll try to provide a list of steps required to reproduce the error. Maybe some Docker container would be helpful here? I'll think about soon and try to come up with something when I have some free time.

**Comment by fishcakez** [comment]
I will try to replicate with 3.4.3 because thats what my package manager gives me.

**Comment by mkaszubowski** [comment]
Actually, there were some fix between 3.4.x and 3.5.2 which might affect this. I've installed pgpool from sources from here: `http://www.pgpool.net/download.php?f=pgpool-II-3.5.2.tar.gz`.

**Comment by fishcakez** [comment]
`pgpool` becomes unresponsive when sent valid protocol messages. I'm not really sure why this occurs. I will revert https://github.com/elixir-ecto/postgrex/commit/5c626de28fe4cc4a17f89cd3633d499d31e267d5 as this suggests we support it but we don't.

**Comment by mkaszubowski** [comment]
Shouldn't the docs at least state that it's not supported? I guess it would be nice to have this information somewhere in the docs.

**Comment by fishcakez** [comment]
It's more that it may or may not work, with no promises either way. Therefore we won't claim to support it.

**Comment by mkaszubowski** [comment]
Ok, that makes sense. Thanks for checking it :)

**Comment by mkaszubowski** [comment]
@fishcakez Can you give an example of the valid protocol message which causes the problem? I'll try to make an issue for the pgpool and it would be really helpful.

**Comment by fishcakez** [comment]
There seemed to be many combinations using extended queries where it would stale. I did not try to find minimal cases. `pgpool -d` and running ecto/postgrex without `prepare: :unnamed` should show a simple case.

**Comment by mkaszubowski** [comment]
Great, thanks!

**Comment by OpakAlex** [comment]
hello @mkaszubowski, any progress on this issue? Same for me with pgpool `4.0.2`, and `prepare: :unnamed` didn't help me, now it crashes on `mix ecto.create`
```
11:26:03.673 [error] GenServer #PID<0.548.0> terminating
** (KeyError) key :messages not found in: %{opts: [types: Postgrex.DefaultTypes, max_restarts: 0, backoff_type: :stop, database: "postgres", telemetry_prefix: [:cm_notifications, :repo], otp_app: :cm_notifications, timeout: 15000, username: "postgres", password: "postgres", hostname: "pgpool.staging.svc.cluster.local", show_sensitive_data_on_connection_error: true], prepare: :unnamed, ssl: false, types_key: {'pgpool.staging.svc.cluster.local', 5432, "postgres"}, types_lock: {#PID<0.553.0>, #Reference<0.1669622628.2398617602.225443>}, types_mod: Postgrex.DefaultTypes}
    (stdlib) :maps.get(:messages, %{opts: [types: Postgrex.DefaultTypes, max_restarts: 0, backoff_type: :stop, database: "postgres", telemetry_prefix: [:cm_notifications, :repo], otp_app: :cm_notifications, timeout: 15000, username: "postgres", password: "ee7d1462033a8dd110ff170b52fa4354", hostname: "pgpool.staging.svc.cluster.local", show_sensitive_data_on_connection_error: true], prepare: :unnamed, ssl: false, types_key: {'pgpool.staging.svc.cluster.local', 5432, "postgres"}, types_lock: {#PID<0.553.0>, #Reference<0.1669622628.2398617602.225443>}, types_mod: Postgrex.DefaultTypes})
    (elixir) lib/map.ex:267: Map.update!/3
    (postgrex) lib/postgrex/protocol.ex:2815: Postgrex.Protocol.handle_msg/3
    (postgrex) lib/postgrex/protocol.ex:825: Postgrex.Protocol.bootstrap_recv/5
    (postgrex) lib/postgrex/protocol.ex:576: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:66: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for CmNotifications.Repo couldn't be created: killed
```

**Comment by mkaszubowski** [comment]
Unfortunately no - we decided not to use pgpool at that project, so I haven't spent any more time trying to figure it out.

**Comment by OpakAlex** [comment]
ok, thanks @mkaszubowski. with pgbouncer it works?

**Comment by paveltyk** [comment]
Hi @mkaszubowski 

I've had some success running Postgrex with Pgpool, however, since we've had logging level at INFO I had to update `protocol.ex:825` with a case for `:msg_notice`, since the handshake phase does not have `:messages` key in `status` map it crashed.

```
11:26:03.673 [error] GenServer #PID<0.548.0> terminating
** (KeyError) key :messages not found in: %{opts: [types: Postgrex.DefaultTypes, max_restarts: 0, backoff_type: :stop, database: "***", telemetry_prefix: [:my_app, :repo], otp_app: :my_app, timeout: 15000, username: "***", password: "***", hostname: "***", show_sensitive_data_on_connection_error: true], prepare: :unnamed, ssl: false, types_key: {'***', 5432, "postgres"}, types_lock: {#PID<0.553.0>, #Reference<0.1669622628.2398617602.225443>}, types_mod: Postgrex.DefaultTypes}
    (stdlib) :maps.get(:messages, %{opts: [types: Postgrex.DefaultTypes, max_restarts: 0, backoff_type: :stop, database: "***", telemetry_prefix: [:my_app, :repo], otp_app: :my_app, timeout: 15000, username: "***", password: "***", hostname: "***", show_sensitive_data_on_connection_error: true], prepare: :unnamed, ssl: false, types_key: {'***', 5432, "postgres"}, types_lock: {#PID<0.553.0>, #Reference<0.1669622628.2398617602.225443>}, types_mod: Postgrex.DefaultTypes})
    (elixir) lib/map.ex:267: Map.update!/3
    (postgrex) lib/postgrex/protocol.ex:2815: Postgrex.Protocol.handle_msg/3
    (postgrex) lib/postgrex/protocol.ex:825: Postgrex.Protocol.bootstrap_recv/5
    (postgrex) lib/postgrex/protocol.ex:576: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:66: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for CmNotifications.Repo couldn't be created: killed
```

Please advice how should I handle that case correctly, and let me know if PR for this case will be acceptable.

Thanks in advance.

**Comment by mkaszubowski** [comment]
@paveltyk As I'm not a maintainer of postgrex, you should probably mention @fishcakez  here :)

**Comment by Zatvobor** [comment]
@paveltyk, Anyway, let's make a PR, so we can fix it and use it from here or even from fork.

**Comment by BartOtten** [comment]
> I've had some success running Postgrex with Pgpool,

@paveltyk care to share how? I've been trying for a few hours now but can't find the issue (nor a solution). Using Ecto 3 with Postgres, no SSL and prepare: :unnamed.

**Comment by paveltyk** [comment]
@BartOtten https://github.com/elixir-ecto/postgrex/pull/451

**Comment by elliottminns** [comment]
Any update on this? Haven't managed to get Ecto working with PgPool at all, just seems to hang.

**Comment by msudgh** [comment]
I think the same issue is happening to me, it throws a timeout error while using PGPool. I'm not sure its protocol incompatibility in connection-level or not but from the side of `pgpool`, logs indicate that connection retrieved from front-end(Elixir App).

```bash
$ mix ecto.create
** (Mix) The database for App.Repo couldn't be created: command timed out
```

PGPool Logs:
```
2021-02-23T09:50:52.933326000Z 2021-02-23 09:50:52: pid 146: ERROR:  unable to read data from frontend
2021-02-23T09:50:52.933423900Z 2021-02-23 09:50:52: pid 146: DETAIL:  EOF encountered with frontend
2021-02-23T09:51:09.200791600Z 2021-02-23 09:51:09: pid 1: LOG:  child process with pid: 145 exits with status 256
```

@fishcakez It'd be better to reopen the issue.
