### ISSUE TITLE
Cant get ltree extension to work.

### ISSUE THREAD

**Issue by abhinavzspace** [elixir-ecto/postgrex#306]
I am using the phoenix framework and trying to use ltree extension.

Getting the following error while migrating a table by running `mix ecto.migrate`:
```
19:24:25.241 [error] Could not update schema migrations. This error typically happens when the "schema_migrations" table, which Ecto uses for storing migrationinformation, is already used by another library or for other purposes.

You can fix this by running `mix ecto.drop` in the appropriate `MIX_ENV` to drop the existing database and let Ecto start a new one with a proper definition of "schema_migrations" or by configuring the repository to use another source:

    config :d_server, DServer.Repo,
      migration_source: "some_other_table_for_schema_migrations"

The full error is shown below.

** (ArgumentError) Postgrex expected %NaiveDateTime{}, got {{2017, 3, 29}, {13, 54, 25, 210847}}. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
    deps/postgrex/lib/postgrex/type_module.ex:717: DServer.PostgrexTypes.encode_params/3
```

What I am trying to do is to install "ltree" extension. I followed the following steps:
1. Defined ltree extension and used Postgrex.Types.define() exactly as mentioned [here](https://hexdocs.pm/postgrex/Postgrex.Extension.html#content).
2. Then changed database settings in dev.exs like this:
```
# Configure your database
config :d_server, DServer.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "d_server_dev",
  hostname: "localhost",
  pool_size: 10,
  types: DServer.PostgrexTypes
```

I am new with all these technologies. I apologise if I have missed something trivial here.

**Comment by josevalim** [comment]
See Extensions here: https://hexdocs.pm/ecto/Ecto.Adapters.Postgres.html
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by abhinavzspace** [comment]
Yes read that, but I am not sure if I understood a lot.

I have a file with name `postgrex_types.ex` in `lib/d_server/` with following content:
```
Postgrex.Types.define(DServer.PostgrexTypes, [{DServer.LTree, :copy}])
```

 and another named `ltree.ex` with:
```
defmodule DServer.LTree do
  @behaviour Postgrex.Extension
  
  def init(opts) when opts in [:reference, :copy], do: opts
  
  def matching(_opts), do: [type: "ltree"]
  
  def format(_opts), do: :text
  
  def encode(_opts) do
    quote do
      bin when is_binary(bin) ->
        [<<byte_size(bin) :: signed-size(32)>> | bin]
    end
  end
  
  def decode(:reference) do
    quote do
      <<len::signed-size(32), bin::binary-size(len)>> ->
        bin
    end
  end
  def decode(:copy) do
    quote do
      <<len::signed-size(32), bin::binary-size(len)>> ->
        :binary.copy(bin)
    end
  end
end
```

**Comment by michalmuskala** [comment]
You still need to include the standard types in your custom types module. The module you defined above is able of handling **only** the ltree type, and nothing else.

**Comment by abhinavzspace** [comment]
Thanks! It works. 

Actually I tried that last time also. But then when I ran `mix ecto.drop`, extension from database also got deleted. So I was getting `missing ltree` error.

I am sorry for bothering.
