### ISSUE TITLE
How do you pass parameters to a query?

### ISSUE THREAD

**Issue by drozzy** [elixir-ecto/postgrex#308]
How do I properly pass parameters to a query? I have something like this:

```
CREATE TABLE my_table (
    id SERIAL,
    my_id uuid UNIQUE NOT NULL,
    my_name text
);
```

and here is the query I am issuing:
```
query = "INSERT INTO my_table (my_id, my_name) VALUES ('#{my_id}', '#{my_name}')"
Postgrex.query!(pid, query, [])

```
Where `my_id` is a string containing uuid like `"c4bbeca6-03a6-45b9-a35d-5d41a2b44442"` and `my_name` is just a string of arbitrary text.
But if the `my_name` variable has an apostrophe in it, like `"Scott's Bakery"` it breaks my query.

Tried looking at the [tests](https://github.com/elixir-ecto/postgrex/blob/master/test/query_test.exs) and doing this, but it still doesn't work:

```
query = "INSERT INTO my_table (my_id, my_name) VALUES ($1, $2)" 
Postgrex.query!(pid, query, [my_id, my_name])
```
since the first parameter breaks it now:

`Postgrex expected a binary of 16 bytes, got "c4bbeca6-03a6-45b9-a35d-5d41a2b44442"`

What am I doing wrong?

**Comment by drozzy** [comment]
Strange, if I convert the `my_id` to binary, e.g.:

`UUID.string_to_binary!(my_id)`

and then pass it as a parameter, it works.

But why does this work then?
```
query = "INSERT INTO my_table (my_id, my_name) VALUES ('#{my_id}', '#{my_name}')"
```
It's like it automatically casts it correctly...

**Comment by josevalim** [comment]
Because Postgres itself, the database, handles the query itself in the first case. When you pass parameters, it leaves it up to developers.
