### ISSUE TITLE
Exception: has invalid types for the connection

### ISSUE THREAD

**Issue by ottojimb** [elixir-ecto/postgrex#309]
Hi!

I'm getting the following issue:

```elixir
ArgumentError{message: \"query %Postgrex.Query{columns: ["id", "name", "internal", "inserted_at", "updated_at"], name: "ecto_616034", param_formats: [:binary], param_oids: [25], param_types: [Postgrex.Extensions.Raw], ref: #Reference<0.0.1.107309>, result_formats: [:binary, :binary, :binary, :binary, :binary], result_oids: [23, 1043, 16, 1184, 1184], result_types: [Postgrex.Extensions.Int4, Postgrex.Extensions.Raw, Postgrex.Extensions.Bool, Ecto.Adapters.Postgres.TimestampTZ, Ecto.Adapters.Postgres.TimestampTZ], statement: "SELECT r0.\"id\", r0.\"name\", r0.\"internal\", r0.\"inserted_at\", r0.\"updated_at\" FROM \"roles\" AS r0 WHERE (r0.\"name\" = $1)", types: {Ecto.Adapters.Postgres.TypeModule, 35356751}} has invalid types for the connection\"}", status: "error"}
```

My model schema is defined as following:

```elixir
  schema "roles" do
    field :name, :string
    field :internal, :boolean
    many_to_many :user_organizations, User.Models.UserOrganization, join_through: "roles_users_organizations"
    many_to_many :sessions, User.Models.Session, join_through: "roles_sessions"

    timestamps()
  end
```

The tests are running ok on my local machine, but it happens every time on semaphoreci. I'm using docker-compose with the "postgis" image I have already tried with the "postgres" image with the same results. 

Any suggestion is greatly appreciated. 

Thanks!

**Comment by fishcakez** [comment]
The error should mean that a query was prepared using a different type cache to the one used by the connection executing the query. I am unsure why this would happen, so unfortunately not enough to go on yet.

**Comment by ottojimb** [comment]
Thanks for the tip about the different cache. Now I have a idea to get a more concise search about it.
 
The images I tried:

mdillon/postgis:9.1
postgres/9.6

On the local machine I'm using postgres.app with postgres (PostgreSQL) 9.6.1

The full [log](https://hastebin.com/jisiyojexe.vbs)

**Comment by josevalim** [comment]
@ottojimb the particular error in your log is happening because you seem to already have a schema_migrations table but it is defined with a different schema than Ecto's. If you follow the advice there, you should fix it:

    config :core, Core.Repo,
      migration_source: "some_other_table_for_schema_migrations"

Btw, sorry for the delay on this. If you have more information about the first error, please let us know! Thank you!
