### ISSUE TITLE
WHERE .. IN ..

### ISSUE THREAD

**Issue by radiospiel** [elixir-ecto/postgrex#311]
I have trouble executing a WHERE .. IN query. I guess I miss something fundamental here.

    Postgrex.query!(conn, "SELECT * FROM #{table_name} WHERE id IN ($1)", [[1,2]]) 

results in:

    Postgrex expected an integer in -2147483648..2147483647, got [1, 2]. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.

What am I missing here?

**Comment by josevalim** [comment]
@radiospiel that's likely a question about Postgres syntax. You likely want this or similar instead:

    Postgrex.query!(conn, "SELECT * FROM #{table_name} WHERE id = ANY($1)", [[1,2]])

**Comment by radiospiel** [comment]
I see, thank you very much!
