### ISSUE TITLE
Error connecting to remote database through SSH tunnel

### ISSUE THREAD

**Issue by sineed** [elixir-ecto/postgrex#313]
I have a problem connecting to remote db through ssh tunnel.
Steps to reproduce (real names are replaced for security purposes):
1. `ssh -fN -L 5555:localhost:5432 user@staging.com`
2. in `iex -S mix`: `Postgrex.start_link(hostname: "localhost", port: 5555, database: "staging_db", username: "user", password: "long_password")`

Expected: `{:ok, pid}`
Actual: `[error] Postgrex.Protocol (#PID<0.333.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password): password authentication failed for user "user"`

Connecting through psql (`psql -d staging_db -h localhost -p 5555 -U user` and with the same password prompted) works.

My pg_hba.conf on staging server contains the following row for local connections:
```
TYPE    DATABASE        USER            ADDRESS                 METHOD
host    all             all             localhost               md5
```
PostgreSQL version is 9.4.4.

I reproduced this error on 0.13.0 and 0.13.2 versions. 

I found that it goes to disconnection (https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/protocol.ex#L568) after sending auth md5 message.

UPD: I receive the same error when I change auth method from `md5` to `password` in pg_hba.conf

**Comment by ericmj** [comment]
I cannot reproduce this for databases that runs on other machines. At work we regularly connect to AWS RDS instances by port forwarding the EC2 instance that has access to the RDS instance and this works.

**Comment by sineed** [comment]
I successfully established a connection to the another server. I think there is not problem with binary communication.
Closing this, sorry for disturbance

**Comment by papakay** [comment]
Please how do you achieve connection to a remote database. I have a mysql hosted inside a vagrant vm. I want to connect ecto to this db but all attempts failed. 

Below is what my connection config looks like

```
config :product, Product.Repo,
  adapter: Ecto.Adapters.MySQL,
  username: "root",
  password: "testpassword",
  database: "testdb",
  hostname: "localhost",
  pool_size: 10
```

**Comment by papakay** [comment]
It's resolved now. The information here helped me to resolve it. Thanks.

**Comment by salimane** [comment]
@papakay what was the solution ?

**Comment by papakay** [comment]
@salimane, i have inside ~/.ssh/config the following configuration:

```
Host connect.db
	HostName 127.0.0.1
	User ubuntu
	Port 2222
	IdentityFile ~/vagrant/.vagrant/machines/default/virtualbox/private_key
```
Then i ran this command on the terminal:
```
ssh -fN -L 5555:localhost:3306 connect.db
```
**5555 is the port that will be forwarded to localhost:3306**. You can change the port number to anything you want.

The use case above was for a mysql database connection but I believe you can also use it for postgres as well by just changing a few parameters.

I hope this helps.

**Comment by papakay** [comment]
@salimane, I forgot to add that your repo configuration will look like below
```
config :product, Product.Repo,
  adapter: Ecto.Adapters.MySQL,
  username: "root",
  password: "testpassword",
  database: "testdb",
  hostname: "localhost",
  port: 5555,
  pool_size: 10
```

**Comment by salimane** [comment]
@papakay thanks
