### ISSUE TITLE
Overriding builtin extension

### ISSUE THREAD

**Issue by plamb** [elixir-ecto/postgrex#315]
I'm in the process of upgrading an older ecto app and I need to have the json and jsonb extension return atoms for the keys (yes, I know). In the past, I used my own json/jsonb extension since there wasn't one in postgrex already.

I followed the extensions directions with my own custom json/jsonb extension (all it does is add the keys: :atoms option to the decode call). But my extension does not get called, it looks like the built-in extensions get first priority.

Any thoughts on the best way to handle this?

**Comment by josevalim** [comment]
There is a :json option that you can pass when defining `Postgres.Types` and you will have to provide a module that implements encode and decode.

**Comment by plamb** [comment]
I kept thinking this should be easier and, of course, it is. Thanks for the quick reply.
