### ISSUE TITLE
:bigint field type

### ISSUE THREAD

**Issue by comboy** [elixir-ecto/postgrex#316]
I'm trying to use a `bigint` column. Bigint as a type in migration works fine, but when trying to define field like so:

    field :foo, :bigint

I get `invalid or unknown type :bigint for field :sequence`. When I try `integer` then even though the column is bigint I get `Postgrex expected an integer in -2147483648..2147483647`

Am I doing something wrong or is this an opportunity for contribution?

**Comment by ericmj** [comment]
This is an ecto specific question and please don't post questions in the tracker. On fields use ecto types, it only has the integer type `:integer`, specify the database type in your migration.

**Comment by comboy** [comment]
Could you redirect me to more appropriate place to ask question if this is not a bug? 

Database type in migration is specified as `:bigint` (and properly created in pg), yet the Postgrex raises the error mentioned in the first message.

Problem does not happen for `Repo.insert`, just for `Repo.insert_all`. I know these are Ecto functions, but the exception comes from Postgrex.

**Comment by ericmj** [comment]
> Could you redirect me to more appropriate place to ask question if this is not a bug?

This is where you can ask questions: https://github.com/elixir-ecto/ecto#contributing

> Problem does not happen for Repo.insert, just for Repo.insert_all.

This is hard to know for us since you only pasted one line of code, which is not where the exception is from and does not relate to this library.

**Comment by comboy** [comment]
Just in case checking it would cross your mind, it was my fault. So dumb. I'm really sorry about wasting your time 

(but I was so convinced, I was already adding `location: keep` to all `quote`s in postgrex to figure it out ;) ).
