### ISSUE TITLE
Postgrex.TypeServer exits if Postgrex.Notifications used when Postgres connection invalid

### ISSUE THREAD

**Issue by evadne** [elixir-ecto/postgrex#318]
As subject.

If `Postgrex.Notifications.start_link` is used with invalid Postgres connection details, the type server exits (instead of raising an exception, etc).

Reduced test case available here https://github.com/evadne/postgrex-issue-318

    ➜  evadne-postgrex-issue-318 git:(master) iex -S mix
    Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

    Interactive Elixir (1.4.4) - press Ctrl+C to exit (type h() ENTER for help)
    iex(1)> 
    23:56:55.352 [error] GenServer #PID<0.168.0> terminating
    ** (stop) %DBConnection.ConnectionError{message: "tcp connect (localhost:16384): connection refused - :econnrefused"}
    Last message: nil
    State: [types: Postgrex.DefaultTypes, otp_app: :sample, adapter: Ecto.Adapters.Postgres, username: "hello", password: "world", database: "bogus", hostname: "localhost", port: 16384]

    23:56:55.352 [error] GenServer #PID<0.174.0> terminating
    ** (stop) %DBConnection.ConnectionError{message: "tcp connect (localhost:16384): connection refused - :econnrefused"}
    Last message: nil
    State: [types: Postgrex.DefaultTypes, otp_app: :sample, adapter: Ecto.Adapters.Postgres, username: "hello", password: "world", database: "bogus", hostname: "localhost", port: 16384]

    23:56:55.352 [error] GenServer #PID<0.176.0> terminating
    ** (stop) %DBConnection.ConnectionError{message: "tcp connect (localhost:16384): connection refused - :econnrefused"}
    Last message: nil
    State: [types: Postgrex.DefaultTypes, otp_app: :sample, adapter: Ecto.Adapters.Postgres, username: "hello", password: "world", database: "bogus", hostname: "localhost", port: 16384]

    23:56:55.352 [error] GenServer #PID<0.178.0> terminating
    ** (stop) %DBConnection.ConnectionError{message: "tcp connect (localhost:16384): connection refused - :econnrefused"}
    Last message: nil
    State: [types: Postgrex.DefaultTypes, otp_app: :sample, adapter: Ecto.Adapters.Postgres, username: "hello", password: "world", database: "bogus", hostname: "localhost", port: 16384]

    23:56:55.352 [info]  Application sample exited: shutdown

I’d think that ideally it should just error.

**Comment by evadne** [comment]
I’ve got a fix which requires trapping exit and using `sync_connect`

According to @fishcakez 
1. the connection is asynchronous by default in order not to cause problems with connection pools
2. notifications shouldn’t bootstrap

**Comment by fishcakez** [comment]
Given the guarantees provided by Postgrex.Notifications (only works when connect and can't reconnect) we should force `sync_connect: true`.

**Comment by josevalim** [comment]
Thanks @evadne! :heart: Closing in favor of the PR!
