### ISSUE TITLE
Postgrex.Notifications.start_link does not parse :url

### ISSUE THREAD

**Issue by bechurch** [elixir-ecto/postgrex#319]
## Overview
When setting up a `GenServer` to listen for `pg_notify` events it would work locally but would fail when deployed to Heroku.

This was because Heroku uses a connection url instead of specifying `host`, `username`, `port`, ect.

The app was parsing the url in config fine
```elixir
# prod.exs
config :appname, AppName.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "dbname",

  # Used by Heroku
  url: System.get_env("DATABASE_URL"),
```

However when calling `Postgrex.Notifications.start_link` in my genserver:
```elixir
  @doc """
  When the GenServer starts subscribe to the given channel
  """
  @spec init([String.t])  :: {:ok, []}
  def init(channel) do
    Logger.debug("Starting #{ __MODULE__ } with channel subscription: #{channel}")

    pg_config = Application.get_env(:appname, AppName.Repo)

    {:ok, pid} = Postgrex.Notifications.start_link(pg_config)
    {:ok, ref} = Postgrex.Notifications.listen(pid, channel)
    {:ok, {pid, channel, ref}}
  end
```

This error is thrown
```elixir
** (KeyError) key :hostname not found in: [types: nil, types: Postgrex.DefaultTypes, adapter: Ecto.Adapters.Postgres, database: "dbname", url: "redactedurl", ssl: false, pool_size: 2]
```

This was easily fixable by using `Ecto.Repo.Supervisor.parse_url`:
```elixir
  def get_pg_config do
    pg_config = Application.get_env(:trips_web, TripsWeb.Repo)
    {url, pg_config} = Keyword.pop(pg_config, :url)
    Keyword.merge(pg_config, Ecto.Repo.Supervisor.parse_url(url || ""))
  end
```

but it wasn't obvious and I'd expect if postgrex parses the `url` parameter typically it should also do this here.

Let me know if you have any question! Thanks for this wonderful project btw!

**Comment by michalmuskala** [comment]
The `url` option is not supported by postgrex. Fortunately, you don't need to use private Ecto functions (that could change at any moment), since you have a public function to get full configuration - [`AppName.Repo.config()`](https://hexdocs.pm/ecto/Ecto.Repo.html#c:config/0).

**Comment by josevalim** [comment]
Yes, it is an Ecto feature. You can either get the config as @michalmuskala said or send it as not a URL.

**Comment by bechurch** [comment]
@josevalim @michalmuskala sorry the false bug request and thanks for the advice!
