### ISSUE TITLE
Can not establish SSL connection when :ssl app is not started

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-ecto/postgrex#324]
While running migrations ([here is a code](https://gist.github.com/AndrewDryga/a9172fbd9351d0b89092ff35d5912b40/b5ba6ee5390f263cf855fe852322c3a42675f084)) we have faced a weird issue:
```
Loading app..
Starting dependencies..
Starting repos..
Running migrations for myapp
{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.DBConnection.ConnectionError',message=><<"connection not available because of disconnection">>},[{'Elixir.DBConnection',checkout,2,[{file,"lib/db_connection.ex"},{line,926}]},{'Elixir.DBConnection',run,3,[{file,"lib/db_connection.ex"},{line,742}]},{'Elixir.DBConnection',run_meter,3,[{file,"lib/db_connection.ex"},{line,1133}]},{'Elixir.DBConnection',prepare_execute,4,[{file,"lib/db_connection.ex"},{line,584}]},{'Elixir.Ecto.Adapters.Postgres.Connection',execute,4,[{file,"lib/ecto/adapters/postgres/connection.ex"},{line,93}]},{'Elixir.Ecto.Adapters.SQL',sql_call,6,[{file,"lib/ecto/adapters/sql.ex"},{line,243}]},{'Elixir.Ecto.Adapters.SQL','query!',5,[{file,"lib/ecto/adapters/sql.ex"},{line,193}]},{'Elixir.Ecto.Adapters.Postgres','-execute_ddl/3-fun-0-',4,[{file,"lib/ecto/adapters/postgres.ex"},{line,86}]}]}}
init terminating in do_boot ()
Crash dump is being written to: erl_crash.dump...done
```

PosgtrSQL log has an error entry:
```
2017-08-22T10:26:28+00:00 app[postgres.15761]: [DATABASE] [5-1]  sql_error_code = 08P01 LOG:  could not accept SSL connection: EOF detected
```

This were fixed by starting :ssl app before Postgrex, but the error is not clear enough and I don't think that we should try to establish an SSL connection when `:ssl` is not started. Maybe let's add `Application.ensure_started/1` before establishing an SSL connection?

**Comment by josevalim** [comment]
Doing application:ensure_started will hide bugs, because it will work in development but not if you build a release, as ssl may not actually be there.

**Comment by AndrewDryga** [comment]
You are right. Let's throw an error when `:ssl` is not there?

**Comment by fishcakez** [comment]
@AndrewDryga I wonder why there isn't a log message when the postgrex connection failed to connect?

**Comment by AndrewDryga** [comment]
@fishcakez I have no ideas :(

**Comment by fishcakez** [comment]
@AndrewDryga me neither.

You are right that we should throw an error. We should do this check during the `start_link` call because a postgrex pool needs this guarantee when it starts up. If these are not started it should fail there because it will never be able to serve requests to later children. Under the poolboy pool it will crash repeatedly, which is not good fault tolerance.
