### ISSUE TITLE
Postgrex.Range cannot not distinguish between empty and infinite (unbounded) ranges

### ISSUE THREAD

**Issue by fsabe** [elixir-ecto/postgrex#333]
@mememori and I stumbled upon an issue with how Postgrex encoded infinite (unbounded) ranges when both the lower and upper bound were omitted—meaning that all values are considered to be in the range. This was solved by https://github.com/elixir-ecto/postgrex/pull/332.

This solution, however, introduced a different problem. Now there is no way to distinguish between an unbounded range and an empty range in the Postgrex.Range struct, because both are represented as `%Postgrex.Range{lower: nil, upper: nil}`.

It also means that that was a **breaking change**, because what was previously interpreted as an empty range will now be assumed to be an unbounded range.

We need a way to represent an empty range that is different from an unbounded range. PostgreSQL uses `'(,)'` to represent an unbounded range, while empty ranges are normalized to `'empty'`.

**Comment by mememori** [comment]
If i am not mistaken, unbounded is `%Postgrex.Range{lower: nil, upper: nil, lower_inclusive: false, upper_inclusive: false}` and empty is `%Postgrex.Range{lower: nil, upper: nil, lower_inclusive: true, upper_inclusive: true}`

**Comment by mememori** [comment]
Test code:

```
IO.inspect query("SELECT '[5,5]'::int4range", [])
IO.inspect query("SELECT '(5,5)'::int4range", [])
IO.inspect query("SELECT '(,)'::int4range", [])
IO.inspect query("SELECT '[,]'::int4range", [])
```

Result
```
[[%Postgrex.Range{lower: 5, lower_inclusive: true, upper: 6,
   upper_inclusive: false}]]
[[%Postgrex.Range{lower: nil, lower_inclusive: true, upper: nil,
   upper_inclusive: true}]]
[[%Postgrex.Range{lower: nil, lower_inclusive: false, upper: nil,
   upper_inclusive: false}]]
[[%Postgrex.Range{lower: nil, lower_inclusive: false, upper: nil,
   upper_inclusive: false}]]
```

**Comment by josevalim** [comment]
Maybe it would be better to have `upper: :empty, lower: :empty` for empty and `:unbounded` from unbounded ones. @ericmj ?

**Comment by ericmj** [comment]
👍 on using the atoms instead of nil.

**Comment by mememori** [comment]
:+1: i agree atoms would make it easier to distinguish :)

Also, side-note, my PR did not introduce a breaking change as it does not change the program behaviour in a way that would break code that previously worked :P

**Comment by josevalim** [comment]
Closing in favor of the PR: https://github.com/elixir-ecto/postgrex/pull/380
