### ISSUE TITLE
Postgrex.Extensions.Path sends true for open paths, but protocol wants the opposite

### ISSUE THREAD

**Issue by evadne** [elixir-ecto/postgrex#341]
Referring to PostgreSQL source code for `path_send` in `geo_ops.c`:

```
path_send(PG_FUNCTION_ARGS)
{
    PATH       *path = PG_GETARG_PATH_P(0);
    StringInfoData buf;
    int32       i;

    pq_begintypsend(&buf);
    pq_sendbyte(&buf, path->closed ? 1 : 0);
    pq_sendint32(&buf, path->npts);
    for (i = 0; i < path->npts; i++)
    {
        pq_sendfloat8(&buf, path->p[i].x);
        pq_sendfloat8(&buf, path->p[i].y);
    }
    PG_RETURN_BYTEA_P(pq_endtypsend(&buf));
}
```

It would seem that the code implies that a closed path will have the flag set to `true`, while an open path will have the flag set to `false`. However, in `Postgrex.Extensions.Path`:

```
def decode_path(<<o::int8, n::int32, point_data::binary-size(n)-unit(128)>>) do
  open = (o == 1)
  …
end

def open_to_byte(true), do: 1
def open_to_byte(false), do: 0
```

I am inclined to believe that Postgrex should change to match the protocol. 🤔

**Comment by dantswain** [comment]
This is in fact correct.  I must have flipped the logic somehow in my head.  The current test reads:

```
    path = %Postgrex.Path{points: [p1, p2, p3], open: false}
    assert [[path]] == query("SELECT '[(0.0,0.0),(1.0,3.0),(-4.0,3.14)]'::path", [])
```

But according to the docs `[...]` is an open path, so that test SHOULD actually fail.
