### ISSUE TITLE
Mapping a Postgres TIMESTAMP onto a elixir datatype

### ISSUE THREAD

**Issue by mszmurlo** [elixir-ecto/postgrex#344]
I have a table created and populated with:
 
    CREATE TABLE my_test ( ts TIMESTAMP );
    INSERT INTO my_test (ts) VALUES (now()::timestamp);

Just to validate:

    SELECT * FROM my_test;
                 ts             
    ----------------------------
     2017-11-05 14:41:42.425341
    (1 row)

So far so good. Now, if I ask the SQL adapter in Postgrex to do the select, I get:

    iex(144)> Ecto.Adapters.SQL.query(MyApp.Repo, "select * from my_test")
    [debug] QUERY OK db=1.1ms
    select * from my_test []
    {:ok,
     %Postgrex.Result{columns: ["ts"], command: :select, connection_id: 12634,
      num_rows: 1, rows: [[{{2017, 11, 5}, {14, 41, 42, 425341}}]]}}

Provided the type mappings in the documentation I would have expected something like: `%Postgrex.Timestamp{year: 2017, month: 11, day: 5,  hour: 14, min: 41, sec: 12, usec: 425341}` or a `%DateTime{ ... }` (depending on if you're reading the doc here or on hex) rather than `{{2017, 11, 5}, {14, 41, 42, 425341}}`.

Am I mistaken  ?

**Comment by josevalim** [comment]
Ecto 2 has to override the builtin types for backwards compatibility but
this is no longer the case in Ecto master.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
