### ISSUE TITLE
Cut a new version! (12.3?)

### ISSUE THREAD

**Issue by bshaffer** [elixir-ecto/postgrex#355]
Hello Postgrex maintainers!

We would love to get a new version released for postgrex so that the ability to connect to unix sockets (https://github.com/elixir-ecto/postgrex/pull/326) will be available on hex. 

What is the process for this and how can we help? Thank you!

(see https://github.com/GoogleCloudPlatform/elixir-runtime/issues/6)

**Comment by fishcakez** [comment]
We are currently mid-way through changing how Ecto handles transactions and cursors (postgreSQL portals) so it would not be possible to release a new version from master for a while. We are actually pointing directly at git for a few dependencies on master branches so in an awkward spot and pointing to git may not be wise. Did not plan a release for another month.

Technically it looks like we could release a 0.14.0 with parent at https://github.com/elixir-ecto/postgrex/commit/940c1126a68ad0df065c79980f0fc776ba10633a. This would break semver for commits in the last 2 weeks.

We don't backport new features to prior releases normally, and usually only apply bugfixes to the last release so would prefer not to backport local socket support.

**Comment by bshaffer** [comment]
Releasing 0.14.0 would be great. Sorry but how does this break semver? BC breaking changes can take place on minor versions pre-1.0.

**Comment by fishcakez** [comment]
@bshaffer it doesn't, except people may have fetched 0.14.0-dev from git when it isn't when using Ecto master.

**Comment by fishcakez** [comment]
@bshaffer the release is a little awkward for us so we will hold off with our planned schedule unless there is more demand. If someone wants to use unix sockets then I would suggest they use https://github.com/elixir-ecto/postgrex/commit/940c1126a68ad0df065c79980f0fc776ba10633a.

**Comment by jameskerr** [comment]
Google cloud released their official elixir support for App Engine yesterday: https://cloud.google.com/elixir/

What great news for Elixir!

I've been trying to deploy connect my existing Google Cloud SQL using their recommended unix socket method, but it looks I'll need to point to 940c112. 

Due to the official Elixir support and this hacker news article (https://news.ycombinator.com/item?id=16208809), I'll bet there will be more people asking for socket support.

**Comment by josevalim** [comment]
@jameskerr could you please give the v0.13 branch a try? I have backported the socket option and a couple other fixes to make sure we run mostly without warnings on v1.6.

@fishcakez @ericmj is there anything you want to backport for a new v0.13 release? You can see the [current diff here]( https://github.com/elixir-ecto/postgrex/compare/v0.13.3...v0.13).

**Comment by josevalim** [comment]
Eerrr, I will open a new issue. :) This one is quite old.
