### ISSUE TITLE
How do I define the json library

### ISSUE THREAD

**Issue by jtmkrueger** [elixir-ecto/postgrex#358]
I'm just trying to use Postgrex without any kind of ecto setup, so just the example from the documentation readme.

Here is what my module looks like:
```
defmodule Receive do

  def start(_type, _args) do
    {:ok, pid} = Postgrex.start_link(
      hostname: "localhost",
      username: "john",
      # password: "",
      database: "property_actions",
      extensions: [{Postgrex.Extensions.JSON}]
    )
    Postgrex.query!(
      pid,
      "INSERT INTO actions (search_terms) VALUES ($1)",
      [
        %{foo: 'bar'}
      ]
    )

  end
end
```
when I run the code I get
```
** (RuntimeError) type `json` can not be handled by the types module Postgrex.DefaultTypes, it must define a `:json` library in its options to support JSON types
```

Is there something I'm not setting up correctly? From what I've gathered in the documentation, I shouldn't even need to have that extensions line because json is handled by default.

**Comment by josevalim** [comment]
You need to define your own types:

```elixir
Postgrex.Types.define(MyApp.PostgrexTypes, [], json: Poison)
```

and then when starting Postgrex:

```elixir
Postgrex.start_link(types: MyApp.PostgrexTypes)
```

Alternatively you can use master which supports a json_library option (see the README).

**Comment by jtmkrueger** [comment]
yea, I just needed to switch to master, thanks for the quick response and sorry for the noise!
