### ISSUE TITLE
Postgrex.Notifications doesn't alert you to when the connection dies

### ISSUE THREAD

**Issue by SkipMike** [elixir-ecto/postgrex#359]
Our Postgrex.Notifications listener dies silently. It doesn't seem to send any messages to it's parents and it stays up. This seems to be undesirable behavior, if we don't know that our listener isn't listening then we can't restart it.

I'm wondering if I'm missing something about the behavior. Is there undocumented messages that are sent when the listeners connection dies? Or is this just new behavior that can be added.

**Comment by josevalim** [comment]
@SkipMike you can do a test: what happens if in your development machine you start a notifications listener and then you shutdown postgres? Does the process crash? Is anything logged?

It can also be that it is crashing but your supervision strategy is not restarting it.

**Comment by josevalim** [comment]
Ping. :)

Also, can you include a simple application that reproduces the error?

**Comment by SkipMike** [comment]
@josevalim sorry about going silent. We tried your suggestion of turning of the DB and we did see that the Notifications process would die, kill our genserver, and then get restarted, as desired. However, in our instance, our connection to our DB is killed by our infrastructure. Our Ecto Connection pool tells us it goes down and restarts and operates normally. However, the Notification process does not die, we just silently stop getting notifications.

We're not exactly sure how to provide a minimal case. I've talked some with my co-workers about how we can replicate it, but since the connection killing is done by our VM host, I'm not sure what we can do.

Do you have suggestions on how we can replicate our network killing our connections?

**Comment by josevalim** [comment]
Thanks @SkipMike. I am not sure how to kill the connection, I guess that's the next step to figure out. Maybe employing some sort of PING would help figure out the connection is dead?

**Comment by josevalim** [comment]
@SkipMike maybe you can use iptables or something at the OS level to simulate netsplits?

In any case, please let us know if you have any issues here. I have also replied on #375, which is related. If you have a way to reproduce the issue, I can take a look at it. I will close this so we track everything there until we have solid reproduction cases.
