### ISSUE TITLE
Release v0.13.4

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/postgrex#360]
@fishcakez @ericmj is there anything you want to backport for a new v0.13 release? You can see the [current diff here](https://github.com/elixir-ecto/postgrex/compare/v0.13.3...v0.13).

It currently includes the socket option and fixes warnings on v1.6.

/cc @jameskerr

**Comment by jameskerr** [comment]
Coming from https://github.com/elixir-ecto/postgrex/issues/355#issuecomment-360064905 

Using the socket: option with the v0.13 branch worked for the App Engine and Cloud SQL. Thank you!

**Comment by fishcakez** [comment]
Could we rename `socket` to `socket_dir` before release please as its more accurate description.

**Comment by josevalim** [comment]
Done!
