### ISSUE TITLE
Cannot connect to Google Cloud SQL instance using :socket_dir option

### ISSUE THREAD

**Issue by sausman** [elixir-ecto/postgrex#365]
I was trying to connect to a Cloud SQL instance using the `:socket_dir` option, but couldn't get it to work with [cloudsql-proxy](https://github.com/GoogleCloudPlatform/cloudsql-proxy).

cloudsql-proxy expects the filename to be the "Instance connection name" of the Cloud SQL instance you are trying to connect to. For example:

```
# For -fuse you do not need to specify instance names ahead of time:
./cloud_sql_proxy -dir=/cloudsql -fuse &
mysql -u root -S /cloudsql/my-project:us-central1:sql-inst
```

Postgrex [currently](https://github.com/elixir-ecto/postgrex/blob/5e787635097b393aa169fc0270d3f973a76b08c8/lib/postgrex/protocol.ex#L49) doesn't allow a filename to be configured for the socket.

```elixir
{{:local, "#{socket}/.s.PGSQL.#{port}"}, 0}
```

I was able to get it working with this [small change](https://github.com/sausman/postgrex/commit/dbf41a99f2e9e24364a893bdaa211166f7a41474) that allows the full path to be specified. I can work on a pull request, but wanted to get some feedback on the desired behavior.

Thanks!

**Comment by josevalim** [comment]
@sausman can you please send a pull request where we also accept a `:socket_file` configuration too? So the plan is:

  1. Try socket_file
  2. Try socket_dir
  3. Fallback to hostname

We should document socket_file *after* socket_dir and make it clear that socket_dir is the preferred mechanism to configure sockets.

Thanks!
