### ISSUE TITLE
Using Postgrex.stream with transactions

### ISSUE THREAD

**Issue by thdxr** [elixir-ecto/postgrex#373]
I want to write a function that returns a `Postgrex.stream` that will be consumed by other parts of my application.  However this is difficult with the way the `transaction` API works.  Is there a way to control when the `conn` is released? The only way I can think of is by blocking the transaction callback until the stream is done consuming.  Is there a better way?

I basically want a way to control when I lock and unlock a connection so I can use it in conjunction with `Stream.resource`

**Comment by josevalim** [comment]
Please use ElixirForum or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
