### ISSUE TITLE
Add scram-sha-256 auth method

### ISSUE THREAD

**Issue by seriyps** [elixir-ecto/postgrex#374]
New authorization method was added to PostgreSQL 10.

Details and examples could be found here https://github.com/epgsql/epgsql/pull/156 and here https://github.com/epgsql/epgsql/issues/142

**Comment by seriyps** [comment]
@josevalim sory, I don't know Elixir. I just implemented this auth method for epgsql and started to think that my implementation might be a good reference for postgrex. And to remind postgrex devs about such a feature.

**Comment by josevalim** [comment]
Thanks @seriyps! Your reference implementation will definitely be useful. Let's wait until somebody needs this feature and then they can tackle it. :)

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-xmpp/info/issues/1
