### ISSUE TITLE
Postgrex.CIDR/Postgrex.INET unification is a breaking change

### ISSUE THREAD

**Issue by halostatue** [elixir-ecto/postgrex#383]
The change in a948626 to remove `Postgrex.CIDR` and replace with `Postgrex.INET` is a breaking change for anyone who uses [adam12/ecto_network](https://github.com/adam12/ecto_network). While I have put a PR (adam12/ecto_network#11) in which makes `ecto_network` work with the Postgrex master branch, it is a breaking change for anyone who is using `Postgrex.CIDR` and many extant Postgrex version specifiers (the default version specifier in Phoenix is `{:postgrex, ">= 0.0.0"}`).

I don’t know the Postgrex internals, but I have no reason to believe that an approach similar to the one that I took with EctoNetwork would be inappropriate (keep `Postgrex.CIDR`, but have it essentially alias `Postgrex.INET` via `defdelegate` where possible).

I believe, based on the information that I’m seeing, that this is a *good* change, but I only found it after needing to switch to Postgrex master in order to properly test Ecto master for an issue.

**Comment by halostatue** [comment]
I will also note that there is a further breaking change, because it used to be that `{127, 0, 0, 1}` would be returned as `%Postgrex.INET{address: {127, 0, 0, 1}}` (that is, `%Postgrex.INET{address: {127, 0, 0, 1}, netmask: nil}`), but is now returned as `%Postgrex.INET{address: {127, 0, 0, 1}, netmask: 32}`.

**Comment by fishcakez** [comment]
Please see https://github.com/elixir-ecto/postgrex/issues/292. Postgrex master has other breaking changes compared to the previous release. It is still pre 1.0 unfortunately.

**Comment by halostatue** [comment]
I think you misunderstand what I’m after. I’m not after reverting, because I think that the unification is a good thing for all of the reasons in #292, and I’ve already got a fix that will make it work with EctoNetwork as a PR.

There are two things that I’d like to see changed/fixed about this, both of which I can provide as PRs if you wish:

1. This change should be called out explicitly as something that will break previous use of Postgrex.CIDR or Postgrex.INET. When I looked over the changelog, this did not jump out as a potentially breaking change to me until I experienced it.

2. I’d like to have a bit of encoding/decoding magic to make Postgrex.INET work the way that it did before for plain IP addresses. I honestly don’t think of my local IP address as `127.0.0.1/32` or `::1/128`, but Postgrex simply doesn’t work if you leave `%Postgrex.INET{netmask: nil}` (the tests are getting an undefined savepoint), and this is a fairly easy change to make (IMO), as I’ve already got it in my EctoNetwork PR.

There is a third item, when combined with #2, makes this whole change non-breaking (but still requires an upgrade to EctoNetwork, because the current version makes invalid assumptions about Postgrex.INET). It may or may not be possible to restore Postgrex.CIDR but have it transparently promote to Postgrex.INET, but that would allow things to work more or less as is.

**Comment by fishcakez** [comment]
> (the tests are getting an undefined savepoint)

Can you share this?  We should never get that

**Comment by halostatue** [comment]
@fishcakez Sorry, I misremembered the error. It is `** (Postgrex.Error) ERROR 3B001 (invalid_savepoint_specification) no such savepoint`

I have commented out the pieces of code which I added to ecto_network to always set a `netmask`, but if the netmask is missing, you get the invalid savepoint specification. You can see this in this branch of my fork of ecto_network.

https://github.com/halostatue/ecto_network/tree/example-undefined-savepoint

**Comment by josevalim** [comment]
@fishcakez it probably happens because we have encoding data incorrectly?

**Comment by halostatue** [comment]
@josevalim Absolutely. When the `netmask` is `nil`, I get the savepoint error. When the `netmask` is not nil (and is appropriately 32 or 128), everything works.

**Comment by fishcakez** [comment]
> @fishcakez it probably happens because we have encoding data incorrectly?

Even if that it is the case we should not get the error. Looking at the code briefly I think this issue is showing a much more sinister bug.
