### ISSUE TITLE
Postgrex.Notification connection silently dies

### ISSUE THREAD

**Issue by mmmries** [elixir-ecto/postgrex#386]
I ran into an issue similar to #359 in my production setup (`postgrex 0.13.5`, postgres 9.6). I had a node listening for notifications for 7 days. I noticed that I wasn't seeing updates elsewhere and tracked it back to a `Postgrex.Notification` process that was alive with a state of:

```
iex(spiff-ex@10.12.0.5)6> :sys.get_state(p2)
%Connection{
  backoff: nil,
  mod: Postgrex.Notifications,
  mod_state: %Postgrex.Notifications{
    listener_channels: %{
      "background_tasks" => %{
        #Reference<0.2314467320.2725511169.157557> => #PID<0.477.0>
      }
    },
    listeners: %{
      #Reference<0.2314467320.2725511169.157557> => {"background_tasks",
       #PID<0.477.0>}
    },
    parameters: nil,
    protocol: %Postgrex.Protocol{
      buffer: :active_once,
      connection_id: 19762,
      connection_key: 290296840,
      null: nil,
      parameters: #Reference<0.2314467320.2725511169.157556>,
      peer: {{10, 15, 241, 191}, 5432},
      postgres: :idle,
      queries: nil,
      sock: {:gen_tcp, #Port<0.12742>},
      timeout: 15000,
      transactions: :naive,
      types: nil
    }
  },
  raise: nil
}
```

I tested the process by trying to add an additional listener like this:

```
iex(spiff-ex@10.12.0.5)11> Postgrex.Notifications.listen(p2, "virtual")
** (exit) exited in: :gen_server.call(#PID<0.478.0>, {:listen, "virtual"}, 5000)
    ** (EXIT) %DBConnection.ConnectionError{message: "tcp async_recv: closed"}
    (stdlib) gen_server.erl:214: :gen_server.call/3
```

So it looks like the connection had died, but the `Postgrex.Notification` process had not been notified that the TCP connection was down, until it tried to use it again.

## Proposed Solution

I think it might be a good idea to do some sort of a PING message periodically. This could be managed by the `Postgrex.Notification` directly, or perhaps I could add a method that allows for this to be triggered elsewhere. Maybe a `Postgrex.Notification.check_alive(pid)` function?

I have some time to look into this and provide a PR or find a way of replicating if that is more helpful.

**Comment by josevalim** [comment]
I think we can just ping periodically without user intervention. IIRC, this is already a behaviour in Postgrex.Connection, it is just not enabled for notifications. PR please? :)
