### ISSUE TITLE
Can we support `jsonb_set` in postgrex?

### ISSUE THREAD

**Issue by SkipMike** [elixir-ecto/postgrex#389]
We're doing some work that requires us to do concurrent updates to a jsonb column. Normal updates using postgrex will writes the whole column even if the changes are just one field in the map. If we could find some way to support `jsonb_set` I think the behaviour during conncurrent updates of a jsonb column would be much more intuitive. 

I'm hoping we can start a discussion about this. We have a solution that we are using, but we think this is something that everyone could benefit from.

**Comment by SkipMike** [comment]
Yes, currently we are using `jsonb_set` inside `fragment` to do our updates, and perhaps bringing `jsonb_set` is obscuring my problem.

Here is a smaller scale example of the problem we're trying to solve.

The schema is:
```
schema "items" do
  field :upc, :integer
  embeds_one :coupon,  Coupon do
    field :amount, :integer
    field :description, :string 
  end
end
```
With this schema, if we tried to do

```
t1 = Task.async(fn ->
Items.changeset(
  %Items{id: 1, upc: "1234", coupon: %Coupon{amount: 2, description: "foo"}},
  %{coupon: %{amount: 3}}
)
|> Repo.update()
end)
t2 = Task.async(fn ->
Items.changeset(
  %Items{id: 1, upc: "1234", coupon: %Coupon{amount: 2, description: "foo"}},
  %{coupon: %{description: "bar"}}
)
|> Repo.update()
end)

Task.await(t1)
Task.await(t2)
Repo.get(Items, 1)
```
I don't think we know what we're going to get from this. The coupon description might be "bar" or it might be "foo" and the coupon amount might be 2 or 3. I think the intuitive result would be a description of "bar" and an amount of 3. We've used `jsonb_set`, `fragment`, and `update_all` to get this behaviour but it's cumbersome and difficult. I'm hoping that there is some way that postgrex can change the way it updates jsonb columns so that updating jsonb columns is easier to do in a concurrent setting.

I was proposing `jsonb_set` because that is the postgresql function that I think would help us do this, but I'm not really an expert so there is probably a different better way to do it.

**Comment by josevalim** [comment]
Oh, so this is not a postgrex issue, it is an Ecto issue. I would recommend you to open up a feature request there. I think this can be done but the issue is that it would only work on embeds_one and not  on embeds_many and this may be confusing.

**Comment by esurat20** [comment]
Hello guys. I need to update jsonb if changes are just one field in the map. Do Ecto have same mechanism?
