### ISSUE TITLE
Implement cube type

### ISSUE THREAD

**Issue by ibarchenkov** [elixir-ecto/postgrex#394]
I'd like to use [cube](https://www.postgresql.org/docs/current/static/cube.html) data type that's internally represented as an array of 64-bit floats.
I got stuck with [Postgrex.Extension](https://hexdocs.pm/postgrex/Postgrex.Extension.html) docs and the real [array](https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/extensions/array.ex) implementation.
Could you please help or guide me in a right direction?

**Comment by josevalim** [comment]
@ibarchenkov it is generally preferred if you ask for help in the ElixirForum, as there are more developers there available to help you. Maybe also see previous pull requests for extensions or some packages that implement extensions. Unfortunately we do not have plenty of time to help and, once we do, our focus will be rather on merging and tidying up the existing pull requests and issues.
