### ISSUE TITLE
Extend Postgrex for CockroachDB

### ISSUE THREAD

**Issue by chintan-mishra** [elixir-ecto/postgrex#396]
https://www.cockroachlabs.com/docs/stable/install-client-drivers.html

> CockroachDB supports the PostgreSQL wire protocol, so most available PostgreSQL client drivers should work with CockroachDB.

I noticed that Postgrex supports **PostgreSQL's wire protocol**. Thus, the reason for creating this issue.

With minimal updates, this can be made to work. Although I don't use **CockroachDB**, this would fruther help ease the scaling of modern applications using Ecto and Phoenix.

**And help improve Elixir adoption as well.**

**Comment by josevalim** [comment]
Hi @chintan-mishra, I believe there are some people working on this already, I would recommend investigating. Also, if you are interested on making PostgreSQL work with CockRoachDB, then we recommend you to take a look at it and send the relevant pull requests. It is something we are interesting in supporting, but we can't focus on it right now. Thank you!

**Comment by chintan-mishra** [comment]
Referencing the repo for other interested people https://github.com/jumpn/postgrex

@josevalim  I am currently working on drivers for ArangoDB. PostgreSQL or CockroachDB are not used in our stack. I would be happy to contribute if we use it at any other point in time.
