### ISSUE TITLE
How to close connection correctly?

### ISSUE THREAD

**Issue by kiote** [elixir-ecto/postgrex#413]
Hi, sorry wasn't able to find any info regarding this question. 
So when need to close connection I do simple `Process.exit` but that seem to not close Postgres Connections. Any suggestions on how to do it?

**Comment by josevalim** [comment]
Ideally you will start the connection as part of a supervisor. Then you can use either `Supervisor.terminate_child` or shutdown the supervisor so it shuts your pull down.

If you are starting a connection directly, then sending a `Process.exit(pid, :shutdown)` should terminate it too.

Keep in mind that whenever a connection to postgres is closed abruptly, then you are leaving it up to the Postgres and the OS to figure out whenever that socket will be reclaimed. Eventually postgres will notice the connection is no longer active and do something about that.
