### ISSUE TITLE
Ecto postgrex and unix sockets for Phoenix

### ISSUE THREAD

**Issue by lpvm** [elixir-ecto/postgrex#415]
Did not see any documentation or examples about using a Unix socket to communicate with Postgresql, and also did not get an answer on this in the Elixir forum.
The only thing said in `postgrex`'s documentation is that there's `:sock_dir`.

My question: how to configure ecto and postgrex to use unix sockets instead of TCP?

**Comment by josevalim** [comment]
You can check the docs:

https://hexdocs.pm/postgrex/0.13.5/Postgrex.html#start_link/1

In a nutshell you should set `socket_dir: "path/to/socket/dir"` in your repo configuration. Just make sure to set the proper socket dir (usually "/tmp").

**Comment by lpvm** [comment]
Thank you José, but please pardon my novice in Phoenix (and also Elixir).
The examples at the docs you mentioned show the command that should be used from the iex.
Should I include 
`config :postgrex, socket_dir: "/var/run/postgres"`    (prefer socket there)
in `config/config.exs`?    or some `smart_link` declaration?

Another thing:  the default for Ecto  (not yet using the new ecto_sql) is:

```
config :my_app, Sample.Repo,
adapter: Ecto.Adapters.Postgres,
database: "ecto_simple",
username: "postgres",
password: "postgres",
hostname: "localhost",
port: "5432"
```

Should I change this configuration as well, specially `hostname` and `port`, or is it not necessary?

**Comment by josevalim** [comment]
Good questions! You need to change only the Repo config, i.e.:

    config :my_app, Sample.Repo,
      socket_dir: "/var/run/postgres",
      database: "ecto_simple"

**Comment by cw789** [comment]
Hello @rm116.
I've checked the implementation of `ecto://` database URL.
→ https://github.com/elixir-ecto/ecto/blob/d792962246abb7876e540052ea9da7d25f105f12/lib/ecto/repo/supervisor.ex#L78-L115

It seems Unix domain socket configuration as URL is not supported within Ecto.
So for now it's needed to use `:socket` or `:socket_dir` in the configuration.

**Comment by onnimonni** [comment]
Postgres itself supports giving the socket in `?host` parameter. This is common pattern in NixOS where user gets access to the  postgres socket and doesn't even need a password:
```
$ sudo -u phoenix-web psql "postgresql://phoenix-web@localhost/phoenix-web?host=/run/postgresql/"
psql (16.6)
Type "help" for help.

phoenix-web=> exit
$  sudo -u phoenix-web psql "postgresql://phoenix-web@localhost/phoenix-web"
Password for user phoenix-web:
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "phoenix-web"
```

I was trying to use this url with a service running phoenix and ecto and it doesn't seem to be working outside of the box:
```
DATABASE_URL="postgresql://phoenix-web@localhost/phoenix-web?host=/run/postgresql/"
```

And it fails to `environment variable DATABASE_URL is missing.` even though the env is definitely there:
```
Jan 28 21:35:01 rusty systemd[1]: phoenix-web.service: Failed with result 'exit-code'.
Jan 28 21:35:01 rusty systemd[1]: phoenix-web.service: Main process exited, code=exited, status=1/FAILURE
Jan 28 21:35:01 rusty phoenix-web-start[1923590]: Crash dump is being written to: erl_crash.dump...
Jan 28 21:35:01 rusty phoenix-web-start[1923590]:
Jan 28 21:35:01 rusty phoenix-web-start[1923590]: Runtime terminating during boot ({#{message=><<101,110,118,105,114,111,110,109,101,110,116,32,118,97,114,105,97,98,108,101,32,68,65,84,65,66,65,83,69,95,85,82,76,32,105,115,32,109,105,115,115,105,110,103,46,10,70,111,114,32,101,120,97,109,112,108,101,58,32,101,99,116,111,58,47,47,85,83,69,82,58,80,65,83,83,64,72,79,83,84,47,68,65,84,65,66,65,83,69,10>>,'__struct__'=>'Elixir.RuntimeError','__exception__'=>true},[{elixir_eval,'__FILE__',1,[{file,"/nix/store/sfkljaydf8rj5fiq2si5qigb8xvs44lg-phoenix-web-0.1.0/releases/0.1.0/runtime.exs"},{line,26}]},{elixir,eval_external_handler,3,[{file,"src/elixir.erl"},{line,386},{error_info,#{module=>'Elixir.Exception'}}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,919}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,663}]},{erl_eval,exprs,6,[{file,"erl_eval.erl"},{line,271}]},{elixir,eval_forms,4,[{file,"src/elixir.erl"},{line,364}]},{'Elixir.Module.ParallelChecker',verify,1,[{file,"lib/module/parallel_checker.ex"},{line,120}]},{'Elixir.Code',validated_eval_string,3,
Jan 28 21:35:01 rusty phoenix-web-start[1923590]:     (elixir 1.18.1) lib/code.ex:572: Code.validated_eval_string/3
Jan 28 21:35:01 rusty phoenix-web-start[1923590]:     (elixir 1.18.1) lib/module/parallel_checker.ex:120: Module.ParallelChecker.verify/1
Jan 28 21:35:01 rusty phoenix-web-start[1923590]:     (elixir 1.18.1) src/elixir.erl:364: :elixir.eval_forms/4
Jan 28 21:35:01 rusty phoenix-web-start[1923590]:     (stdlib 6.2) erl_eval.erl:271: :erl_eval.exprs/6
Jan 28 21:35:01 rusty phoenix-web-start[1923590]:     (stdlib 6.2) erl_eval.erl:663: :erl_eval.expr/6
Jan 28 21:35:01 rusty phoenix-web-start[1923590]:     (stdlib 6.2) erl_eval.erl:919: :erl_eval.do_apply/7
Jan 28 21:35:01 rusty phoenix-web-start[1923590]:     (elixir 1.18.1) src/elixir.erl:386: :elixir.eval_external_handler/3
Jan 28 21:35:01 rusty phoenix-web-start[1923590]:     /nix/store/sfkljaydf8rj5fiq2si5qigb8xvs44lg-phoenix-web-0.1.0/releases/0.1.0/runtime.exs:26: (file)
Jan 28 21:35:01 rusty phoenix-web-start[1923590]: For example: ecto://USER:PASS@HOST/DATABASE
Jan 28 21:35:01 rusty phoenix-web-start[1923590]: ** (RuntimeError) environment variable DATABASE_URL is missing.
Jan 28 21:35:01 rusty phoenix-web-start[1923590]: ERROR! Config provider Config.Reader failed with:
```

**Comment by onnimonni** [comment]
It seems that giving socket directly with `DATABASE_URL` doesn't work but it can be done if it's complemented with `PGHOST`. See more in postgrex source: 
https://github.com/elixir-ecto/postgrex/blob/bb8ee9483bd5df6412b10f4942f1aa5d4d9a45bc/lib/postgrex/utils.ex#L88-L105

So if one wants to use socket without modifying the config code they can do this:
```
DATABASE_URL = "postgresql:///DATABASE_NAME_HERE?host=/run/postgresql/";
PGHOST = "/run/postgresql/";
```

I tested this in with default phoenix code as of january 2025 by having same `phoenix-web` user for both database name, database user and unix user for the service.
