### ISSUE TITLE
Many compile warnings when using the JSON or JSONB extensions

### ISSUE THREAD

**Issue by jamesvl** [elixir-ecto/postgrex#424]
## Observed Behavior

I see > 40 repetitions of this compiler warning when using the JSON or JSONB extensions in a mix project:

```
warning: this clause cannot match because a previous clause at line 713 always matches
  deps/postgrex/lib/postgrex/type_module.ex:713
```

The last warning given is slightly different and reads
```
warning: this clause cannot match because a previous clause at line 713 always matches
  lib/postgrex/type_module.ex:713
```

## Environment

From Elixir (and mix) 1.7.3 running on Fedora:
```$elixir --version
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 19)
```
## Steps to reproduce

Start a new, minimal mix project with `mix.new`.

Add these deps to the `mixe.exs` file:
```elixir
  defp deps do
    [
      {:postgrex, "~> 0.14"},
      {:jason, "~> 1.0"},
    ]
  end
```

Add one file, `lib/ecto_extensions.ex` with these contents:
```elixir
Postgrex.Types.define(Tmp.PostgresTypes, [Postgrex.Extensions.JSON])
```

(Also works if doing `JSONB`)

Then do `mix compile`

### Research

Looking at the source here in the repository I see no issues in the file itself. (It hasn't changed in the last 9 months anyways.)

If I copy the json.ex or jsonb.ex file into my mix project and reference it directly as an extension (after changing its module name to match my project), the compiler warnings are not shown.

**Comment by michalmuskala** [comment]
This is because all of the extensions defined in postgrex itself are included already in the type module defined with `Postgrex.Types.define/3`, by adding them explicitly the clauses are defined twice. 

I think we could improve the docs to make it clearer.

**Comment by jamesvl** [comment]
I see now - my config based on the previous docs is no longer needed, and those types are included for me by default.

This can be closed as "not a bug"; I agree it would help if docs were updated to call this out more explicitly for people upgrading.

**Comment by michalmuskala** [comment]
Looking in git history it seems that the json extension was always included by default in the types module and that's why none of the changelogs mention the change. The previous mechanism of the `extensions` options to `start_link` didn't and that's might be where the issue originated.
