### ISSUE TITLE
tstzrange bug: Postgrex expected %DateTime{}

### ISSUE THREAD

**Issue by jgautsch** [elixir-ecto/postgrex#425]
Hello! I believe I may have run into a bug/issue tangentially related to #417, although I'm not 100% sure.

Long story short, I have a custom Ecto type mapping a `{%DateTime{}, %DateTime{}}` to a Postgres `tstzrange`.

This works well with `ecto 2.2.11` and `postgrex 0.13.5`, but upgrading to `ecto_sql 3.0.0` and `postgrex 0.14.0` results in the following error when inserting `{%DateTime{}, %DateTime{}}` tuples into a `tstzrange` column:
```elixir
** (DBConnection.EncodeError) Postgrex expected %DateTime{}, got ~N[2018-11-04 09:00:00]. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
code: time_block = time_block_factory(attrs)
stacktrace:
  (postgrex) lib/postgrex/type_module.ex:713: Postgrex.DefaultTypes.encode_value/2
  (postgrex) lib/postgrex/type_module.ex:713: Postgrex.DefaultTypes.encode_params/3
  (postgrex) lib/postgrex/query.ex:62: DBConnection.Query.Postgrex.Query.encode/3
  (db_connection) lib/db_connection.ex:1074: DBConnection.encode/5
  (db_connection) lib/db_connection.ex:1172: DBConnection.run_prepare_execute/5
  (db_connection) lib/db_connection.ex:1268: DBConnection.run/6
  (db_connection) lib/db_connection.ex:480: DBConnection.parsed_prepare_execute/5
  (db_connection) lib/db_connection.ex:473: DBConnection.prepare_execute/4
  (postgrex) lib/postgrex.ex:167: Postgrex.query/4
  (ecto_sql) lib/ecto/adapters/sql.ex:627: Ecto.Adapters.SQL.struct/10
  (ecto) lib/ecto/repo/schema.ex:603: Ecto.Repo.Schema.apply/4
```

It seems that somewhere inside postgrex, the `DateTime` is being converted to a `NaiveDateTime`, which then doesn't work.

**I've created a repo with test cases to illustrate the issue: [https://github.com/jgautsch/range_bug](https://github.com/jgautsch/range_bug)**

**Comment by josevalim** [comment]
I think the error is in your tztsrange dump function. The Ecto.Type.dump
for utc_datetime returns a naive datetime. It is probably best to not rely
on Ecto here and work with the types directly.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by jgautsch** [comment]
Aha excellent! That solved it, thank you!
