### ISSUE TITLE
Notifications system does not automatically retry connections

### ISSUE THREAD

**Issue by bernardd** [elixir-ecto/postgrex#433]
For "normal" Postgrex connections (those started with `Postgrex.start_link()`), if the database connection drops for whatever reason, the system will continually retry the connection with a capped backoff, just as one might expect/hope.

Notification connections, however, (those started with `Postgrex.Notifications.start_link()`) just terminate the process and require the user to have set up a supervision tree (or some other method) to handle any retries. Digging into it, the reason is that, in `Postgrex.Notifications.handle_info/2`, the `:error` and `:disconnect` responses from `Protocol.handle_info/2` are explicitly mapped to a `{:stop ...}` tuple. Is there a good reason for this or should I put together a PR that makes notification connections retry the same way other connections do?

**Comment by josevalim** [comment]
I am not sure there is a good reason. @ericmj / @fishcakez ?

We could implement backoff too... but I have to ask, what is the issue with putting it under  a supervisor? :)

**Comment by fishcakez** [comment]
Notification is stateful, and state is lost in such a way it can't be recovered on disconnect.

**Comment by josevalim** [comment]
That answers it, thanks @fishcakez !

**Comment by fishcakez** [comment]
A better description is that the notification process has a pointer to a location in the stream of events on the back end and we lose that point on disconnect. If the error isn't to crash we need to send messages.

I think for those looking to guarantee events and sync with data in a table it's not possible to do unless listen first then read table.

Certainly we could support opt in reconnect etc if someone writes it.

**Comment by bernardd** [comment]
Ah, okay, that makes more sense to me, thanks a lot :) If you're happy to have reconnection as an option, I might look into writing it.
