### ISSUE TITLE
Feature request - rollback to save point and retry queries on known safe failures

### ISSUE THREAD

**Issue by seddy** [elixir-ecto/postgrex#434]
I'm raising this as an issue but please do let me know if this is the wrong thing for feature requests and I'll happily raise elsewhere!

We've occasionally seen the following error when running a migration against our production database:

> ERROR 0A000 (feature_not_supported) cached plan must not change result type

This appears to be what happens when some DDL gets run whilst a prepared statement is getting executed. I've not found any explicit description in postgres documentation beyond [this reply on their mailing list](https://www.postgresql.org/message-id/CA%2Bq6zcWX8vu8emD_kZhvNtJ0CS4aVFTbLWpS%3DbiOQLa5A-Dy_w%40mail.gmail.com), but it makes sense and matches up with the other hits I get when googling for this error. If there is official documentation I'm missing then apologies if that's mistaken!

There's a feature that's been implemented in `pgjdbc` which looks like a reasonable approach for dealing with this error where they use savepoints to retry this and `prepared statement XXX does not exist` errors. The documentation for their implementation is [in the `autosave` configuration here](https://jdbc.postgresql.org/documentation/head/connect.html#connection-parameters). See [this stackoverflow answer](https://stackoverflow.com/a/48536394/2240218) and [this PR](https://github.com/pgjdbc/pgjdbc/pull/451) for how they went about handling it.

Is this something we could get into Postgrex? If so, what sort of format/configuration would be sensible? I'm happy to take a look at this at some point if this is thought to be worthwhile.

**Comment by josevalim** [comment]
How do you solve those errors currently? Do you have to reboot or shutdown the system? Or does it come back to a working state naturally?

**Comment by seddy** [comment]
At the moment we're not handling them at all, our app just blows up the request with a `Postgrex.Error` (I think [this](https://github.com/elixir-ecto/postgrex/blob/f93bfd84a22222390f2be9e7245dd868a388991b/lib/postgrex.ex#L167) is where it's returned) and returns a 500. 

To be clear, this isn't a burning pain for us as we don't have anything dealing with particularly high traffic (it's happened only a couple of times in the last 3 months). I was just investigating the issue and it seemed like a potential enhancement :smile: .

**Comment by seddy** [comment]
Actually!! I've just read more around the code I linked to there, would the `:mode` option resolve this? https://github.com/elixir-ecto/postgrex/blob/f93bfd84a22222390f2be9e7245dd868a388991b/lib/postgrex.ex#L342-L343

**Comment by josevalim** [comment]
> At the moment we're not handling them at all, our app just blows up the request with a Postgrex.Error (I think this is where it's returned) and returns a 500.

But does it return it only a handful of times and the fixes itself or do you have to reboot the system?

> Actually!! I've just read more around the code I linked to there, would the :mode option resolve this?

That mode is about SQL sandboxing. It is not what you want. :)

**Comment by seddy** [comment]
Yes, it happens only a handful of times and fixes itself, we don't have to manually reboot the system.

> That mode is about SQL sandboxing. It is not what you want. :)

Gotcha :sweat_smile:

**Comment by fishcakez** [comment]
> That mode is about SQL sandboxing. It is not what you want. :)

That mode is fine to use explicitly, and would create the savepoints you desired for individual queries if inside a transaction. The sandbox behavior is exactly what you want. It may take some work in your repo module to use it though, as you will only want to add it when inside a transaction. If we were to add this feature it would be a third mode.

**Comment by fishcakez** [comment]
> Yes, it happens only a handful of times and fixes itself, we don't have to manually reboot the system.

There is code in postgrex to explicitly handle this case, we close the prepared query on this particularly error. However we aren't doing anything better (without an autosavepoint style feature) because a transaction goes into bad state. However we try to handle this error outside a transaction but inside a checkout for cache statement queries (used for ecto writes). We could do similar for execute (used for ecto reads) though again it would only work inside a checkout.

The most times the error should occur is number of connections * number of affect queries. It is independent of the throughout.

**Comment by fishcakez** [comment]
You can trade some performance to avoid this error by using `prepare: :unnamed` as repo config/start_link option.

**Comment by josevalim** [comment]
Please give it a try using the savepoint mode as mentioned by James and pls let us know how it goes!

**Comment by dylan-chong** [comment]
@seddy @fishcakez So... how did it go?

**Comment by seddy** [comment]
Sorry @dylan-chong - I think I didn't pursue this any further as it was fairly sporadic and we haven't seen it in a long time. I checked the codebase for `prepare: :unnamed` and it looks like we didn't configure this. Trying the `prepare: :unnamed` approach is presumably still valid though, so may be worth trying out.
