### ISSUE TITLE
Postgrex is printing error message when VM is shutting down

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-ecto/postgrex#436]
I've noticed that we are getting Postgrex errors once VM in a Docker container receives sigterm signal. I think it's not desired as it can trigger false alerts on monitoring when the node is shutting down normally. Is there anything we can do about it?

<img width="1137" alt="2019-01-25 22 30 08" src="https://user-images.githubusercontent.com/1877644/51755276-d5a34e00-20f0-11e9-9405-5f0163858803.png">

(Maybe this issue should be moved to DBConnection instead?)

**Comment by josevalim** [comment]
Are you draining your requests and activities before? Because those are likely happening because processes are shutting *while* they are using a connection. So I believe Postgres/DBConnection are correct in logging here. You can also do a trap_exit to ensure they can't suddenly terminate.

**Comment by AndrewDryga** [comment]
Ah, I think you right. Here is related issue in Plug: https://github.com/elixir-plug/plug/issues/732.
