### ISSUE TITLE
Jason being forced over Poison configured

### ISSUE THREAD

**Issue by tpitale** [elixir-ecto/postgrex#438]
I'm going through the upgrade to Ecto 3 and getting a ton of test failures because `* (UndefinedFunctionError) function Jason.encode_to_iodata!/1 is undefined (module Jason is not available)` coming from Postgrex.

I've added `config :postgrex, :json_library, Poison` to my config.exs file. I've run `mix deps.clean --all` and recompiled deps. I've cleaned and recompiled my code numerous times and I can't seem to get it to pick up the configuration to use Poison.

Is there a different place I should be adding this configuration? Or perhaps, is there something else I'm doing wrong? It seems slim, but possible that this is a bug, and very few people are using Poison …?

**Comment by josevalim** [comment]
So I cannot reproduce this on Postgrex. I created a new project, added postgrex as a dependency, configured it to use Poison:

```elixir
Interactive Elixir (1.9.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> {:ok, pid} = Postgrex.start_link [database: "postgres"]
{:ok, #PID<0.751.0>}
iex(2)> Postgrex.query pid, "SELECT '{}'::jsonb", []
** (UndefinedFunctionError) function Poison.decode!/1 is undefined (module Poison is not available)
    Poison.decode!("{}")
    (postgrex) lib/postgrex/type_module.ex:713: Postgrex.DefaultTypes."Elixir.Postgrex.Extensions.JSONB"/6
    (postgrex) lib/postgrex/protocol.ex:2733: Postgrex.Protocol.rows_recv/4
    (postgrex) lib/postgrex/protocol.ex:1777: Postgrex.Protocol.recv_execute/5
    (postgrex) lib/postgrex/protocol.ex:1615: Postgrex.Protocol.bind_execute_close/4
    (db_connection) lib/db_connection/holder.ex:270: DBConnection.Holder.holder_apply/4
    (db_connection) lib/db_connection.ex:1195: DBConnection.run_execute/5
    (db_connection) lib/db_connection.ex:1282: DBConnection.run/6
iex(2)> Postgrex.query pid, "SELECT $1::jsonb", [%{}]
** (UndefinedFunctionError) function Poison.encode_to_iodata!/1 is undefined (module Poison is not available)
    Poison.encode_to_iodata!(%{})
```

You can see it is trying to use Poison. So can you please provide a way to reproduce the issue you are having?

**Comment by tpitale** [comment]
On a clean project, I can reproduce until I cleans and recompile deps. Then it works as you shared. Can't reproduce in the same way as my project, so closing.

**Comment by tpitale** [comment]
@josevalim _Should_ this require recompiling `deps` after changing `config.exs`?

**Comment by tpitale** [comment]
E.g., If my `deps` are compiled before my `app` is compiled (as in docker or something) … the deps have to be recompiled because the config.exs wasn't picked up?

**Comment by tpitale** [comment]
Or maybe `config.exs` just has to be present with the configuration when the `deps` are compiled.

**Comment by tpitale** [comment]
Confirmed, it was a docker build order issue.

**Comment by josevalim** [comment]
Yes, it does need to recompile. I thought we mentioned this in the README, but apparently we don't. I  will push a fix.
