### ISSUE TITLE
Handling XML as a string?

### ISSUE THREAD

**Issue by cigrainger** [elixir-ecto/postgrex#439]
Is there a way to just get the binary data for XML from postgres (that is, treating the XML as a string/text)? I'm currently getting the following error:

```
** (Postgrex.QueryError) type `xml` can not be handled by the types module Postgrex.DefaultTypes
    (ecto_sql) lib/ecto/adapters/sql.ex:620: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:553: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
```

I assume this would be relatively simple with the Postgrex.Extension behaviour, but I honestly don't know where to start in terms of indicating that it should just return the binary.

**Comment by josevalim** [comment]
You do need a custom Postgrex.Extension. I assume returning a binary is a matter of extracting the field on decode and that's it? Anyway, I recommend you to give it a try, it is the only way to know for  sure. :D

**Comment by cigrainger** [comment]
Thanks @josevalim! That worked. I'm leaving this here for posterity. I basically just copied the ltree implementation and it worked! If I'm honest, I don't grok some of the quote stuff yet or matching on the encoded binaries, so I'm not sure if this is *right*, but it works.

```
defmodule Dataloader.PostgrexXML do
  @behaviour Postgrex.Extension

  def init(opts) do
    Keyword.get(opts, :decode_copy, :copy)
  end

  def matching(_state), do: [type: "xml"]

  def format(_state), do: :text

  def encode(_state) do
    quote do
      bin when is_binary(bin) ->
        [<<byte_size(bin)::signed-size(32)>> | bin]
    end
  end

  def decode(:reference) do
    quote do
      <<len::signed-size(32), bin::binary-size(len)>> ->
        bin
    end
  end

  def decode(:copy) do
    quote do
      <<len::signed-size(32), bin::binary-size(len)>> ->
        :binary.copy(bin)
    end
  end
end
```

Then added a postgrex_types file:
```
Postgrex.Types.define(
  Dataloader.PostgrexTypes,
  [Dataloader.PostgrexXML] ++ Ecto.Adapters.Postgres.extensions()
)
```

And for use with Ecto, added an Ecto type that uses the postgrex extension:
```
defmodule Dataloader.EctoXML do
  @behaviour Ecto.Type
  def type, do: Dataloader.PostgrexXML

  def cast(value), do: {:ok, value}

  def load(data) do
    {:ok, data}
  end

  def dump(value), do: {:ok, value}
end
```

**Comment by josevalim** [comment]
Awesome @cigrainger! for the ecto type, you may be able to use it as a string and you may not need a custom type, but I am not sure. :)

**Comment by cigrainger** [comment]
Thanks @josevalim -- you're right! The ecto type is unnecessary, just checked it.
