### ISSUE TITLE
DB types that are semantically arbitrary-precision integers should map to native arbitrary-precision integers

### ISSUE THREAD

**Issue by tsutsu** [elixir-ecto/postgrex#448]
Currently there is no PG type usable through Postgrex that both can _hold_ arbitrary-precision integers, and which _decodes to_ Erlang's own native arbitrary-precision integers. This seems flawed, especially in the context of fixed-point monetary calculations, which make frequent use of arbitrary-precision integers and don't want any fractional information leaking into the results. (In fact, they want to assert that all results have no fractional part.)

Now, it does make sense that the PG type called `DECIMAL` should map to an arbitrary-precision decimal ADT (`%Decimal{}`), regardless of the parameterization of the `DECIMAL`. It's called `DECIMAL`; doing anything else would violate POLS.

On the other hand, I would argue that `NUMERIC`—especially with a `scale` of 0 (e.g. `NUMERIC(1000, 0)` or `NUMERIC(1000)`, but maybe plain `NUMERIC` as well, since there are practical reasons† to choose it over the alternatives) should map to plain Erlang integers, and vice versa. The `NUMERIC` types do not claim to be decimal numbers (although they happen to share an implementation with `DECIMAL`), but rather to just be able to represent "arbitrary numeric information"; and their parameterization _can_ make explicit that there is no decimal part to this information. So—in the cases where such parameterization is used—the resulting type **is** an arbitrary-precision integer, no?

† `NUMERIC` by itself allows "up to 131072 digits before the decimal point" but `NUMERIC(n)` only allows `n` ≤ 1000. True arbitrary-precision integers, then, are best represented in PG by an un-parameterized `NUMERIC` column, plus a check constraint on that column of `scale(col) = 0`.

**Comment by tsutsu** [comment]
As an aside, I'm working around my need for a field that represents an arbitrary-precision integer on a higher layer, using this (silly) `Ecto.Type`:

```elixir
defmodule MyProject.Ecto.Bignum do
  @behaviour Ecto.Type

  def type, do: :numeric

  def cast(bin) when is_binary(bin) do
    case Integer.parse(bin) do
      {n, ""} -> {:ok, n}
      :error -> :error
    end
  end
  def cast(n) when is_integer(n) do
    {:ok, n}
  end
  def cast(%Decimal{} = d) do
    {:ok, Decimal.to_integer(d)}
  rescue
    FunctionClauseError -> :error
  end
  def cast(_), do: :error

  def load(%Decimal{} = d) do
    {:ok, Decimal.to_integer(d)}
  end

  def dump(n) when is_integer(n), do: {:ok, Decimal.new(n)}
  def dump(_), do: :error
end
```

**Comment by tsutsu** [comment]
As an alternative, if modifying the semantics of `NUMERIC`'s decoding in this way is untenable (even as a configuration option):

Perhaps, allow Postgrex to be configured with the name of a PG `TYPE` (required to be defined as a custom base type with all its functions mapped to the equivalent functions from `NUMERIC`) which it would then consider to be "the native arbitrary-precision integer type" to decode to native Erlang integers.

Sadly, there is no standard SQL name for such a type (other than "`NUMERIC` with a `scale` of 0", I mean), or I would just suggest detecting the existence of the type by its standard name(s), without any configuration. (If y'all wanted to pretend, though, we could slap up a page about "the `ARBINT` SQL type unofficial extensional standard" or somesuch, with a bit of DDL you can paste into your DB console to create the type, and then just add an extension to detect our `ARBINT` if it's there.)

**Comment by josevalim** [comment]
Hi  @tsutsu, the adapter [does receive the scale](https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/extensions/numeric.ex), so if you want, you can implement your own Postgrex extension that returns an integer for a scale of 0. If you use a custom type, you can implement your own Postsgrex extension too. However, for simplicity, we will support only numeric -> decimal in Postgrex itself. All of the extension mechanisms are in place though. :+1:

**Comment by tsutsu** [comment]
Thanks for the pointer! I hadn't seen a third-party Postgrex extension in the wild before and wasn't aware that Postgrex extensions were "exposed" for addition by downstream libraries. Browsing Hex, I see a good example of how to do this in the [geo_postgis](https://hex.pm/packages/geo_postgis) library. I can handle the rest from here, then! :smile:
