### ISSUE TITLE
Use :erlang.md5/1 instead of :crypto.hash/2

### ISSUE THREAD

**Issue by burmajam** [elixir-ecto/postgrex#449]
Hi, we are using erlang and host OS in FIPS mode, talking to PG on aws. Problem we are facing with is that PG on aws requests authentication encrypted with md5 using given salt, and that can't be changed. That procedure is FIPS 140-2 compliant since communication is TLS encrypted. Problem is that in `Postgrex.Protocol.auth_md5/4` :crypto.hash(:md5, iodata) is used and openssl in fips mode refuses to do md5 encryption:

```
[error] GenServer #PID<0.269.0> terminating
** (RuntimeError) Connect raised a ErlangError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

    (crypto) crypto.erl:949: :crypto.notsup_to_error/1
    (postgrex) lib/postgrex/protocol.ex:612: Postgrex.Protocol.auth_md5/4
    (postgrex) lib/postgrex/protocol.ex:504: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
```

Erlang docs for FIPS mode state that "For exceptional, non-cryptographic use cases one may consider switching to erlang:md5/1 as well." and indeed it works as expected. Can you consider this change?

Thanks

**Comment by josevalim** [comment]
@burmajam yes, definitely. Please send a PR.

/cc @wojtekmach you may want to mirror this in MyXQL if applicable.
