### ISSUE TITLE
Supported PostgreSQL Versions

### ISSUE THREAD

**Issue by schmidh** [elixir-ecto/postgrex#452]
The README states that PostgreSQL versions 8.4, 9.0-9.6, and 10.0 are supported. I assume that Postgrex uses wire protocol 3.0 which supports all PostgreSQL versions beginning from 7.4 including 11.x. (See also https://www.postgresql.org/docs/current/protocol.html). If someone could offer some clarification I would be very grateful.

Thanks!

**Comment by josevalim** [comment]
We do use the protocol 3.0 but it is not as simple as saying if we support protocol 3.0 then we support all of the versions using protocol 3.0. For example, newer versions may introduce new authentications under the protocol.

We also do a bootstrap on query to figure out the types, which makes it hard to support earlier versions than 8.4 and so on.

So protocol 3.0 is a requirement but it is not sufficient.

**Comment by schmidh** [comment]
Ok. Thanks!
