### ISSUE TITLE
Feature Request - Allow MapSet to be encoded as ararys

### ISSUE THREAD

**Issue by karlseguin** [elixir-ecto/postgrex#453]
currently running our own type for arrays with the added clause:

```
%MapSet{} = set, [oid], [type] ->
  encoder = &encode_list(&1, type)
  unquote(__MODULE__).encode(MapSet.to_list(set), oid, encoder)
```

Though more generally, would be nice for anything that implements `Enumerable` to be usable.

**Comment by josevalim** [comment]
Because they won't be encoded back in their original shape, we prefer to explicitly support only lists. You can use your own extensions (or Ecto Custom Types if you are using Ecto) to customize the behaviour though. Thanks!
