### ISSUE TITLE
Genserver terminating upon start while deploying docker image

### ISSUE THREAD

**Issue by radhikapatil25** [elixir-ecto/postgrex#455]
Hello
I have a running Phoenix app connected to a Postgresql db, which is running fine locally. But  when i am trying to deploy a docker image of it I am getting errors.

[container.log](https://github.com/elixir-ecto/postgrex/files/3071739/container.log)
Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:5] [hipe]
05:11:20.438 [error] GenServer #PID<0.2576.0> terminating
** (ArgumentError) argument error
(kernel) gen_tcp.erl:167: :gen_tcp.connect/4
(postgrex) lib/postgrex/protocol.ex:473: Postgrex.Protocol.connect/5
(postgrex) lib/postgrex/protocol.ex:103: Postgrex.Protocol.connect/1
(db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
(connection) lib/connection.ex:622: Connection.enter_connect/5
(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
05:11:20.438 [error] GenServer #PID<0.2575.0> terminating
** (ArgumentError) argument error
(kernel) gen_tcp.erl:167: :gen_tcp.connect/4
(postgrex) lib/postgrex/protocol.ex:473: Postgrex.Protocol.connect/5
(postgrex) lib/postgrex/protocol.ex:103: Postgrex.Protocol.connect/1
(db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
(connection) lib/connection.ex:622: Connection.enter_connect/5
(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
[container.log](https://github.com/elixir-ecto/postgrex/files/3071743/container.log)
also i have attached the log file.

Thank you.

**Comment by josevalim** [comment]
This is a bug in Postgrex. I will release a fix soon and ping back here.

**Comment by radhikapatil25** [comment]
> This is a bug in Postgrex. I will release a fix soon and ping back here.

okay thank you

**Comment by josevalim** [comment]
`mix deps.update postgrex` should fix it, as v0.14.2 is out with a fix.

**Comment by radhikapatil25** [comment]
The issue isn't solved, getting same error @josevalim

**Comment by zemuldo** [comment]
I was using RDS and I ended up with having a pace at the end of my RDS URL. It's weird how the error was reported though. Removing the space solved the issue.

**Comment by Khunpisit** [comment]
Hi there, Can we reopen this issue ?

**Comment by aleklisi** [comment]
I have the same issue with `:postgrex, "0.15.5"`
```
running migration
create Cert.Repo database if it doesn't exist
06:56:12.244 [error] GenServer #PID<0.205.0> terminating
** (ArgumentError) argument error
    (kernel 6.5.2.1) gen_tcp.erl:167: :gen_tcp.connect/4
    (postgrex 0.15.5) lib/postgrex/protocol.ex:546: Postgrex.Protocol.connect/5
    (postgrex 0.15.5) lib/postgrex/protocol.ex:105: Postgrex.Protocol.connect/1
    (db_connection 2.2.2) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
database creation error : "killed"
06:56:12.267 [error] GenServer #PID<0.209.0> terminating
** (ArgumentError) argument error
    (kernel 6.5.2.1) gen_tcp.erl:167: :gen_tcp.connect/4
    (postgrex 0.15.5) lib/postgrex/protocol.ex:546: Postgrex.Protocol.connect/5
    (postgrex 0.15.5) lib/postgrex/protocol.ex:105: Postgrex.Protocol.connect/1
    (db_connection 2.2.2) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
06:56:12.267 [error] GenServer #PID<0.210.0> terminating
** (ArgumentError) argument error
    (kernel 6.5.2.1) gen_tcp.erl:167: :gen_tcp.connect/4
    (postgrex 0.15.5) lib/postgrex/protocol.ex:546: Postgrex.Protocol.connect/5
    (postgrex 0.15.5) lib/postgrex/protocol.ex:105: Postgrex.Protocol.connect/1
    (db_connection 2.2.2) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
06:56:12.268 [error] GenServer #PID<0.211.0> terminating
** (ArgumentError) argument error
    (kernel 6.5.2.1) gen_tcp.erl:167: :gen_tcp.connect/4
    (postgrex 0.15.5) lib/postgrex/protocol.ex:546: Postgrex.Protocol.connect/5
    (postgrex 0.15.5) lib/postgrex/protocol.ex:105: Postgrex.Protocol.connect/1
    (db_connection 2.2.2) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
06:56:12.268 [error] GenServer #PID<0.212.0> terminating
** (ArgumentError) argument error
    (kernel 6.5.2.1) gen_tcp.erl:167: :gen_tcp.connect/4
    (postgrex 0.15.5) lib/postgrex/protocol.ex:546: Postgrex.Protocol.connect/5
    (postgrex 0.15.5) lib/postgrex/protocol.ex:105: Postgrex.Protocol.connect/1
    (db_connection 2.2.2) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
06:56:12.269 [error] GenServer #PID<0.213.0> terminating
** (ArgumentError) argument error
    (kernel 6.5.2.1) gen_tcp.erl:167: :gen_tcp.connect/4
    (postgrex 0.15.5) lib/postgrex/protocol.ex:546: Postgrex.Protocol.connect/5
    (postgrex 0.15.5) lib/postgrex/protocol.ex:105: Postgrex.Protocol.connect/1
    (db_connection 2.2.2) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
** (EXIT from #PID<0.164.0>) shutdown
```

**Comment by bryanhuntesl** [comment]
> I have the same issue with `:postgrex, "0.15.5"`
> 
> ```
> running migration
> create Cert.Repo database if it doesn't exist
> 06:56:12.244 [error] GenServer #PID<0.205.0> terminating
> ** (ArgumentError) argument error
>     (kernel 6.5.2.1) gen_tcp.erl:167: :gen_tcp.connect/4
>     (postgrex 0.15.5) lib/postgrex/protocol.ex:546: Postgrex.Protocol.connect/5
>     (postgrex 0.15.5) lib/postgrex/protocol.ex:105: Postgrex.Protocol.connect/1
>     (db_connection 2.2.2) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
>     (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
>     (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
> Last message: nil
> database creation error : "killed"
> 06:56:12.267 [error] GenServer #PID<0.209.0> terminating
> ** (ArgumentError) argument error
>     (kernel 6.5.2.1) gen_tcp.erl:167: :gen_tcp.connect/4
>     (postgrex 0.15.5) lib/postgrex/protocol.ex:546: Postgrex.Protocol.connect/5
>     (postgrex 0.15.5) lib/postgrex/protocol.ex:105: Postgrex.Protocol.connect/1
>     (db_connection 2.2.2) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
>     (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
>     (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
> Last message: nil
> 06:56:12.267 [error] GenServer #PID<0.210.0> terminating
> ** (ArgumentError) argument error
>     (kernel 6.5.2.1) gen_tcp.erl:167: :gen_tcp.connect/4
>     (postgrex 0.15.5) lib/postgrex/protocol.ex:546: Postgrex.Protocol.connect/5
>     (postgrex 0.15.5) lib/postgrex/protocol.ex:105: Postgrex.Protocol.connect/1
>     (db_connection 2.2.2) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
>     (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
>     (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
> Last message: nil
> 06:56:12.268 [error] GenServer #PID<0.211.0> terminating
> ** (ArgumentError) argument error
>     (kernel 6.5.2.1) gen_tcp.erl:167: :gen_tcp.connect/4
>     (postgrex 0.15.5) lib/postgrex/protocol.ex:546: Postgrex.Protocol.connect/5
>     (postgrex 0.15.5) lib/postgrex/protocol.ex:105: Postgrex.Protocol.connect/1
>     (db_connection 2.2.2) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
>     (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
>     (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
> Last message: nil
> 06:56:12.268 [error] GenServer #PID<0.212.0> terminating
> ** (ArgumentError) argument error
>     (kernel 6.5.2.1) gen_tcp.erl:167: :gen_tcp.connect/4
>     (postgrex 0.15.5) lib/postgrex/protocol.ex:546: Postgrex.Protocol.connect/5
>     (postgrex 0.15.5) lib/postgrex/protocol.ex:105: Postgrex.Protocol.connect/1
>     (db_connection 2.2.2) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
>     (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
>     (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
> Last message: nil
> 06:56:12.269 [error] GenServer #PID<0.213.0> terminating
> ** (ArgumentError) argument error
>     (kernel 6.5.2.1) gen_tcp.erl:167: :gen_tcp.connect/4
>     (postgrex 0.15.5) lib/postgrex/protocol.ex:546: Postgrex.Protocol.connect/5
>     (postgrex 0.15.5) lib/postgrex/protocol.ex:105: Postgrex.Protocol.connect/1
>     (db_connection 2.2.2) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
>     (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
>     (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
> Last message: nil
> ** (EXIT from #PID<0.164.0>) shutdown
> ```
> 
> @josevalim I got the same issue on Kubernetes 🤔

Ignore this report - @aleklisi works with me - it was because of missing connection variables - we need to fail faster in the presence of empty environment variables.
