### ISSUE TITLE
bigint has limit

### ISSUE THREAD

**Issue by xxhenglyxx** [elixir-ecto/postgrex#456]
The erorr when inserting into the database:

    "Postgrex expected an integer in -9223372036854775808..9223372036854775807, got
    1xxxxxxxxxxxxxxxxxxxxx1. Please make sure the value you are passing matches the
    definition in your table or in your query or convert the value accordingly."

The migration:

    ...
    alter table(:users) do
      add_if_not_exists :gauth_id, :bigint, null: false
    end
    ...

The gauth id is the google user id. I use google sign in on the client side and get the gauth id from `id_token` and save it to database if user not yet register/sign-up before on my app.

**Comment by josevalim** [comment]
This limit is imposed by Postgres, there is nothing we can do about it. You likely want to set your id to be a string.
