### ISSUE TITLE
Introductory documentation

### ISSUE THREAD

**Issue by ChuckIrvine** [elixir-ecto/postgrex#457]
It would be very useful to have more introductory documentation for Postgrex. For me, an ideal use case would be how to access a Postgrex based connection pool across a set of Plug.Router based modules. Thanks

**Comment by josevalim** [comment]
Agreed, PRs from anyone interested on this are welcome.

**Comment by ChuckIrvine** [comment]
FYI - Rather than using the Postgrex driver directly to execute raw SQL, I'm using Ecto.Adapters.SQL.query(). In that context everything is well documented. So, I'll close this issue unless anyone thinks I shouldn't.

**Comment by josevalim** [comment]
Sounds good!
