### ISSUE TITLE
Unable to use beta version of postgres

### ISSUE THREAD

**Issue by ankhers** [elixir-ecto/postgrex#464]
This issue stems from this [SO](https://stackoverflow.com/questions/56543947/can-connect-to-postgres-container-through-shell-but-not-through-phoenix-app) question (not mine). It seems that the current beta version of postgres reports it's version as `12beta1`. The `Postgrex.Utils.parse_version/1` function crashes with this version.

**Comment by josevalim** [comment]
Thanks! In case anyone wants to submit a PR, it would be welcome!
