### ISSUE TITLE
Is there a way to disable prepared statements? 

### ISSUE THREAD

**Issue by gaynetdinov** [elixir-ecto/postgrex#468]
Hi,

I'd like to disable prepared statements completely. This is needed to switch `pgbouncer` into `transaction` mode. To my understanding when prepared statements are off, the raw SQL I see in the console should not have any placeholders like `$1`, `$2`, etc. 

For example when I switch off prepared statements in activerecord in the config `prepared_statements: false`, I can see that instead of
```sql
select * from table where field = $1 [["field", 1]]
```
the generated SQL is the following
```sql
select * from table where field = 1
```

However with Ecto + Postgrex I still cannot find the way how to disable prepared statements. The tip from the README does not really do anything regarding placeholders. I put the following into config
```
config :my_project, MyRepo,
  adapter: Ecto.Adapters.Postgres,
  # ...
  prepare: :unnamed
```
but I still see raw SQL like this

```sql
SELECT m0."id", m0."field" FROM "table" AS m0 WHERE (m0."field" = $1) ["value"]
```

Is there a way to force Postgrex adapter to not use prepared statements at all? 

Thanks.

**Comment by josevalim** [comment]
Those are separated things. One is a parameterized queries the other is prepared statements. AFAIK, parameterized queries are supported fine by pgbouncer. Prepared statements are not, hence the unnamed option.

It is not possible to disable parameterized queries in Ecto and we don't plan to, as they are important for efficiency and to avoid SQL injection attacks. You can write them by hand in Postgrex though.

**Comment by ngocketit** [comment]
@gaynetdinov Have you found the way yet? I have a similar issue and not sure if `prepare: :unnamed` would work. When connecting via PgBouncer with transaction pooling mode, there are a bunch of errors like this: `ERROR:  prepared statement "ecto_xxx" does not exist`

**Comment by greg-rychlewski** [comment]
Hi @ngocketit ,

That should work. Where did you put `prepare: :unnamed`?

**Comment by mathieurousseau** [comment]
@greg-rychlewski you need to put in your `config.exs`

I just found out that putting it in `runtime.exs` does not work 😬

**Comment by paveltyk** [comment]
AFAIK Postgres query planner can't use partial-indexes with parameterized statements ([docs](https://www.postgresql.org/docs/current/indexes-partial.html#INDEXES-PARTIAL-EX2)):

> Matching takes place at query planning time, not at run time. As a result, parameterized query clauses do not work with a partial index.

Is there any workaround?
