### ISSUE TITLE
Sanity check new bootstrap query on Cockroach DB

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/postgrex#470]
Hi @tlvenn!

We have merged a new and more efficient bootstrap query but we are not sure if it runs on Cockroach DB though. Can you please give master a try and let us know what you find?

If it is all good, we will release v0.15.0.

Thank you!

**Comment by tlvenn** [comment]
Sure thing @josevalim !

**Comment by tlvenn** [comment]
All good on my side, everything works just fine.

**Comment by josevalim** [comment]
Thanks!
