### ISSUE TITLE
Type.Server errors on newest versions.

### ISSUE THREAD

**Issue by mnussbaumer** [elixir-ecto/postgrex#474]
So up to 0.14.1 this doesn't happen. If my experiments are correct it  happens from 0.14.3 upwards. 

[elixir forum post](https://elixirforum.com/t/postgrex-types-error-working-fine-previously/24167/4)

Basically, I started having an error pop up on postgrex connecting to an external db. It always happens, but *looks* random in terms of which connection triggers it (and it triggers more than 1 time). 
The issue is, the db is external and I have no copy of it nor way to poke around locally. The error that happens is this:

```
Jul 25 15:32:55 *** ***[25397]: 15:32:55.161 [error] GenServer {Postgrex.TypeManager, {DBExt.PostgresTypes, {'url', 6432, "dbname"}}} terminating
Jul 25 15:32:55 *** ***[25397]: ** (MatchError) no match of right hand side value: false
Jul 25 15:32:55 *** ***[25397]:     (postgrex) lib/postgrex/types.ex:128: anonymous fn/3 in Postgrex.Types.associate_type_infos/2
Jul 25 15:32:55 *** ***[25397]:     (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
Jul 25 15:32:55 *** ***[25397]:     (postgrex) lib/postgrex/types.ex:127: Postgrex.Types.associate_type_infos/2
Jul 25 15:32:55 *** ***[25397]:     (postgrex) lib/postgrex/type_server.ex:122: Postgrex.TypeServer.associate/2
Jul 25 15:32:55 *** ***[25397]:     (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
Jul 25 15:32:55 *** ***[25397]:     (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
Jul 25 15:32:55 *** ***[25397]:     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Jul 25 15:32:55 *** ***[25397]: Last message (from #PID<0.7212.0>): {:update, #Reference<0.1539663786.2454716417.235103>, [%Postgrex.TypeInfo{array_elem: 0, base_type: 0, comp_elems: [1043], input: "record_in", oid: 2922406102, output: "record_out", receive: "record_recv", send: "record_send", type: "in_property_rooms_hashdiff"}, %Postgrex.TypeInfo{array_elem: 2922406102, base_type: 0, comp_elems: [], input: "array_in", oid: 2922406101, output: "array_out", receive: "array_recv", send: "array_send", type: "_in_property_rooms_hashdiff"}, %Postgrex.TypeInfo{array_elem: 0, base_type: 0, comp_elems: [1043], input: "record_in", oid: 3288525060, output: "record_out", receive: "record_recv", send: "record_send", type: "ky_property_rooms_hashdiff"}, %Postgrex.TypeInfo{array_elem: 3288525060, base_type: 0, comp_elems: [], input: "array_in", oid: 3288525059, output: "array_out", receive: "array_recv", send: "array_send", type: "_ky_property_rooms_hashdiff"}, %Postgrex.TypeInfo{array_elem: 0, base_type: 0, comp_elems: [23, 1043, 1043, 23, 23, 23, 23, 23, 23, 23, 1114, 1114, 1114, 1114, 1042, 1043], input: "record_in", oid: 4127806000, output: "record_out", receive: "record_recv", send: "record_send", type: "data_prov_history_backup"}, %Postgrex.TypeInfo{array_elem: 4127806000, ....... many more
```

If it helps, there's several connections being opened for this same server, they do some work, then get closed. About 8 run in parallel at all times, as each one is closed another opens, and they run for a couple minutes 2/3min. 

I'm imagining it has something to do with re-using the types, I found some commits doing some work on the Type server and I imagine this is related to it.

**Comment by josevalim** [comment]
@mnussbaumer can you please confirm that they happen on v0.14.3? That's very important to help us trim down the bug source. Thanks!

**Comment by josevalim** [comment]
Also please let me know which version you were using for the stacktrace above.

**Comment by mnussbaumer** [comment]
@josevalim will then do later today some fresh deployments pinning down the versions until it errors out and report back!

**Comment by mnussbaumer** [comment]
@josevalim so, weird. This happens exactly on 0.14.3 and doesn't seem to happen in 0.15.0? Not sure how this came to be as I'm almost positive I had updated the dependencies to 0.15 as well before when  I first saw the error and it still erred. Perhaps I didn't deps.update? But that should have given me an error when building. Anyway, thanks. If it appears again I'll re-open.
