### ISSUE TITLE
Postgrex.Interval support for microseconds

### ISSUE THREAD

**Issue by terianil** [elixir-ecto/postgrex#475]
Currently decoding of `Postgrex.Interval` cuts off microseconds. Postgres delivers interval accurate to microseconds, but `Postgrex.Interval` struct contains only `months`, `days` and `secs`.

I suggest:
- adding `microsecs` to `Postgrex.Interval` struct
- extending `Postgrex.Extensions.Interval` encode/decode functions to support microsecs

**Comment by josevalim** [comment]
Yes, please do send a PR!

**Comment by terianil** [comment]
As you wish :)
