### ISSUE TITLE
uses unknown oid(s) xxxx causing bootstrap

### ISSUE THREAD

**Issue by paridin** [elixir-ecto/postgrex#477]
Recently update my dependencies and Postgrex was updated to the latest version 0.15.0 then this kind of warnings appears. I'm not sure if this is related to the `Money.Ecto.Composite.Type` because of others schemas using the same type of field had a similar issue. 

```
[warn] %Postgrex.Query{cache: :statement, columns: nil, name: "ecto_insert_packages", param_formats: nil, param_oids: nil, param_types: nil, ref: nil, result_formats: nil, result_oids: nil, result_types: nil, statement: "INSERT INTO \"packages\" (\"description\",\"is_active\",\"name\",\"plan_id\",\"price\",\"inserted_at\",\"updated_at\") VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING \"id\"", types: nil} 
uses unknown oid(s) 75512 causing bootstrap.
[warn] %Postgrex.Query{cache: :reference, columns: nil, name: "ecto_110722", param_formats: nil, param_oids: nil, param_types: nil, ref: nil, result_formats: nil, result_oids: nil, result_types: nil, statement: "SELECT m0.\"id\", m0.\"name\", m0.\"description\", m0.\"price\", m0.\"inserted_at\", m0.\"updated_at\" FROM \"x_packages\" AS m0 ORDER BY m0.\"inserted_at\" LIMIT $2 OFFSET $3", types: nil} 
uses unknown oid(s) 19714 causing bootstrap
```

The price is a composite field.

```
schema "packages" do
    field(:name, :string)
    field(:description, :string)
    field(:price, Money.Ecto.Composite.Type)
    field(:is_active, :boolean, default: true)
    belongs_to(:plan, Plan)
    timestamps(type: :utc_datetime)
end
```

looking for references to `unknown oid(s)` message. I found [this](https://github.com/elixir-ecto/postgrex/commit/fd94dd8c63052de4e64fae7dbb7048ccdbec4b48).

I tried 0.14.3 version, and it works with no warnings.

**Comment by fishcakez** [comment]
We can likely reduce the level, it's okay for this bootstrap to happen. If it occurs alot though it's a problem.

**Comment by paridin** [comment]
I observed it happens during the first execution of the query on the table x_package, also during the performance of the tests.

The behavior confuses me; The warning sometimes occurs five times (number of test inserting into package table) others just one.

And the weird part of this, it only happens during the tests which work with "packages" table.

I found the function where the message comes from, but I'm not sure how can I fixed since it is reloading because of the oid. Right? 

There is an oid catalog? 

I would like to understand how it works.

**Comment by grekko** [comment]
In a Phoenix project we are trying to switch from building up the DB structure from migrations in our tests to loading the `structure.sql` generated by `pg_dump`.

When we do so we observe several such warnings when running the test suite:

```sh
[warn] %Postgrex.Query{cache: :statement, columns: nil, name: "ecto_insert_users", param_formats: nil, param_oids: nil, param_types: nil, ref: nil, result_formats: nil, result_oids: nil, result_types: nil, statement: "INSERT INTO \"users\" (**ommitted**)", types: nil} uses unknown oid(s) 16386 causing bootstrap
```

I'd also like to better understand if this is an issue one can address or if this is unavoidable for some reason :)

**Comment by josevalim** [comment]
@grekko that's expected because pg_dump is loaded a bunch of extensions into the database which we learn about while running the suite. Perhaps you want to restart your repository though (see the Ecto.Migrator.with_repo helper). I will move the level back to debug. Thank you.

**Comment by josevalim** [comment]
v0.15.1 pushed!
