### ISSUE TITLE
Precision option on :float

### ISSUE THREAD

**Issue by jamilabreu** [elixir-ecto/postgrex#480]
In migration:

`add :rank, :float, default: 0.0` works, while

`add :rank, :float, default: 0.0, precision: 2`

throws the following error:

`** (Postgrex.Error) ERROR 42601 (syntax_error) syntax error at or near ","`

ecto_sql 3.2.0
phoenix master
phoenix_ecto 4.0.0
postgrex 0.15.1

**Comment by josevalim** [comment]
As far as I know you can’t have precision on floats, you need to use
numeric or similar. Floats are always 32 bits. Or you can use doubles for
64 bits.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by jamilabreu** [comment]
Got it! For anyone else, looked up numeric types and looks like :decimal might be a good option:

https://www.postgresql.org/docs/9.1/datatype-numeric.html

**Comment by bartblast** [comment]
@jamilabreu @josevalim Ecto's float is Postgres' double precision (64 bit). If you want to have a 32 bit float, use :real in migration and :float in schema, no need to resolve to decimals.
