### ISSUE TITLE
Strange TCP error when using Unix Domain Sockets

### ISSUE THREAD

**Issue by feld** [elixir-ecto/postgrex#490]
```
Dec  1 00:00:51 colo pleromadev[80979]: [error] Postgrex.Protocol #PID<0.551.0> could not cancel backend: tcp connect: non-existing domain - :nxdomain
```

I'm not sure why Postgrex would be trying to cancel Postgres backend connections over TCP when I'm using Unix Domain Sockets

**Comment by josevalim** [comment]
Can you please provide more information? Which version? How are you
invoking it? What are your connection options?
-- 


*José Valim*
www.plataformatec.com.br
Founder and Director of R&D

**Comment by feld** [comment]
With pleroma config:

```
config :pleroma, Pleroma.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "pleromadev",
  password: "REDACTED",
  database: "pleroma_dev",
  socket_dir: "/var/shared",
  pool_size: 4
```

And just running one of my dev servers and it gets overloaded for various reasons (intentional or not) I find these errors in my Pleroma logs

**Comment by josevalim** [comment]
So it only happens under load and not during regular execution? I.e. the
app still boots with this config?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by feld** [comment]
Yes, correct, the application works but this error comes up under load and makes me wonder if it's failing to kill long running connections/queries because it's trying to use TCP

**Comment by josevalim** [comment]
What is your Erlang/OTP? And the postgrex version in your mix.lock?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by feld** [comment]
```
  "postgrex": {:hex, :postgrex, "0.15.1", "23ce3417de70f4c0e9e7419ad85bdabcc6860a6925fe2c6f3b1b5b1e8e47bf2f", [:mix], [{:connection, "~> 1.0", [hex: :connection, repo: "hexpm", optional: false]}, {:db_con
nection, "~> 2.1", [hex: :db_connection, repo: "hexpm", optional: false]}, {:decimal, "~> 1.5", [hex: :decimal, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional:
true]}], "hexpm"},
```

erlang/otp version is 21.3.8.10

**Comment by josevalim** [comment]
So good news. This error only happens when we are at the end of disconnecting. So they should not affect your operation. The bad news is that there is something else going on here, so please look at your logs if you find more information!
