### ISSUE TITLE
Non-strict encoding of empty arrays

### ISSUE THREAD

**Issue by karlseguin** [elixir-ecto/postgrex#491]
I'm not sure if this is a bug in Postgrex or CockroachDB, but empty lists are currently encoded with the last 2 bytes (length + start index) missing.

For example, an empty int4 array is encoded as `<<0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 134>>
`, whereas cockroachdb expects: `<<0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 134, 0, 0, 0, 0, 0, 0, 0, 1>>`

From what I could understand, libpq DOES include the extra two bytes when encoding (if ndims == 0 then ndims = 1 type thing), however it also tolerates the missing lengths when decoding. So how this should be encoded seems ambiguous to me (FWIW, I once contributed some array encoding/decoding logic to go's pgx library, and we included those two bytes also).

**Comment by josevalim** [comment]
I am ok with including them as long as our tests pass for PG. Can you please send a PR? Thanks!
