### ISSUE TITLE
Multiple hosts connection

### ISSUE THREAD

**Issue by big-town** [elixir-ecto/postgrex#496]
Hello. Are you planning to integrate support multiple hosts connection in the driver? I mean about this https://paquier.xyz/postgresql-2/postgres-10-multi-host-connstr/

**Comment by josevalim** [comment]
If someone sends a pull request, sure!

**Comment by josevalim** [comment]
Closing this. If there is an interest, we will be glad to reopen!

**Comment by kevinlang** [comment]
This would enable use of [pg_auto_failover](https://github.com/citusdata/pg_auto_failover#application-and-connection-strings) which depends on this functionality to implement HA Postgres.

More notes on that here:
https://pg-auto-failover.readthedocs.io/en/latest/architecture.html#client-side-ha
