### ISSUE TITLE
PGHOST is not working for local socket case

### ISSUE THREAD

**Issue by tkachuk-labs** [elixir-ecto/postgrex#501]
https://github.com/elixir-ecto/postgrex/blob/27cb2dcce72f5ac0bf23dd889be4fa486933191e/lib/postgrex.ex#L74

```
export PGHOST=/tmp/postgres
```

causes error

```
13:13:01.248 [error] GenServer #PID<0.286.0> terminating
** (DBConnection.ConnectionError) tcp connect (/tmp/postgres:5432): non-existing domain - :nxdomain
    (db_connection) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
```

**Comment by wojtekmach** [comment]
PGHOST is used for the server host, not the socket. To connect via custom socket, do:

```
Postgrex.start_link(socket: path_to_socket)
```

Per https://www.postgresql.org/docs/9.4/app-psql.html, the socket might be passed as `PGPORT` and so you can send a PR for that but first I'd let other maintainers chime in whether this would be desirable (I think it would.)

**Comment by wojtekmach** [comment]
I take it back, PGHOST can indeed be used as a directory with sockets:

```
~% PGHOST=/path/to/sockets PGPORT=1234 psql
(...)
	connections on Unix domain socket "/path/to/sockets/.s.PGSQL.1234"?
```

In any case, today you can do: `Postgrex.start_link(socket_dir: "/tmp/postgres")`.
