### ISSUE TITLE
How I can get the last inserted ID

### ISSUE THREAD

**Issue by edwinallenz** [elixir-ecto/postgrex#508]
Quick question.
After running something like 
```
Postgrex.query!(postgres, "INSERT INTO my_table (name) VALUES ('#{name}')", []) 
```
from a table with an id column from a sequence, how I can get the value of the last inserted Id?

**Comment by leandrocp** [comment]
Add the `RETURNING` statement to your query:

```
Postgrex.query!(postgres, "INSERT INTO my_table (name) VALUES ('#{name}') RETURNING id", [])
```

Result will be on the `rows` field.

But I recommend using the repo from your app instead of `Postgrex` directly, unless you have a specific reason. Also, I recommend posting those kind of question on https://elixirforum.com/ :)

**Comment by edwinallenz** [comment]
wow thanks a lot, I've been looking for that feature
