### ISSUE TITLE
pg_trgm: Operator does not exist: text % text

### ISSUE THREAD

**Issue by alexfreska** [elixir-ecto/postgrex#509]
Hello, I am trying to use the `pg_trgm` module with `SET pg_trgm.similarity_threshold` and the `%` operator to optimize a query (in a way similar to [this Stackoverflow answer](https://stackoverflow.com/questions/11249635/finding-similar-strings-with-postgresql-quickly)), but am getting Postgrex operator errors. The queries below work with Postgres directly, but not with Postgrex.

Here is an (simplified) example query:
```elixir
query = """
  select similarity(song.name, 'song name') as sim, *
  from song
  where song.name % 'song name'
  order by sim DESC
  limit 10
"""
```

I get the following Postgrex error:
```elixir
** (Postgrex.Error) ERROR 42883 (undefined_function) operator does not exist: character varying % unknown
```

Or the query with explicit type casts according to the `%` signiture:
```elixir
query = """
  select similarity(song.name::text, 'song name'::text) as sim, *
  from song
  where song.name::text % 'song name'::text
  order by sim DESC
  limit 10
"""
```
```elixir
(Postgrex.Error) ERROR 42883 (undefined_function) operator does not exist: text % text
```

Am I approaching this the wrong way? Do I need to write a Postgrex extension for the `%` function?

Thank you in advance for any help or info, and I would be happy to contribute if someone could point me in the right direction.

**Comment by josevalim** [comment]
You shouldn't need anything. How are you running the query above? Is your psql session and your Postgrex connected to the same database?

**Comment by alexfreska** [comment]
Hey Jose, this was due to a Postgres configuration error on my part - `pg_trgm` was only installed on a specific schema. I reinstalled it in `public` and things are working! Thank you for the fast response 🙏
