### ISSUE TITLE
[Ask for help] Origin of a postgres timeout impossible to determine

### ISSUE THREAD

**Issue by lanarchyste** [elixir-ecto/postgrex#510]
Hi,

I have a mobile application (C#) which call an API using phoenix and ecto.

This API makes several calls to the postgres database. Each call lasts approximately 60ms and we make approximately 25 calls to the database.

But at some point, I get a timeout from the database.

Here is the postgres error:
`2020-06-04 09:40:03.503 CEST [24455] postgres@view_models ERROR:  canceling statement due to user request
2020-06-04 09:40:03.503 CEST [24455] postgres@view_models STATEMENT:  SELECT DISTINCT ON (i0."intervention_id") i0."intervention_id" FROM "interventions" AS i0 LEFT OUTER JOIN "appointments" AS a1 ON a1."intervention_id" = i0."intervention_id" WHERE ((i0."account_id" = $1) AND ((i0."updated_at" > $2) OR (a1."updated_at" > $3))) LIMIT 1
2020-06-04 09:40:03.504 CEST [24455] postgres@view_models LOG:  could not send data to client: Broken pipe
2020-06-04 09:40:03.504 CEST [24455] postgres@view_models FATAL:  connection to client lost`

Here is the ecto error:
`DBConnection.ConnectionError: tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)`

The postgres **statement_tiemout** parameter is 0

Here is the ecto config:
`config :query_backend, QueryBackend.V1.Repo,
  username: System.get_env("POSTGRES_USERNAME"),
  password: System.get_env("POSTGRES_PASSWORD"),
  database: System.get_env("VIEW_POSTGRES_DB_NAME"),
  hostname: System.get_env("POSTGRES_HOST"),
  pool_size: 10,
  queue_target: 3_000,
  queue_interval: 15_000,
  connect_timeout: 20_000,
  timeout: 30_000`

On the mobile, the HTTP client timeout is 15s.

This problem is reproduced only by our customers and our technical team cannot reproduce it.

Can you tell me if my configuration is valid? What is the origin of timeout? the mobile HTTP client, Ecto, Postgres ?

Thank you in advance for your help

Best regards.
Julien.

**Comment by josevalim** [comment]
Hi Julien, please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
