### ISSUE TITLE
RDS Proxy connection pinning

### ISSUE THREAD

**Issue by bforchhammer** [elixir-ecto/postgrex#514]
Hi, 

I am currently testing the AWS RDS Proxy with one of our services using ecto/postgrex. It has a feature called "session pinning" which pins client connections to connections to the RDS database being proxied; this feature is enabled automatically whenever the RDS Proxy detects features that depend on connection state. Since it limits connection re-use, it is also something which is recommended to avoid if possible; see [AWS docs](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-proxy.html#rds-proxy-pinning) for more details and a list of features which may trigger connection pinning. 

In my current case unfortunately it seems that _all_ connections are currently being pinned due to usage of the extended query protocol. Specifically, we are seeing the following log messages:

> 2020-08-04T11:47:24.251Z [WARN] [clientConnection=3888679423] The client session was pinned to the database connection [dbConnection=529039385] for the remainder of the session. The proxy can't reuse this connection until the session ends. Reason: A parse message was detected.

(Note that this is with unnamed prepared statements as suggested for pg_bouncer in the README; which unfortunately did not seem to have any effect on session pinning with the RDS proxy.)

My questions would be:

1. is it reasonable to assume that postgrex is responsible for those parse messages?
2. if yes, is there anything that could be done to reduce/avoid session pinning with RDS proxies?

I appreciate any ideas/thoughts on this issue! Thanks!

**Comment by josevalim** [comment]
Postgrex is fully built on extended queries, therefore I don't believe there is an alternative here that fully disables it. Somebody could add connection reaping, so we automatically disconnect after N seconds, limiting the length of the session, but AFAIK nobody has contributed it yet. :)

**Comment by chaodhib** [comment]
Hello,

If it was possible to disable the automatic pinning of connections that use the extended protocol, could it be possible to use RDS Proxy? [The same limitation than using pg_bouncer ](https://www.pgbouncer.org/features.html) would hold then (the need to use unnamed statements, to not keep state in the sessions, ..). Is that correct?

**Comment by josevalim** [comment]
You can disable prepared queries by setting prepare: :unnamed. See PG Bouncer config in README/docs.
