### ISSUE TITLE
Ecto.Query.API.ago/2 against timestamptz depends on timezone setting?

### ISSUE THREAD

**Issue by julp** [elixir-ecto/postgrex#518]
Hi,

I was migrating from `:utc_datetime` to `:timestamptz` and see that some of my tests were now failing. In the end, I was able to associate these failures to my use of Ecto.Query.API.ago/2.

In fact, when you write `column > ago(X, "second")`, postgrex "rewrites" it to `column > $1::timestamp + ($2::numeric * interval '1 second')`

My understanding is, since I changed *column* to *timestamp with time zone*, PostgreSQL apply the value of its current *timezone* setting to the right operand of `>` (because it is a *timestamp **without** time zone*) before the comparaison. But this can result in "weird" results if *timezone* is set to something else than 'UTC':

```
SET timezone = 'Europe/Paris'; /* UTC+1 as of 2001-02-16 */
SET

SELECT (TIMESTAMP WITH TIME ZONE '2001-02-16 20:38:43+00') > ('2001-02-16 20:38:40'::timestamp + (3 * INTERVAL '1 second'));
 ?column? 
----------
 t /* when you probably expect f(alse) */

set timezone = 'UTC';
SET

SELECT (TIMESTAMP WITH TIME ZONE '2001-02-16 20:38:43+00') > ('2001-02-16 20:38:40'::timestamp + (3 * INTERVAL '1 second'));
 ?column? 
----------
 f
```

(the part `(TIMESTAMP WITH TIME ZONE '2001-02-16 20:38:43+00')` simulates my *timestamp with time zone* column)

It's not really a bug but I think it might exist several ways to, still, have a consistent and reliable result:
* set `timezone` to 'UTC' at connection
* cast as `::timestamp AT TIME ZONE 'UTC'` instead of `::timestamp` (for a %DateTime{} in "Etc/UTC" time_zone as value)

I hope I didn't miss some point, thanks.

**Comment by josevalim** [comment]
Hi @julp, if you are not running your database in UTC, it is likely that you will run into other weird scenarios besides this one. That's why drivers like Postgrex (and I believe also Ecto) document you should guarantee the time is set as UTC. We discussed doing so automatically but it seems it could cause permission issues in some cases where otherwise Ecto would run fine.

So I believe "option 1" is the way to go. We can't do it automatically but you can configure your connection:

    after_connect: {Postgrex, :query!, ["SET TIMESTAMP 'UTC'"]}

Thoughts?

**Comment by julp** [comment]
Hi José,

my apologies, this was not what I understood from the documentations and I haven't try to force the timezone to UTC because, on my own server and application, I can do it of course, but I can't guarantee it for someone who uses a library (hex package).

If (any) PostgreSQL client could override timezone without permission issue, it would be the simplest way to fix this. IMO, the best solution **would** be to not rely at all on PostgreSQL's timezone setting to have a consistent, reproducible and reliable result.

At least, this "non-issue" might serve people in the future ;)

---

On a second thought:

* Ecto.Query.API.from_now/2 is (internally) based on now - DateTime.utc_now/0 - so as %DateTime{} with time_zone: "Etc/UTC" (before calling Ecto.Query.API.datetime_add/3)
* Ecto.Query.API.ago/2: same
* Ecto.Query.API.datetime_add/3 is particular since it accepts %DateTime{} as %NaiveDateTime{}

I was wondering if it would work by:
* translating %NaiveDateTime{} to `$X::timestamp` (but it might be a good idea to discourage if not deprecate the use of NaiveDateTime here)
* shifting %DateTime{} to UTC (if not already in UTC) then translate it to `($X::timestamp AT TIME ZONE 'UTC')` or directly map :utc_datetime to timestamptz (by setting the appropriate PostgreSQL's timezone or, same, if easier, shifting the %DateTime{} to UTC first to have UTC as unique input timezone for PostgreSQL)

**Comment by josevalim** [comment]
Right, `$X::timestamp AT TIME ZONE 'UTC'` won't be enough and unfortunately changing DateTime to timestasmptz would be a backwards incompatible change - which we don't plan on doing. I would also be concerned with mixing both timestamp and timestamptz and the connection timezone is not UTC.

So overall I think the best we can do at this point is document more clearly the UTC requirement. :)

**Comment by julp** [comment]
Ok, lesson learned. Thank you José!
