### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nmbrone** [elixir-ecto/postgrex#520]
Hi all. 

Thanks for all of your work. 

Do you plan any release shortly? Hex.pm version seems a bit outdated. Or there are reasons?

**Comment by josevalim** [comment]
There are no reasons but note there has been only 5 commits since the last release, so there is nothing really pressuring us to update. Do you need master for some reason?

**Comment by nmbrone** [comment]
Thanks for the quick response.
Decimal 2 is the thing. But `{:decimal, "~> 2.0", override: true}` obviously solves the problem.
Please feel free to close this.

**Comment by josevalim** [comment]
v0.15.6 released!
