### ISSUE TITLE
Support negative dates

### ISSUE THREAD

**Issue by zacharydenton** [elixir-ecto/postgrex#522]
Postgrex currently uses Erlang's `:calendar` module to encode and decode Postgres dates (https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/extensions/date.ex#L31). The `:calendar` module only supports dates with year >= 0. Thus, attempting to insert a negative `Date` results in a crash:

```
 [error] Task #PID<0.26744.1> started from #PID<0.95.0> terminating
** (FunctionClauseError) no function clause matching in :calendar.last_day_of_the_month/2
    (stdlib 3.13.1) calendar.erl:257: :calendar.last_day_of_the_month(-300, 1)
    (stdlib 3.13.1) calendar.erl:133: :calendar.date_to_gregorian_days/3
    (postgrex 0.15.6) lib/postgrex/extensions/date.ex:31: Postgrex.Extensions.Date.encode_elixir/1
    ...
```

I looked into options for changing the codec implementation in order to support negative dates. Unfortunately, it doesn't look like postgres understands the `Date.to_iso8601` format for negative dates:

```
# select '-0300-01-01'::date;
ERROR:  time zone displacement out of range: "-0300-01-01"
```

However, there are two options that it does appear to support for negative dates (the second one is the Julian day):

```
# select 'Jan 1, 300 BC'::date;
     date
---------------
 0300-01-01 BC

# select 'J1611853'::date;
     date
---------------
 0300-01-01 BC
```

Perhaps we can switch to one of these options in order to support negative dates.

**Comment by josevalim** [comment]
I plan to migrate to Elixir's Calendar but we needed some features that were added just in v1.11. Also note that Date.to_iso9601 doesn't matter much because we use the wire format where we send just the amount of seconds since a given epoch and not a string representation.

**Comment by kipcole9** [comment]
This issue was also raised in [Elixir Forum](https://elixirforum.com/t/ecto-postgres-timestamp-before-year-0/40120). Is this an appropriate time to submit a PR for Elixir 1.13?

**Comment by josevalim** [comment]
Yes, a PR would be welcome! I think we can even support earlier Elixir versions, but they require using the internal rata die representation, but I think it should be fine as we don't plan to change it. :)

**Comment by josevalim** [comment]
Yeah, I think we added it when we bumped the Elixir requirement!
