### ISSUE TITLE
Option to prevent parsing query result?

### ISSUE THREAD

**Issue by kmurph73** [elixir-ecto/postgrex#523]
In Rails, when serving JSON APIs, I often pipe JSON straight out of the DB if no server-side processing is needed, EG:

```ruby
ActiveRecord::Base.connection.execute(query)[0]['json_build_object']
```

My query looks something like

```sql
SELECT json_build_object('products',
  ( SELECT json_agg(row_to_json(t))
    FROM
      ( SELECT id, name FROM products ) t 
  ))
```

Rails returns this as a string, which I then send back to the client.

In Postgrex, this gets parsed as:

```elixir
%Postgrex.Result{
  columns: ["json_build_object"],
  command: :select,
  connection_id: 60321,
  messages: [],
  num_rows: 1,
  rows: [[%{"products" => [%{"id" => 1, "name" => "My Product"}]}]]
}
```

Which is fine for most cases.  However, I don't want the result to be parsed in certain scenarios, I just want the raw JSON string to send back to the client.

Is it possible to add an option to `Postgrex.query` that bypasses the parsing stage?  Thank you.

**Comment by wojtekmach** [comment]
there's currently no way to stop Postgres from decoding on a given type, however I think the easiest solution is on the database side to ensure it is returned as string: `::text`.

**Comment by kmurph73** [comment]
@wojtekmach thanks, doing that was easier than expected
