### ISSUE TITLE
update connection lib to latest version

### ISSUE THREAD

**Issue by ray-sh** [elixir-ecto/postgrex#526]
Hi,
Currently, I see lots of compiling warning message.
Compiling 1 file (.ex)
warning: System.stacktrace/0 is deprecated, use __STACKTRACE__ instead
  lib/connection.ex:429

Any plan to update to connection 1.1.0 which has fix this?
https://diff.hex.pm/diff/connection/1.0.4..1.1.0

My env is
mix phx.new -v
Phoenix v1.5.6

elixir -v 
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.11.1 (compiled with Erlang/OTP 23)
Thanks

**Comment by wojtekmach** [comment]
Thanks for the report. The fix is already in db_connection (https://github.com/elixir-ecto/db_connection/commit/2824a2edada88bf97e486f75ddd42c77ca26dde5) so you can use master while waiting for a new release.

**Comment by wojtekmach** [comment]
db_connection v2.3.1 is out!
