### ISSUE TITLE
Connect to Unix socket with 1.0

### ISSUE THREAD

**Issue by hauleth** [elixir-ecto/postgrex#527]
From what I see in the code the possibility to connect to the Unix socket using Postgrex is removed. Is there any reason why? This feature is handy for local development where one can have different Postgres versions per project, so Unix sockets are the easiest way to manage connections.

**Comment by josevalim** [comment]
What do you mean by is removed? The :socket option is explicitly documented and it has examples. :)

**Comment by hauleth** [comment]
Call me blind, but I cannot see how I could make the [`host` here](https://github.com/elixir-ecto/postgrex/blob/0729979bec52830ac9e146dd7d429161b055d677/lib/postgrex/protocol.ex#L455) to be `{:local, path}`. And nowhere in documentation I can find the example that uses local socket.

**Comment by josevalim** [comment]
Did you search for the above mentioned socket option in the docs?

**Comment by hauleth** [comment]
Well - [I did](https://hexdocs.pm/postgrex/1.0.0-rc.1/Postgrex.html#start_link/1) and found nothing.

**Comment by josevalim** [comment]
Oh. This was published by mistake quite some time ago. It is not how 1.0 will look like. The package has been retired but the docs don’t reflect that. Use latest v0.15.

**Comment by wojtekmach** [comment]
yup, this is the correct link to latest docs: https://hexdocs.pm/postgrex/Postgrex.html#start_link/1

**Comment by hauleth** [comment]
Written email to the Dash author as this was main source of the confusion (it fetches docs for the highest version, not highest stable version).
