### ISSUE TITLE
Custom :json_library breaks deps.compile: "module is not available or is yet to be defined"

### ISSUE THREAD

**Issue by ftes** [elixir-ecto/postgrex#532]
# How to reproduce
1. Create and configure a custom `:json_library`.
```ex
defmodule MyJasonDecorator do
  def encode_to_iodata!(input), do: Jason.encode_to_iodata!(input)
  def decode!(iodata), do: Jason.decode!(iodata)
end
```

```ex
# config.exs
config :postgrex, :json_library, MyJasonDecorator
```

2. Run `mix deps.compile postgrex --force`
```
MyJasonDecorator.encode_to_iodata!/1 is undefined (module MyJasonDecorator. is not available or is yet to be defined)
```

# References
- Slack post: https://elixir-lang.slack.com/archives/C087B66BY/p1611225263005000
- Answer by **lostkobrakai:**
> In the end the answer is you can’t (relyably). The only thing causing order between dependencies is the dependency tree. The only thing making anything compile before postgrex is postgrex depending on it (even if it’s an optional dependency). Given the only json library postgrex depends on is jason the option to configure it is essentially useless. I’d open an issue in postgrex about the compile time usage for the json_library config.

**Comment by josevalim** [comment]
Thanks! Btw, is it a warning or is it a compilation error?

**Comment by ftes** [comment]
Its a warning.
