### ISSUE TITLE
Proposal: make the `database` parameter in connection config optional

### ISSUE THREAD

**Issue by beorc** [elixir-ecto/postgrex#534]
Is there any reason why it is required?

**Comment by josevalim** [comment]
My understanding is that it is required by Postgres when establishing a TCP connection.

**Comment by beorc** [comment]
Actually, it's not required by Postgres. For example, you don't have to connect to to database if you need to create role or grant permissions or just drop database. I had to switch to the `epgsql` in order to do it since it does not require the `database`.

**Comment by josevalim** [comment]
Ah, cool! A PR with a test then is very welcome! :)

**Comment by ericmj** [comment]
You cannot connect to postgres without connecting to a database.

We can default to connect to the database with the same name as the user, but I think being explicit with the database is a benefit.

**Comment by wojtekmach** [comment]
fwiw I noticed this:

```elixir
iex(2)> {:ok, pid} = Postgrex.start_link(database: ""); Postgrex.query!(pid, "SELECT current_database()", []).rows
[["wojtek"]]
```

**Comment by beorc** [comment]
> You cannot connect to postgres without connecting to a database.
> 
> We can default to connect to the database with the same name as the user, but I think being explicit with the database is a benefit.

The thing is that Postgres does not require this parameter and so do other clients like `psql` or `epgsql`. Sometimes I want to apply Postgres defaults instead of being specific in this regard. So IMO it would be more straightforward and less confusing to just follow the Postgres API.

**Comment by wojtekmach** [comment]
> to just conform the Postgres API.

which Postgres API? :-)

we have the server and the protocol which as Eric mentioned requires the explicit DB name, we have libpq which is _a_ client that indeed defaults the database to the current user name, and we have programs like `psql` that use `libpg`.

I think it's fair to argue that Postgrex should behave like libpg/psql/etc but the library never claimed to do that.

**Comment by ericmj** [comment]
> The thing is that Postgres does not require this parameter and so do other clients like psql or epgsql. Sometimes I want to apply Postgres defaults instead of being specific in this regard. So IMO it would be more straightforward and less confusing to just conform the Postgres API.

`psql` is an interactive tool, a more direct comparison would be the C API `libpq`. The C API defaults the database name as well, but it also defaults things like the username to the OS username which is even worse imo so I am not sure we should follow what it does.

Since there has already been some confusion about if connections are established to databases in this thread I am not sure it's a good idea to make these parameters implicit. When they are explicit it's clear what's going on under the hood.

If you want the same behavior as `psql` you can call `System.get_env("USER")` and pass that as username and database.

**Comment by beorc** [comment]
If I do not pass database name I end up connected to the `postgres` database now at least using psql. The database with the same name as username highly likely won't exist. So that one should find it out in order to do the same thing and pass "postgres" as database name. Default database name also could change, so that it is not guaranteed that database named `postgres` will exist.

**Comment by ericmj** [comment]
> If I do not pass database name I end up connected to the postgres database now at least using psql.

That only happens if you connect as the "postgres" user.

> So that one should find it out in order to do the same thing and pass "postgres" as database name. Default database name also could change, so that it is not guaranteed that database named postgres will exist.

I don't understand what you mean by this.

**Comment by beorc** [comment]
I mean the database with the same name as username may not exist

**Comment by ericmj** [comment]
> I mean the database with the same name as username may not exist

In that case `psql` will fail to connect if you do not explicitly specify a database. This problem does of course not apply for postgrex as you are always required to specify the database.
