### ISSUE TITLE
unknown oid(s) forcing us to reload type information from the database

### ISSUE THREAD

**Issue by shirokovnv** [elixir-ecto/postgrex#541]
Hello!

After upgrading phoenix application from elixir 1.6.6 -> 1.11.3 and postgrex 0.13.5 -> 0.15.9 
I have been catching strange error in authorization query:

%Postgrex.Query{cache: :reference, columns: nil, name: "ecto_3235", param_formats: nil, param_oids: nil, param_types: nil, ref: nil, result_formats: nil, result_oids: nil, result_types: nil, statement: "SELECT e0.\"tableoid\", e0.\"id\", e0.\"first_name\", e0.\"credentials\", e0.\"user_external_id\", e0.\"chat_enabled\", e0.\"reset_token\" FROM \"tenant_1\".\"employees\" AS e0 WHERE ((e0.\"credentials\").login = $1)", types: nil} uses unknown oid(s) 16427forcing us to reload type information from the database. This is expected behaviour whenever you migrate your database.

As long as I understood correctly, the problem is the employees table oid (16427) is wrong. 
But, If I run the same query from database terminal, it returns another oid: 17250. 

PostgreSQL Server Version = 13.

How can I fix that ?

Thanks.

**Comment by josevalim** [comment]
When does the error happens? Is it from time to time? On new deployments? On every query in this table? What is the Ecto query you are writing and your database schema?

**Comment by shirokovnv** [comment]
Sorry, I already figured it out.

I have an umbrella application with different postgrex versions in authable app and
app, that working with data layer. 

After correct versioning, the error disappeared.
