### ISSUE TITLE
Compilation warning with OTP-24: "a term is constructed, but never used"

### ISSUE THREAD

**Issue by J3RN** [elixir-ecto/postgrex#543]
When compiling postgrex with Elixir 1.11.4 and Erlang/OTP 24.0, the following warning is produced:
```
warning: a term is constructed, but never used
  lib/postgrex/type_module.ex
```

Also somewhat strangely, this warning is shown when compiling my work application:
```
$ mix compile --force --warnings-as-errors
Compiling 1247 files (.ex)

warning: a term is constructed, but never used
  /home/j3rn/Code/joydrive/joydrive/opt-24/deps/postgrex/lib/postgrex/type_module.ex

Compilation failed due to warnings while using the --warnings-as-errors option
```
Generally speaking, compilation warnings for dependencies are not shown when compiling an application for which the dependencies are already compiled (e.g. by running `mix deps.compile` beforehand, as here).

This warning is not shown when compiling postgrex or my work application with Elixir 1.11.4 and Erlang/OTP 23.

I spent a few hours trying to track down the cause this morning, but didn't get very far. Any pointers are appreciated! :grin:

**Comment by josevalim** [comment]
Do you define a custom type module? If so, what extensions you are using?

**Comment by josevalim** [comment]
To be clear, this is most likely due to a type module. It is called by your app but some of the code generation happens inside Postgrex, which gives the warning pointing to postgrex. But definitely coming from your app!

**Comment by J3RN** [comment]
Yes, we do define a custom type module. The entire file is this:
```elixir
Postgrex.Types.define(
  Joydrive.PostgresTypes,
  [Geo.PostGIS.Extension] ++ Ecto.Adapters.Postgres.extensions()
)
```

Here, `Geo.PostGIS.Extension` refers to the [the (rather tiny) Postgrex extension  in the `geo_postgis` library](https://github.com/bryanjos/geo_postgis/blob/v3.4.0/lib/geo_postgis/extension.ex).

Is it correct to say that the warning produced when compiling this repo in isolation is unrelated from the warning produced when compiling my app's codebase?

**Comment by josevalim** [comment]
Yes, they are unrelated.
Does the warning appear without the PostGiS extension?

**Comment by J3RN** [comment]
Yes. If I change that file's contents to only:
```elixir
Postgrex.Types.define(Joydrive.PostgresTypes, [])
```
The warning still appears, exactly as before.

**Comment by josevalim** [comment]
Thanks for the report! This is an Elixir bug that has been fixed on Elixir v1.12-rc and also the final release coming next week.

**Comment by tcitworld** [comment]
Is the bugfix going to be backported into 1.11 ?

**Comment by josevalim** [comment]
No but Elixir v1.12 will be released today and it should be fully compatible with v1.11 (as our releases are!).
