### ISSUE TITLE
'invalid types for the connection' error after a DB fail over

### ISSUE THREAD

**Issue by chaodhib** [elixir-ecto/postgrex#550]
There seems to be a bad interaction between Ecto and Postgrex regarding Postgrex types when using multiple endpoints.

Ecto caches Postgrex queries. A %Postgrex.Query struct contains a 'types' reference. A %Postgrex.Protocol struct also has a 'types' reference. the Protocol's `types` reference changes when a DB fail-over occurs and Postgrex connects to one of the replicas.
The result is that the 2 references diverge after a DB fail-over since the Query comes from a cache and was not updated. The Protocol on the other hand was updated with the new `types` reference.

The simplest fix I see would be to reopen this discussion https://github.com/elixir-ecto/postgrex/pull/535#discussion_r579806598 ? In other others, maybe `types` shouldn't depend on the specific instance in case multiple endpoints are provided?

### Steps to reproduce:
* Use any Ecto app with at least one primary and one secondary db instance. Here I will be using the sample app is provided at [1] below.
* `iex -S mix`
* `Core.Accounts.users()`
* trigger a DB fail-over
* once the fail-over has finished, call again `Core.Accounts.users()`

This is the result:
```
** (Postgrex.QueryError) query %Postgrex.Query{cache: :reference, columns: ["id", "email", "first_name", "last_name", "password_hash", "inserted_at", "updated_at"], name: "ecto_11588", param_formats: [], param_oids: [], param_types: [], ref: #Reference<0.3320560104.3017539587.79853>, result_formats: [:binary, :binary, :binary, :binary, :binary, :binary, :binary], result_oids: [20, 1043, 1043, 1043, 1043, 1114, 1114], result_types: [Postgrex.Extensions.Int8, Postgrex.Extensions.Raw, Postgrex.Extensions.Raw, Postgrex.Extensions.Raw, Postgrex.Extensions.Raw, Postgrex.Extensions.Timestamp, Postgrex.Extensions.Timestamp], statement: "SELECT u0.\"id\", u0.\"email\", u0.\"first_name\", u0.\"last_name\", u0.\"password_hash\", u0.\"inserted_at\", u0.\"updated_at\" FROM \"users\" AS u0 ORDER BY u0.\"email\"", types: {Postgrex.DefaultTypes, #Reference<0.3320560104.3017670659.79794>}} has invalid types for the connection
    (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:693: Ecto.Adapters.SQL.execute/5
    (ecto 3.6.2) lib/ecto/repo/queryable.ex:224: Ecto.Repo.Queryable.execute/4
    (ecto 3.6.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

[1] https://github.com/chaodhib/elixir-umbrella-sample-application/tree/reproduce_ecto_types_bug can be used with:

```
use Mix.Config

config :core, Core.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "XXX",
  username: "XXX",
  password: "XXX",
  endpoints: [{"DB_1", 5432}, {"DB_2", 5432}],
  pool_size: 1
```
in the file `apps/core/config/dev.secret.exs`

**Comment by josevalim** [comment]
Correct. We should clear the types cache whenever we change host/port.

**Comment by chaodhib** [comment]
Unless I'm not following you somewhere, we already change types in Postgrex upon connecting to a different host/port. The issue is that the Postgrex.Query itself is cached at the Ecto level (`ecto/repo/queryable.ex`). And that query has a reference to the previous `types`. Then the pattern matching at [protocol.ex#L374](https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/protocol.ex#L374) fails. [protocol.ex#L382](https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/protocol.ex#L382) is called instead.

**Comment by josevalim** [comment]
Oh, I see. I think we should move the types equality check to inside `query_member?` and have it return false if the types are not equal. WDYT? Since now we are reasonably expecting the types to change.

**Comment by chaodhib** [comment]
Sure, that change would solve the issue. However all the following queries will have to be re-parsed on every call since invoking `handle_prepare_execute` will not fix the mismatch between the Query's types and the Protocol's types.

I could be wrong but what I suggest would be to actually use the same types cache for a primary instance and its replicas, as opposed to what we agreed to in [the discussion here](https://github.com/elixir-ecto/postgrex/pull/535#discussion_r579806598). In the event that the types are updated, Postgrex has a "reload" mechanism to update the types, if I'm not mistaken.

**Comment by josevalim** [comment]
@chaodhib I was thinking that returning false on query_member? would force it to be cached once again. That's my goal here, so we are in sync!

**Comment by josevalim** [comment]
However, I think we cannot reuse types, I don't think there is a guarantee they would be compatible across servers?

**Comment by chaodhib** [comment]
> I was thinking that returning false on query_member? would force it to be cached once again. That's my goal here, so we are in sync!

Yes, we are in sync. Sadly however, I tested it and it doesn't work. The issue here is that we are, in effect, dealing with 2 different caches: the Postgrex one and the Ecto one (`Ecto.Query.Planner`). If `query_member?` returns `false`, only the Postgrex cache is updated. And the next time the client app queries Ecto, the Query will come from the Ecto cache (which still has an outdated reference). 

One way to reset the Ecto cache entry would be that Postgrex returns an error (and then [this line](https://github.com/elixir-ecto/ecto_sql/blob/d701128561c2e377113a31879ccc80184a030ada/lib/ecto/adapters/sql.ex#L716 ) is called) but we want to avoid this.

> However, I think we cannot reuse types, I don't think there is a guarantee they would be compatible across servers?

For a primary and its replicas, it might be the case. I admit I'm not 100% sure however. I will look into it further.

**Comment by josevalim** [comment]
If we return the query as parse of the response with a new ref, we will update the cache. See here (and other `update.(` calls in the same file):

https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/adapters/sql.ex#L699

And this will happen as long as we return a new ref in the query:

https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/adapters/postgres/connection.ex#L80-L85
