### ISSUE TITLE
EncodeError when doing a bulk UPDATE with VALUES syntax

### ISSUE THREAD

**Issue by rmoretto** [elixir-ecto/postgrex#557]
Hey all!

I'm trying to create a query using the bulk update pattern as described in the current [Postgres docs](https://www.postgresql.org/docs/13/sql-values.html), which mine looks like:
```sql
UPDATE test_table
SET data = update_data.data
FROM (
  VALUES 
    (1, '1.1'),
    (2, '1.1'),
    (3, '1.1')
) AS update_data (id, data)
WHERE test_table.id = update_data.id
```
Howeber the above query gives a cast error, as stated in the above docs (emphasis mine):
> When VALUES is used in INSERT, the values are all automatically coerced to the data type of the corresponding destination column. When it's used in other contexts, **it might be necessary to specify the correct data type**.

So to fix this problem I have put explicit casts in the query:
``` sql
UPDATE test_table
SET data = (update_data.data)::numeric
FROM (
  VALUES 
    (1, '1.1'),
    (2, '1.1'),
    (3, '1.1')
) AS update_data (id, data)
WHERE test_table.id = (update_data.id)::integer
```
Running this query directly in the `psql` CLI I can successfully update all 3 entries, but when I tried to use the same query with the `Postgrex.query!` function using parameter for the UPDATE (code below) I receive the following exception:

```
** (DBConnection.EncodeError) Postgrex expected a binary, got 2. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
    (postgrex 0.15.9) lib/postgrex/type_module.ex:897: Postgrex.DefaultTypes.encode_params/3
    (postgrex 0.15.9) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection 2.4.0) lib/db_connection.ex:1205: DBConnection.encode/5
    (db_connection 2.4.0) lib/db_connection.ex:1305: DBConnection.run_prepare_execute/5
    (db_connection 2.4.0) lib/db_connection.ex:1409: DBConnection.run/6
    (db_connection 2.4.0) lib/db_connection.ex:574: DBConnection.parsed_prepare_execute/5
    (db_connection 2.4.0) lib/db_connection.ex:566: DBConnection.prepare_execute/4
    (postgrex 0.15.9) lib/postgrex.ex:272: Postgrex.query_prepare_execute/4
```

Am I doing something wrong with the cast? Or should I transform all my parameters to binary before passing to the `Postgrex.query!` function?

Thanks all!

----
### Using:
OS: Ubuntu 20.04.2 LTS
PostgreSQL: 13.3 (Ubuntu 13.3-1.pgdg20.04+1)
Elixir: 1.12
Postgrex: 0.15

### Code used for test:
```elixir
defmodule PostgrexTestBulkUpdate do
  def test_bulk_update do
    {:ok, pid} = Postgrex.start_link(
      hostname: "localhost", 
      username: "postgres",
      password: "postgres",
      database: "test"
    )

    # Create a test table
    Postgrex.query!(pid, """
      CREATE TABLE test_table (
        id INTEGER PRIMARY KEY,
        data NUMERIC
      )
    """, [])
    
    # Add some test rows
    Postgrex.query!(pid, """
      INSERT INTO test_table (id, data)
      VALUES
      (1, '1.0'),
      (2, '1.1'),
      (3, '1.2'),
      (4, '1.3'),
      (5, '1.4'),
      (6, '1.5')
    """, [])

    # Issue the bulk update with values
    params = [
      2, Decimal.new("0.0"),
      4, Decimal.new("1.0"),
      6, Decimal.new("1.0"),
    ]

    # This raises the error:
    # ** (DBConnection.EncodeError) Postgrex expected a binary, got 2. 
    #     Please make sure the value you are passing matches the definition 
    #     in your table or in your query or convert the value accordingly.
    Postgrex.query!(pid, """
      UPDATE test_table
      SET data = (update_data.data)::numeric
      FROM (
        VALUES 
          ($1, $2),
          ($3, $4),
          ($5, $6)
      ) AS update_data (id, data)
      WHERE test_table.id = (update_data.id)::integer
    """, params)
  end
end
```

**Comment by ericmj** [comment]
The issue here is postgresql infers a different type than you expect, it is possible the type inference cannot use the type hints from outside the `FROM` so try adding them inside instead:

```
FROM (
  VALUES 
    ($1::integer, $2::numeric),
    ($3::integer, $4::numeric),
    ($5::integer, $6::numeric)
)
```

**Comment by josevalim** [comment]
The cli uses the text encoding while Postgrex uses the binary encoding. Given the data is encoded to rows, we don’t know its binary representation, so I don’t think we can make it work. You can force some queries to use the text encoding, but they don’t allow parameters. The best is probably to rewrite how you are approaching the problem.

**Comment by rmoretto** [comment]
I should have stated in the issue that we are using this pattern because we are handling some big updates (10000+ rows).

 I will try the @ericmj  response and measure the performance impact, otherwise I will seek other alternatives to the problem.

Thanks all for the response!
