### ISSUE TITLE
Feature Request: More descriptive error message when a value cannot be encoded into the database

### ISSUE THREAD

**Issue by axelson** [elixir-ecto/postgrex#562]
When passing an invalid value to the database an encoding error is raised by postgrex. For an `:integer` column an error may look like:

> (DBConnection.EncodeError) Postgrex expected an integer in -2147483648..2147483647, got 1624921391866. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.

While this is decently informative, I believe that the error message would be enhanced if it could include the failing column name so the user doesn't need to manually look for the column that is failing. The user can partially find the failing column by looking at the arguments list below, but if the value is duplicated across multiple columns then they'll have to look at multiple columns and cross-reference the type of each column to find the failing column.

Full error example:
> [error] Task #PID<0.11396.0> started from #PID<0.445.0> terminating
** (DBConnection.EncodeError) Postgrex expected an integer in -2147483648..2147483647, got 1624921391866. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
    (my_app 0.1.0) deps/postgrex/lib/postgrex/type_module.ex:897: MyApp.PostgresTypes.encode_params/3
    (postgrex 0.15.9) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection 2.4.0) lib/db_connection.ex:1205: DBConnection.encode/5
    (db_connection 2.4.0) lib/db_connection.ex:1305: DBConnection.run_prepare_execute/5
    (db_connection 2.4.0) lib/db_connection.ex:1409: DBConnection.run/6
    (db_connection 2.4.0) lib/db_connection.ex:574: DBConnection.parsed_prepare_execute/5
    (db_connection 2.4.0) lib/db_connection.ex:566: DBConnection.prepare_execute/4
    (postgrex 0.15.9) lib/postgrex.ex:251: Postgrex.query/4
    (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:798: Ecto.Adapters.SQL.struct/10
    (ecto 3.6.2) lib/ecto/repo/schema.ex:725: Ecto.Repo.Schema.apply/4
    (ecto 3.6.2) lib/ecto/repo/schema.ex:350: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (my_app 0.1.0) lib/my_app/backfill.ex:20: anonymous fn/1 in MyApp.Backfill.backfill/0
    (elixir 1.12.1) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.1) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.62590368/1 in MyApp.Backfill.backfill/0>, [ok: %MyApp.Earthquake{__meta__: #Ecto.Schema.Metadata<:built, "earthquakes">, detail: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/tx2021moze.geojson", geometry: %Geo.Point{coordinates: {-103.9138692, 31.59265521}, properties: %{}, srid: nil}, id: nil, mag: 1.7, place: "32 km WSW of Mentone, Texas", time: 1624921391866, title: "M 1.7 - 32 km WSW of Mentone, Texas", tsunami: 0, type: "earthquake", updated: 1624983886314, url: "https://earthquake.usgs.gov/earthquakes/eventpage/tx2021moze"}]]

**Comment by josevalim** [comment]
I will investigate but I am almost sure we don’t have this information. The type requirement can come from anywhere in a query, including complex expressions.

**Comment by axelson** [comment]
Thanks for taking a look!

**Comment by josevalim** [comment]
Yup, we simply don't have this information. Sorry. :(

The only solution I can think is to provide more specific types in Ecto too (i.e. int64, int32, etc) so we can detect it early on.
