### ISSUE TITLE
Passing read_only option through the connection config?

### ISSUE THREAD

**Issue by brainlid** [elixir-ecto/postgrex#567]
I would like to pass Postgres options through the Ecto Postgrex adapter during connection. 

These are the JDBC options but I presume some of these options exist or are supported?
https://jdbc.postgresql.org/documentation/head/connect.html

Specifically I want to set the `"readOnly"` to `true` in the connection and not the Repo. When set in the repo, it changes the compilation to remove create/update/delete functions. 

Is there a way to pass a `read_only` option through for the connection?

I've looked in a number of places:
- https://hexdocs.pm/ecto_sql/Ecto.Adapters.Postgres.html
- https://hexdocs.pm/postgrex/Postgrex.html#parameters/2

I've tried passing it through `:parameters` but that's not supported. Any tips? Is it possible?

**Comment by josevalim** [comment]
You can set an after_connect MFA and then run the following statement: `SET default_transaction_read_only = on`. Most options in those cases boil down to regular statements. :)
