### ISSUE TITLE
Ssl option :verify_peer does not work when using multiple endpoints

### ISSUE THREAD

**Issue by zucaritask** [elixir-ecto/postgrex#571]
When using endpoints (each with a different hostname) and connecting with SSL we cannot specify a list of `server_name_indication` hostnames as we do for endpoints but only one `hostname` as indicated by the code snippet below.

Our config for `Postgrex.start_link` looks like:
```elixir
endpoints = [{"database-1.eu-west-1.rds.amazonaws.com", 5432},  {"database-2.eu-west-1.rds.amazonaws.com", 5432}]
hostname = "database-1.eu-west-1.rds.amazonaws.com"

{:ok, pid } = Postgrex.start_link(
  endpoints: endpoints,
   username: "postgres",
   password: "redacted-password",
   database: "database",
   ssl: true,
   ssl_opts: [
     verify: :verify_peer,
     cacertfile: "./priv/cacert.pem",
     depth: 3,
     server_name_indication: String.to_charlist(hostname),
     customize_hostname_check: [
       match_fun: :public_key.pkix_verify_hostname_match_fun(:https)
     ]
)
```

We have thought of setting the value of the hostname as the default `server_name_indication` value for the `:ssl.connect` call in https://github.com/elixir-ecto/postgrex/blob/28e36907e7a8e2ec95337b28d9e7667454fcd1dc/lib/postgrex/protocol.ex#L712

I could start working on a PR to get some initial feedback on this. Thoughts?

**Comment by josevalim** [comment]
maybe we can support `{host, port, extra_options}` and the extra options are deep merged into the actual config?

**Comment by zucaritask** [comment]
PR #572 addresses this problem, it is now merged, so this issue is now closed.
