### ISSUE TITLE
Error table does not exist [name=pg_attribute]

### ISSUE THREAD

**Issue by jfcalvo** [elixir-ecto/postgrex#576]
I'm trying to connect to [QuestDB](https://questdb.io/docs/develop/connect#postgres-compatibility) with the following code:

```elixir
{:ok, pid} = Postgrex.start_link(
  username: "admin",
  password: "quest",
  database: "qdb",
  hostname: "localhost",
  port: 8812
)
```

And the following error is raised:

```
[error] Postgrex.Protocol (#PID<0.468.0>) failed to connect: ** (Postgrex.Error) ERROR 00000 (successful_completion) table does not exist [name=pg_attribute]
```

I guess that postgrex is trying to get some metadata about the database and probably because the poorly PostgreSQL compatibility layer implementation on QuestDB this error is raised.

Do we have some config setting or anything to avoid these kind of errors? I'm successfully executing queries to this database using psql.

* Using postgrex 0.15.9 with Elixir 1.11.4.
* Related issue on QuestDB repo: https://github.com/questdb/questdb/issues/819

**Comment by josevalim** [comment]
You can try setting `types: nil`, so we don't attempt to load typing information, but I am afraid a lot of the querying functionality won't work as expected. Please give it a try and let us know.

**Comment by jfcalvo** [comment]
> You can try setting `types: nil`, so we don't attempt to load typing information, but I am afraid a lot of the querying functionality won't work as expected. Please give it a try and let us know.

I get an error using the following call to `Postgrex.start_link` with `types: nil` as option:
```elixir
{:ok, pid} = Postgrex.start_link(
  username: "admin",
  password: "quest",
  database: "qdb",
  hostname: "localhost",
  port: 8812,
  types: nil
)
```

```
[error] GenServer #PID<0.468.0> terminating
** (RuntimeError) connect raised KeyError exception: key :types not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir 1.11.4) lib/keyword.ex:420: Keyword.fetch!/2
    (postgrex 0.15.9) lib/postgrex/protocol.ex:71: Postgrex.Protocol.connect/1
    (db_connection 2.4.0) lib/db_connection/connection.ex:82: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.14.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
```

Maybe because we are using `nil` and it's expecting some value?.

**Comment by josevalim** [comment]
Ok, if that doesn't work, then unfortunately we cannot support QuestDB trivially, as Postgrex relies on the types to encode information over the wire. We could tweak parts of the query, but but that doesn't seem to be an option right now, as the `pg_attribute` table is not available altogether.

**Comment by jfcalvo** [comment]
I guess I'll have to wait for QuestDB to improve the Postgres compatibility adding the `pg_attribute` table.

Thanks for the help @josevalim

**Comment by vilinski** [comment]
is it the same issue of QuestDb with dotnet?
trying c# api example by wriging and get the same error
