### ISSUE TITLE
Proposal: Adding create_slot, drop_slot and start_replication to Postgrex.Replication

### ISSUE THREAD

**Issue by greg-rychlewski** [elixir-ecto/postgrex#578]
Hi,

I have a proposal to alter `Postgrex.Replication` so that the initialization function doesn't start the replication process, but instead delegates those actions to different functions that can be used after the connection starts. 

This makes it possible for users to do the following things:
 - utilize pre-existing slots
 - create persistent slots
 - apply conditional logic based on whether or not a slot already existed

I have a branch in my fork to show what I was thinking: https://github.com/greg-rychlewski/postgrex/commit/44a0304573194d62db182e44ea81c0d4da1b4811. If this proposal moves forward I can clean it up and make a proper PR.

One problem that I don't have solved on my branch is when a user tries to use one of the commands after starting replication. This causes the messages to become intertwined and everything breaks apart. I had one idea to create a flag in the state to say whether or not the connection started replicating and then block any attempts to send other commands after that. But would be interested to hear other ideas.

Some future extensions I can think of:
- create functions for the rest of the commands allowed under the replication protocol
- some the the commands in the replication protocol return information that could be useful. i believe this can be extended to send back the rows in the result set for those commands

**Comment by josevalim** [comment]
Everything you said sounds good to me! PRs are welcome. The flag is also how i would do it. :+1:

Btw, may I ask what you plan to use this for? :)

**Comment by greg-rychlewski** [comment]
Thanks! Will send a PR soon.

My work-related goal is to eventually use this to create a system that replicates our OLTP database to a data warehouse in a reliable way. 

I also have some non-work relate goals that involve getting a deeper understanding of Postgres and Postgrex.

**Comment by greg-rychlewski** [comment]
@josevalim Apologies for the ping. Just wanted to mention that I created a PR, in case it got lost in the shuffle: https://github.com/elixir-ecto/postgrex/pull/579.

**Comment by josevalim** [comment]
No problem to ping! My backlog is lately higher than usual but I am hoping to catch up this upcoming week!

**Comment by josevalim** [comment]
Closing in favor of the PR!
