### ISSUE TITLE
Discussion/Proposal: Decoding pgoutput messages

### ISSUE THREAD

**Issue by greg-rychlewski** [elixir-ecto/postgrex#584]
Hi,

I wanted to see if you would be interested in having a module to decode the binary pgoutput messages for users. 

A potential objection would be that users can just use the wal2json plugin if they want non-binary messages. There are a few counterpoints to this:

  - It's possible the user is locked into a vendor that won't let them install extra extensions on their Postgres instance.
  - It would be nice if Postgrex could provide an out-of-the-box solution to decoding messages without relying on external libraries that may have bugs/issues or might stop being maintained.

If you think it's worth pursuing, I have a proposal. 

I really like the `Postgrex.Messages` module and would like to create something similar. I think it could be a good idea to use structs instead of records. From what I've seen they are more common/widely understood. 

The struct definitions could correspond to the [message definitions here](https://www.postgresql.org/docs/current/protocol-logicalrep-message-formats.html). And then a couple extra structs for things like keep alive messages. The `wal_start`, `wal_end`, `timestamp`, etc.. values that are common to all the `?w` messages could be put inside a single key in the structs for the `?b`, `?i`, `?c`,... nested messages, called something like "metadata".

Thanks

**Comment by josevalim** [comment]
Hi @greg-rychlewski, this is the part that I decided to not tackle on purpose. I want to keep the replication core lean, and it seems all features you requested so far have to be part of the connection, but the decoding can be done elsewhere with no problems. :+1:

**Comment by greg-rychlewski** [comment]
@josevalim Would you have interest in putting this in a separate project within `elixir-ecto`, similar to the way `phoenixframework` has `phoenix_html` and those kinds of helpers? 

I was planning on writing something for decoding the messages and was just curious if you'd be interested in reviewing/putting it up for people to use.

**Comment by josevalim** [comment]
Thanks for pinging but I would prefer not to put under this org, to not add more responsibilities on our shoulders :)

**Comment by josevalim** [comment]
Btw: https://github.com/cainophile/pgoutput_decoder

**Comment by greg-rychlewski** [comment]
Thanks!
