### ISSUE TITLE
ERROR 42725 (ambiguous_function) operator is not unique: unknown @> point

### ISSUE THREAD

**Issue by jon-mcclung-fortyau** [elixir-ecto/postgrex#600]
I have been struggling for quite a while trying to write a query to check if a point resides in a circle. I do not want to construct the entire query as a string because I am already extensively composing the query using Ecto features. The essence of what I am struggling with is the following:

```
schema "point" do
  field :x, :float
  field :y, :float
end

circle_x = 5.0
circle_y = 5.0
circle_radius = 10.0

from(
  p in Point, 
  where: fragment(
    "? @> point(?, ?)", 
    ^(%Postgrex.Circle{center: %Postgrex.Point{x: circle_x, y: circle_y}, radius: circle_radius}),
    p.x,
    p.y
  )
) |> Repo.all()
```

I get the following error:

```
** (Postgrex.Error) ERROR 42725 (ambiguous_function) operator is not unique: unknown @> point`

...

hint: Could not choose a best candidate operator. You might need to add explicit type casts
```

It was my understanding that the whole purpose of these extensions was to tell Ecto how to put it into a query. Is there any way to check if a point is in a circle using `fragment`?

The query I would expect it to generate is the following (which works when I run it through psql directly):

"SELECT * FROM points WHERE CIRCLE '((5.0, 5.0), 10.0)' @> POINT (p.x, p.y);"

**Comment by ericmj** [comment]
The error means that postgres doesn't know the type of the operator arguments. Try changing the query to: `?::circle @> point(?, ?)`.

**Comment by jon-mcclung-fortyau** [comment]
> 

And so my journey comes to an end. Many hours of work went into discovering as much as I did about this problem before posting this issue, but the final puzzle piece has been laid by you, @ericmj . I rest, as a traveler who has trekked across the desert and after many weeks arrives at his destination. From the bottom of my heart, I thank you.
