### ISSUE TITLE
Type matching issues when using different schemas

### ISSUE THREAD

**Issue by fiodorbaczynski** [elixir-ecto/postgrex#607]
Hi, I've run into a weird issue with Postgrex.

## Setup:

1. Database schemas: `public`, `foo`.
2. Database user `foo`, with `search_path='foo'`.
3. Database table: `bars (id: bigint, name: citext)`
4. Ecto schema:

   ```
   defmodule Bar do
     # ...
     schema "bars" do
       field(:name, :string)
     end
   end
   ```

## Issue:

When I try to query from `bars`, for example `Repo.all(Bar)`, I get:

```
[error] Postgrex.Protocol (#PID<0.963.0>) disconnected: ** (Postgrex.QueryError) type `citext` can not be handled by the types module Postgrex.DefaultTypes
```

## Findings:

1. Since the extension is in the `public` schema, but the `search_path` for my user is `foo`, the functions(?) from the `citext` extension get a `public.` prefix:
   ```
   %Postgrex.TypeInfo{
     array_elem: 0,
     base_type: 0,
     comp_elems: [],
     input: "public.citextin",
     oid: 16397,
     output: "public.citextout",
     receive: "public.citextrecv",
     send: "public.citextsend",
     type: "citext"
   }
   ```
   
   when it runs normally (for example with `search_path='public,foo'`) the type info is different:
   
   ```
   %Postgrex.TypeInfo{
     array_elem: 0,
     base_type: 0,
     comp_elems: [],
     input: "public.citextin",
     oid: 16397,
     output: "citextout",
     receive: "citextrecv",
     send: "citextsend",
     type: "citext"
   }
   ```
2. The `citext` type is supposed to be handled by `Postgrex.Extensions.Raw`.
3. The `Postgrex.Extensions.Raw` module defines its types like this:
   ```
   defmodule Postgrex.Extensions.Raw do
     @moduledoc false
     import Postgrex.BinaryUtils, warn: false

     use Postgrex.BinaryExtension,
       send: "bpcharsend",
       send: "textsend",
       send: "varcharsend",
       send: "byteasend",
       send: "enum_send",
       send: "unknownsend",
       send: "citextsend",
       send: "charsend"
     
     # ...
   end
   ```
4. From this `Postgrex.Utils` generates a `case` that matches type info to the extensions.
5. The relevant case clause looks like this: `%{send: "citextsend"} when ... -> ...`.
6. In my case this clause doesn't match because the type info is `%{send: "public.citextsend"}`.

## Potential solution:

In `Postgrex.Extensions.Raw`, change `send: "citextsend"` to `type: "citext"`. The type field seems independent of where the type extension lives in the database. (This would probably need to be applied to the other clauses as well.)

**Comment by josevalim** [comment]
Reverting to type will cause other issues: https://github.com/elixir-ecto/postgrex/issues/233

You have to make sure citext is installed on all schemas instead. Check out the issues tracker for previous issues. :)

**Comment by fiodorbaczynski** [comment]
Thank you for such a quick response :)
 
> You have to make sure citext is installed on all schemas instead. Check out the issues tracker for previous issues. :)

I'm not sure what you mean by that. There doesn't seem to be a way to install extensions on multiple schemas (for example `ALTER EXTENSION citext SET SCHEMA public, foo;` gives a syntax error). Are you suggesting the extension should be moved to `pg_catalog`?

I read some other issues, but none of the suggestions seemed to work / apply in my case. Sorry if this is a duplicate.

**Comment by josevalim** [comment]
Thank you for following up with detailed steps for future reporters. It seems we are good now, thank you!
