### ISSUE TITLE
(Postgrex.Error) ERROR 42P01 (undefined_table) relation "bsc.lib_blks" does not exist

### ISSUE THREAD

**Issue by watsy0007** [elixir-ecto/postgrex#618]
postgresql version: 14
elixir: 1.14.0

i create tables under `bsc` schema.

then try write some code with livebook.

but get error like `(Postgrex.Error) ERROR 42P01 (undefined_table) relation "bsc.lib_blks" does not exist`

i don't know why and how to fix it. 

livebook code

<img width="600" alt="image" src="https://user-images.githubusercontent.com/822237/188859761-514bd732-7022-4731-814c-cc021effc67c.png">

DataGrip
<img width="600" alt="image" src="https://user-images.githubusercontent.com/822237/188859978-78f6cf81-45af-4bd0-8d6a-906f327d0434.png">

**Comment by josevalim** [comment]
@watsy0007 which database are you connecting to? Make sure you are connecting both to the "postgres" database.

**Comment by watsy0007** [comment]
sorry, i connect to wrong database.  😭
