### ISSUE TITLE
`Postgrex.QueryError` thrown with extensions installed in `heroku_ext` schema

### ISSUE THREAD

**Issue by tomtaylor** [elixir-ecto/postgrex#619]
Heroku recently changed how extensions are installed, so new extensions have to be installed in the `heroku_ext` schema, separately from the `public` schema that normal tables, etc. are in.

https://devcenter.heroku.com/changelog-items/2446
https://help.heroku.com/ZOFBHJCJ/heroku-postgres-extension-changes-faq

We'd like to reproduce this environment on our development machines + CI, so we're building and testing in the same way.

We've added a migration that creates the `heroku_ext` schema if it doesn't exist, and moved the existing extensions into it using, e.g. `execute "ALTER EXTENSION citext SET SCHEMA heroku_ext"`

We've also added the following in our `config.exs`:

```elixir
query_args = ["SET search_path TO public,heroku_ext", []]

config :poplar, Poplar.Repo,
  types: Poplar.PostgresTypes,
  after_connect: {Postgrex, :query!, query_args}
```

This seems to have moved the extensions correctly and updated the references in the table structures to the namespaced extensions. However, we still can't run our app. The following error is thrown whenever a query is made:

```elixir
** (Postgrex.QueryError) type `citext` can not be handled by the types module Poplar.PostgresTypes
     code: assert {:ok, user} = Accounts.create_user(@valid_attrs)
     stacktrace:
       (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:847: Ecto.Adapters.SQL.execute/6
       (ecto 3.8.4) lib/ecto/repo/queryable.ex:221: Ecto.Repo.Queryable.execute/4
       (ecto 3.8.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
       (ecto 3.8.4) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.exists?/3
       (ecto 3.8.4) lib/ecto/changeset.ex:1910: Ecto.Changeset.unsafe_validate_unique/4
       (poplar 0.0.1) lib/poplar/accounts/user.ex:35: Poplar.Accounts.User.create_changeset/2
       (poplar 0.0.1) lib/poplar/accounts/accounts.ex:54: Poplar.Accounts.create_user_changeset/1
       (poplar 0.0.1) lib/poplar/accounts/accounts.ex:34: Poplar.Accounts.create_user/1
       test/poplar/accounts/accounts_test.exs:10: (test)
```

We're defining types using:

```elixir
Postgrex.Types.define(
  Poplar.PostgresTypes,
  [Geo.PostGIS.Extension] ++ Ecto.Adapters.Postgres.extensions(),
  json: Jason
)
```

I've found a few other older issues referring to similar problems, such as https://github.com/elixir-ecto/postgrex/issues/592, which imply that extensions should be installed in all schemas. Given we can't do that for Heroku Postgres, is there any scope to reconsider this and find a solution that will work in these environments?

**Comment by greg-rychlewski** [comment]
@tomtaylor Does flipping the order of your search path work, so that heroku_ext comes before public? Someone else reported that as a solution for a situation similar to yours..

**Comment by tomtaylor** [comment]
> It might be the case `search_path` is not actually being set? You could try printing out the results of `SHOW search_path` in your dev environment.

Good idea, but it looks like it's being set correctly...

```elixir
iex(5)> Poplar.Repo.query!("SHOW search_path")
%Postgrex.Result{
  columns: ["search_path"],
  command: :show,
  connection_id: 76905,
  messages: [],
  num_rows: 0,
  rows: [["public, heroku_ext"]]
}
```

**Comment by greg-rychlewski** [comment]
Would you be able to create a minimal reproducible example that exhibits the problem, like this: https://github.com/wojtekmach/mix_install_examples/blob/main/ecto_sql.exs?

And one last shot in the dark: is it possible you are connecting the a database that doesn't have the extension installed? i.e. database name `myapp_dev` or `myapp_test` instead of `myapp`

**Comment by greg-rychlewski** [comment]
Another last shot in the dark: are you referring to the data type `citext` in a qualified way anywhere? i.e. `heroku_ext.citext` instead of `citext`? I think that might cause this issue too.

**Comment by tomtaylor** [comment]
Thanks @greg-rychlewski. I'm just making a minimal reproducible script at the moment. I'm not exactly sure how to refer to the column in an unqualified way in the table. Isn't it always qualified under the hood? For example:

```
poplar_dev=# SHOW search_path;
   search_path   
-----------------
 "$user", public
(1 row)
poplar_dev=# \d+ users;
                                                                             Table "public.users"
            Column             |            Type             | Collation | Nullable |              Default              | Storage  | Compression | Stats target | Description 
-------------------------------+-----------------------------+-----------+----------+-----------------------------------+----------+-------------+--------------+-------------
 id                            | bigint                      |           | not null | nextval('users_id_seq'::regclass) | plain    |             |              | 
 email                         | heroku_ext.citext           |           | not null |                                   | extended |             |              | 
...

poplar_dev=# ALTER TABLE users ALTER COLUMN email TYPE citext;
ERROR:  type "citext" does not exist
poplar_dev=# SET search_path TO public,heroku_ext;
SET
poplar_dev=# \d+ users;
                                                                             Table "public.users"
            Column             |            Type             | Collation | Nullable |              Default              | Storage  | Compression | Stats target | Description 
-------------------------------+-----------------------------+-----------+----------+-----------------------------------+----------+-------------+--------------+-------------
 id                            | bigint                      |           | not null | nextval('users_id_seq'::regclass) | plain    |             |              | 
 email                         | citext                      |           | not null |                                   | extended |             |              | 
...

poplar_dev=# ALTER TABLE users ALTER COLUMN email TYPE citext;
ALTER TABLE
poplar_dev=# \d+ users;
                                                                             Table "public.users"
            Column             |            Type             | Collation | Nullable |              Default              | Storage  | Compression | Stats target | Description 
-------------------------------+-----------------------------+-----------+----------+-----------------------------------+----------+-------------+--------------+-------------
 id                            | bigint                      |           | not null | nextval('users_id_seq'::regclass) | plain    |             |              | 
 email                         | citext                      |           | not null |                                   | extended |             |              | 
...

poplar_dev=# SET search_path TO public;
SET
poplar_dev=# \d+ users;
                                                                             Table "public.users"
            Column             |            Type             | Collation | Nullable |              Default              | Storage  | Compression | Stats target | Description 
-------------------------------+-----------------------------+-----------+----------+-----------------------------------+----------+-------------+--------------+-------------
 id                            | bigint                      |           | not null | nextval('users_id_seq'::regclass) | plain    |             |              | 
 email                         | heroku_ext.citext           |           | not null |                                   | extended |             |              | 
...

```

**Comment by tomtaylor** [comment]
I've added a test case here: https://github.com/tomtaylor/postgrex-extensions-bug/blob/main/ecto_test_case.exs. Note I'm setting the `search_path` on line 30. If I don't do this, it complains that the `citext` extension isn't installed, which makes me think that maybe `search_path` isn't being set in migrations?

**Comment by greg-rychlewski** [comment]
It looks like it's not being set for the `all` query either. Try replacing your `Repo.all` with this:

```elixir
Repo.transaction(fn ->
    IO.inspect Ecto.Adapters.SQL.query(Repo, "SHOW search_path", [])
    IO.inspect Ecto.Adapters.SQL.query(Repo, "SET search_path TO public,heroku_ext", [])
    IO.inspect Ecto.Adapters.SQL.query(Repo, "SHOW search_path", [])
    Repo.all(User)
end)
```

**Comment by tomtaylor** [comment]
Ah yes, I can see now it's not being set.

```
16:53:31.936 [debug] QUERY OK db=0.1ms
SHOW search_path []
{:ok,
 %Postgrex.Result{
   command: :show,
   columns: ["search_path"],
   rows: [["\"$user\", public"]],
   num_rows: 0,
   connection_id: 88750,
   messages: []
 }}
{:ok,
 %Postgrex.Result{
   command: :set,
   columns: nil,
   rows: nil,
   num_rows: 0,
   connection_id: 88750,
   messages: []
 }}

16:53:31.945 [debug] QUERY OK db=0.1ms
SET search_path TO public,heroku_ext []
{:ok,
 %Postgrex.Result{
   command: :show,
   columns: ["search_path"],
   rows: [["public, heroku_ext"]],
   num_rows: 0,
   connection_id: 88750,
   messages: []
 }}

16:53:31.946 [debug] QUERY OK db=0.4ms
SHOW search_path []
```

**Comment by tomtaylor** [comment]
What's the best way to approach this in our application? It looks to me like this _should_ work, but is there something preventing this locally? https://hexdocs.pm/ecto_sql/Ecto.Adapters.Postgres.html#module-after-connect-callback

**Comment by tomtaylor** [comment]
Actually, I can see this _is_ being set correctly in our application, just not in my test case!

```
iex(2)> Poplar.Repo.query!("SHOW search_path")
[debug] QUERY OK db=0.3ms queue=0.5ms idle=1060.7ms
SHOW search_path [] 
%Postgrex.Result{
  columns: ["search_path"],
  command: :show,
  connection_id: 92499,
  messages: [],
  num_rows: 0,
  rows: [["public, heroku_ext"]]
}
```

**Comment by greg-rychlewski** [comment]
It seems like there is something else happening then. We can see from the test that if the search path is set and the tables are set up the same as in your migrations then the query works.

If you don't use a custom type module do you get the same error? Just trying to isolate where the issue could be.

**Comment by tomtaylor** [comment]
Yeah, the test case runs just fine if I change `add(:email, :citext, null: false)` to `add(:email, :text, null: false)`.

**Comment by greg-rychlewski** [comment]
Oh sorry what I meant was if you don't set up this: `types: Poplar.PostgresTypes,` and just use the default types module.

Also one other thing we can do to debug. In your `deps` directory under postgrex/lib/postgrex/utils.ex can you make this change and recompile the deps?

```elixir
def type_msg(%Postgrex.TypeInfo{type: type} = type_struct, module) do
    IO.inspect type_struct
    "type `#{type}` can not be handled by the types module #{inspect(module)}"
end
```

We're looking for something like this

```
%Postgrex.TypeInfo{
  send: "heroku_ext.citextsend",
  type: "citext"
}
```

Because `send` needs to be `citext` to work.

**Comment by greg-rychlewski** [comment]
The `after_connect` issue was that it was set in the repo module and not here btw:

`Application.put_env(:app, Repo, database: "postgres_extensions_bug", after_connect: {Postgrex, :query!, query_args})`

The test works when I make that change. I guess after_connect is not taken from the repo module.

**Comment by tomtaylor** [comment]
OK, I've done both of those. I now get: `(Postgrex.QueryError) type `citext` can not be handled by the types module Poplar.PostgresTypes`, but I also see:

```elixir
%Postgrex.TypeInfo{
  array_elem: 0,
  base_type: 0,
  comp_elems: [],
  input: "heroku_ext.citextin",
  oid: 21937865,
  output: "heroku_ext.citextout",
  receive: "heroku_ext.citextrecv",
  send: "heroku_ext.citextsend",
  type: "citext"
}
```

**Comment by greg-rychlewski** [comment]
Ah ok so the search path is set correctly but it is still tagging it as `"heroku_ext.citextsend"`. I'm not 100% sure but I feel like that must mean that the underlying data is saved with the qualifier. Is it possible to 1) try altering the column type to just `citext` and if that doesn't work delete the column and add it again with just the type `citext`. I understand psql was behaving the way you showed me but it might just be the way they choose to format the output. And tbh it's hard to see what else it could be.

**Comment by greg-rychlewski** [comment]
And another thing to debug: `Poplar.Repo.query!("SELECT * FROM pg_extension")`

**Comment by greg-rychlewski** [comment]
@tomtaylor  Actually I have another idea. I think `after_connect` is too late to set the search path because it happens after the type info is fetched. Try adding a migration like this `ALTER USER foo SET search_path = public, heroku_ext` so that all user roles have this search path right away.

**Comment by tomtaylor** [comment]
> @tomtaylor Actually I have another idea. I think `after_connect` is too late to set the search path because it happens after the type info is fetched. Try adding a migration like this `ALTER USER your_app_user SET search_path = public, heroku_ext` so that all user roles have this search path right away.

Thanks, that works! Is it possible to make this a full blown configuration option that can define the search_path before the type info is fetched?

**Comment by greg-rychlewski** [comment]
I'm pretty sure that can be done. @josevalim what would you think about adding  a startup option `:search_path` ? And then [this part](https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/protocol.ex#L833) can be modified to check if it exists and sends `SET search_path...` before going to fetch types?

**Comment by josevalim** [comment]
Yeah, I think we should support a `:search_path` option in the connection and call it early. A PR is welcome! :heart: Great job debugging!

**Comment by greg-rychlewski** [comment]
Thanks for the suggestion @tomtaylor. You could try out the new `search_path` option in master now. It has to be set in the application config if you're using Ecto.

**Comment by tomtaylor** [comment]
Thanks @greg-rychlewski, this works nicely! Appreciate all your help on this.
