### ISSUE TITLE
scram-sha-256 authentication is slow enough to cause connect timeouts

### ISSUE THREAD

**Issue by rbishop** [elixir-ecto/postgrex#623]
**What**
Initiating connections to Postgres from Elixir apps uses considerably more CPU than md5. While some additional CPU usage is expected due to scram-sha-256 doing more work we have found that Postgrex in particular is significantly slower than Postgres drivers in other languages or languages using OpenSSL's cryptographic primitives. The slowness can lead to connect timeouts at application startup.

**Why it's worth fixing**
Elixir apps that use larger servers will create more connections at application start up. In my testing the issues start to crop up around 100 connections on a 8 core/16 thread machine. Eventually all of the connections get created but there are connect timeouts along the way. Even without connection timeouts the CPU usage is rather high and could lead to other spurious problems.

**Culprits**
I haven't profiled the problem extensively, but what I have seen so far indicates Erlang's `crypto:exor` and `crypto:mac` are the cause. Here is a FlameGraph (it's an svg) of `Postgrex.Scram.verify/2`:

![out-500](https://user-images.githubusercontent.com/982936/195666821-eb6746f1-8915-4b8c-9546-7c0b7b77553f.svg)

**Comment by josevalim** [comment]
My guess is actually that we do it once per connection. We would need to compute it once and cache it.

**Comment by greg-rychlewski** [comment]
@josevalim I'm interested in trying to tackle this. Would you use an agent for this instead of ets so that all the connections don't attempt to calculate the password while the first connection is in the middle of it?

**Comment by josevalim** [comment]
We need slightly more than Agent. We need a cache where everyone trying to compute the same key will lock until one of them computes it and then all others are unlocked. I have this implemented as a "locked cache" here: https://github.com/elixir-nx/nx/blob/main/exla/lib/exla/defn/locked_cache.ex - I think it is mostly copy and pasteable?

I keep thinking about abstracting it as a pattern but I can't come up with a general API. :)

**Comment by greg-rychlewski** [comment]
> I keep thinking about abstracting it as a pattern but I can't come up with a general API. :)

What about something like this: 

For soft reads:
- `get(key)`

And for hard reads:
- `get_or_set(key, fun/0)` when the value is completely determined by output of a function
- `get_or_set(key, value, fun/1)` when you want to apply an expensive transformation on a possibly dynamic value

And then probably you want some way to modify what is in there:
- `remove(key)`
- `set(key, fun/0)` / `set(key, value, fun/1)` this one still lazily evaluated because even though all the calculations will happen it might still be better for them not to happen at the same time

**Comment by josevalim** [comment]
Thank you!

My biggest concern is more about the scalability of the API, then the signatures per-se. :) The example above will work just fine for Postgrex but it may not scale if someone wants to use it as a general cache.

I don't think we have to worry about it now though, we should probably solve it for Postgrex first. But if you have a need, feel free to go ahead and expand it!

**Comment by greg-rychlewski** [comment]
@rbishop The client key is being cached now in master so it will only be calculated once. When you have a chance to try it out, please let us know if it works better for you.

**Comment by rbishop** [comment]
Just tested it out and that did the trick! Thank you for taking care of this so quickly.
