### ISSUE TITLE
Notifications: auto-reconnect introduces race condition 

### ISSUE THREAD

**Issue by schnittchen** [elixir-ecto/postgrex#637]
### Elixir version

Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]  Elixir 1.13.0 (compiled with Erlang/OTP 24)

### Database and Version

14.5

### Postgrex Version

0.16.5

### Current behavior

By the nature of how Postgres NOTIFY works, any messages sent in the time window between a disconnect and the reconnect+re-subscribe are lost.

Application logic could cope with that in lots of cases by (as per the PG NOTIFY documentation)

* subscribe (listen)
* check database state
* wait for notifications

However, in the case of auto-reconnection there seems to be no way for the process which called `listen` to know about the situation.

A workaround might be to use `auto_reconnect: false`, monitor the Notification process, subscribe and re-subscribe and re-monitor when the DOWN message is received.

### Expected behavior

The library could save and replay subscriptions.

For reproducing the problem, this SQL snippet is useful:

```
SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid() AND datname IS NOT NULL AND leader_pid IS NULL;
```

**Comment by greg-rychlewski** [comment]
Is your concern that an auto-reconnect won't automatically resubscribe?

If so there is a `handle_connect` callback that will be invoked right after connection. The `listen` query could be called there.

**Comment by schnittchen** [comment]
> Is your concern that an auto-reconnect won't automatically resubscribe?
> 
> If so there is a `handle_connect` callback that will be invoked right after connection. The `listen` query could be called there.

Not sure I understand you correctly.

I think `auto_reconnect: true` DOES handle the repeat LISTEN, at least I'm getting notification messages after terminating connections and NOTIFYing. The application just does not know it might have missed notifications.

The `handle_connect` is a `Postgrex.SimpleConnection` callback, implemented by `Postgrex.Notifications`, and it handles the LISTENs here https://github.com/elixir-ecto/postgrex/blob/v0.16.5/lib/postgrex/notifications.ex#L203

I cannot `use` `Notifications` in order to override the callback for adding more logic, though, so I would need to duplicate and extend it. Also, `SimpleConnection` advertises `Notifications` as

```
See [Postgrex.Notifications](https://hexdocs.pm/postgrex/Postgrex.Notifications.html) for a more complex implementation that can unlisten, handle process exits, and persist across reconnection.
```

so I believe the solution should be part of `Postgrex.Notifications`.

**Comment by greg-rychlewski** [comment]
Oh sorry I forgot `Notifications` is implementing `SimpleConnection`. I thought people used `SimpleConnection` to write their own `Notification`.

So basically you want to know when the notification connection disconnected?

**Comment by schnittchen** [comment]
Yes, I think that makes sense.

Proposed solution: add an option `notify_subscribed: true` to the `subscribe` function that creates a message of the format

```
{:notification_subscribed, notification_pid, listen_ref, channel}
```

on every successful SUBSCRIBE, including the initial one.

I'm not sure what should be done in the `auto_reconnect: false` case. Maybe those two should be mutually exclusive.

**Comment by schnittchen** [comment]
I wonder under which conditions a `Notifications` process with `auto_reconnect: true` could crash, because in that case, all subscription information is completely lost

**Comment by josevalim** [comment]
We could have a PR for notify subscribed/listening, but then you still need to monitor the subscription process, in case it crashes, so I am thinking auto-reconnect: false with monitor is actually less work?

**Comment by schnittchen** [comment]
True, if a crash is to be expected under normal circumstances (including database shutdown, netsplit etc.)...
