### ISSUE TITLE
Unable to connect to QuestDB (postgresql compatible protocol)

### ISSUE THREAD

**Issue by Zarathustra2** [elixir-ecto/postgrex#645]
### Elixir version

Elixir 1.14.3

### Database and Version

questdb 7.0.1

### Postgrex Version

 0.16.5

### Current behavior

[QuestDB](https://questdb.io/) is a timeseries database which supports the postgresql wire protocol: https://questdb.io/docs/develop/connect/#postgresql-wire-protocol

I am able to connect via `psql` to QuestDB and other postgresql libs such as libpq can connect as well: https://questdb.io/docs/develop/query-data#postgresql-wire-protocol

When trying to connect with postgrex I get: 
```
 [error] Postgrex.Protocol (#PID<0.1034.0>) failed to connect: ** (Postgrex.Error) ERROR 00000 (successful_completion) table does not exist [table=pg_attribute]
 ```

I am wondering if that is intended behaviour or a bug which should be fixed eventually so that postgrex can be used to connect with postgresql compatible protocols. 

Best regards,
Dario

### Expected behavior

Being able to connect to QuestDB with postgrex or any DB whose protocol is postgresql compatible.

**Comment by josevalim** [comment]
Postgrex uses the wire protocol but it also expects some tables, such as pg_attributes, to be available so can we retrieve properties and learn how to serialize and deserialize data. So unless QuestDB implements the contents of the pg_attributes table, it unfortunately won't work.

**Comment by Zarathustra2** [comment]
@josevalim 

I just tried to connect with clickhouse and there is now a different issue but same as QuestDB (since QuestDB resolved the one above): Both fail on parsing the provided query generated by `bootstrap_query`. 

I am wondering if it would be possible to provide the types via a configuration file or callback function? That way postgrex could be used as a client for more databases (assuming the `bootstrap_query` ) is the only issue.
