### ISSUE TITLE
Supervisor keyword arguments require a specific order to work

### ISSUE THREAD

**Issue by mmaughon** [elixir-ecto/postgrex#646]
### Elixir version

Elixir 1.14.1 (compiled with Erlang/OTP 25)

### Database and Version

postgres (PostgreSQL) 12.14

### Postgrex Version

0.16.5

### Current behavior

1. Add an instance of postgrex to the Supervisor tree. In this case, we had more than one so unique names were given: `%{id: :postgrex_abc_db, start: {Postgrex, :start_link, [Config.abc_postgrex()]}}`
2. Add the config to `runtime.exs`: 
```elixir
    abc_postgrex: [
    name: :abc_db,
    hostname: "localhost",
    username: "postgres",
    password: "postgres",
    port: "5434",
    database: "abc-test",
    pool_size: 2,
    timeout: 5000
 ],
```

### Expected behavior

The code above should work but if the config is changed in `runtime.exs` such that the `port` key is right after the `database` key it will fail.

**Comment by josevalim** [comment]
Hi @mmaughon, can you please provide a small that reproduces the error? This will help ensure we will debug the problem you are seeing. :)

**Comment by mmaughon** [comment]
I was unable to reproduce this problem again. It happened a couple months ago but I can't reproduce it now. I will close it as not a problem.
