### ISSUE TITLE
Unable to connect to Clickhouse (postgresql compatible protocol)

### ISSUE THREAD

**Issue by ColaCheng** [elixir-ecto/postgrex#665]
### Elixir version

1.14.5

### Database and Version

clickhouse-server:23.10.3

### Postgrex Version

master:ab4265e

### Current behavior

[ClickHouse](https://clickhouse.com/) is a database that supports the postgresql wire protocol: https://clickhouse.com/docs/en/interfaces/postgresql

I am able to connect via psql to ClickHouse.

When trying to connect with postgrex I get:

disable_composite_types: true
```
module=DBConnection.Connection function=handle_event/4 [error] Postgrex.Protocol (#PID<0.3478.0>) failed to connect: ** (Postgrex.Error) ERROR 2F000 (sql_routine_exception) Query execution failed.
DB::Exception: Table default.pg_type doesn't exist
```

disable_composite_types: false
```
module=DBConnection.Connection function=handle_event/4 [error] Postgrex.Protocol (#PID<0.3447.0>) failed to connect: ** (Postgrex.Error) ERROR 2F000 (sql_routine_exception) Query execution failed.
DB::Exception: Syntax error: failed at position 159 ('a') (line 3, col 10): a.atttypid
  FROM pg_attribute AS a
  WHERE a.attrelid = t.typrelid AND a.attnum > 0 AND NOT a.attisdropped
  ORDER BY a.attnum
)

FROM pg_type AS t
LEFT JOIN p. Expected one of: token, Dot, Comma, ClosingRoundBracket, OR, AND, BETWEEN, NOT BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, REGEXP, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, MOD, DIV, IS NULL, IS NOT NULL, alias, AS, end of query
```

Related to this [issue #645](https://github.com/elixir-ecto/postgrex/issues/645).

### Expected behavior

Being able to connect to ClickHouse with postgrex or any DB whose protocol is postgresql compatible.

**Comment by greg-rychlewski** [comment]
Thanks for the report. Unfortunately without `pg_type` Postgrex isn't able to handle types properly. I would suggest trying out the Clickhouse Elixir driver here: https://github.com/clickhouse-elixir/clickhousex.

**Comment by greg-rychlewski** [comment]
Another option might be to try using the simple connection: https://hexdocs.pm/postgrex/Postgrex.SimpleConnection.html

It uses the simple query protocol instead of the extended query protocol and doesn't care about OIDs

**Comment by josevalim** [comment]
Yeah, https://github.com/plausible/ch is the way to go. It is also linked on Ecto's main README. :)
