### ISSUE TITLE
"missed message" exit and shutdown with Elixir release

### ISSUE THREAD

**Issue by andrewtimberlake** [elixir-ecto/postgrex#667]
### Elixir version

1.15.4 OTP 24

### Database and Version

PostgreSQL 12.1

### Postgrex Version

0.17.4

### Current behavior

I have a new Phoenix project that I’m trying to run under an elixir release.
If I run the app on the server using `mix phx.server` it works fine but if I run it `bin/app_name start_iex` it starts and then very shortly crashes with the following in the logs:
```
14:15:58.888 [info] Postgrex.Protocol (#PID<0.1976.0>) missed message: {:EXIT, #PID<0.2118.0>, :shutdown}
14:15:58.888 [info] Postgrex.Protocol (#PID<0.1977.0>) missed message: {:EXIT, #PID<0.2118.0>, :shutdown}
14:15:58.888 [info] Postgrex.Protocol (#PID<0.1980.0>) missed message: {:EXIT, #PID<0.2118.0>, :shutdown}
```

The app currently doesn’t have any tables or database interactions.

### Expected behavior

That it works when run under a release.

**Comment by josevalim** [comment]
Can you please provide a way to reproduce this error? I cannot reproduce this in a release.

**Comment by andrewtimberlake** [comment]
@josevalim Thanks, a fresh morning set of eyes and I realised I had exhausted my connection pool. When I reduced the pool size the error went away.
I’m not sure if it’s possible to pick that up and provide a more obvious error?

**Comment by axelson** [comment]
Are these `missed message: {:EXIT, #PID<0.2118.0>, :shutdown}` expected as part of normal shutdown?

I'm seeing this message in my shutdown logs on both production and in development when the server is shutting down. So this is slightly different from what Andrew is seeing where the server shutdown on it's own.

Here's a reproduction repository: https://github.com/axelson/repro_postgrex_shutdown

I reproduced it on a fresh Phoenix app after running `System.stop`. I'm running Elixir 1.15.7-otp-26 and erlang 26.1.2.

**Comment by josevalim** [comment]
Thank you. Fixed in DBConnection main.

**Comment by axelson** [comment]
Great, thank you! ❤️
