### ISSUE TITLE
ReplicationConnection: durable replication slots re-process events on restart/reconnect

### ISSUE THREAD

**Issue by DaemonSnake** [elixir-ecto/postgrex#672]
### Elixir version

1.15.7

### Database and Version

PostgreSQL 12

### Postgrex Version

0.17.4

### Current behavior

I'm working on a fork of Walex (https://github.com/cpursley/walex, uses postgrex under the hood) which aims to add support to non-temp replication slots.
I haven't found much help in the documentation of ReplicationConnection in that regard and no tests in this repo.
Once the replication slot is created it is started by the ReplicationConnection using the query:
```elixir
    query =
      "START_REPLICATION SLOT #{slot_name} LOGICAL 0/0 (proto_version '1', publication_names '#{publication}')"
```
It works well but if we restart messaged that were already processed by the replication gets resent.

the processing of the results is implemented using the example in postgrex's documentation:
```elixir
  @impl true
  # https://www.postgresql.org/docs/14/protocol-replication.html
  def handle_data(<<?w, _wal_start::64, _wal_end::64, _clock::64, rest::binary>>, state) do
    ...
    {:noreply, state}
  end

  # Primary keepalive message (B)
  def handle_data(<<?k, wal_end::64, _clock::64, reply>>, state) do
    messages =
      case reply do
        1 -> [<<?r, wal_end + 1::64, wal_end + 1::64, wal_end + 1::64, current_time()::64, 0>>]
        0 -> []
      end
    {:noreply, messages, state}
  end
```

Might be missing something.
Should the ReplicationConnection itself keep track and store reliably the wal_start + wal_end and use it for the XXX/XXX in the start replication query ?

### Expected behavior

consumed wal segments don't get re-processed.

**Comment by josevalim** [comment]
It is up to you to implement and persist that. The replication connection only opens up a replication connection to PG, the queries that are sent after connected are completely up to you. :)

**Comment by DaemonSnake** [comment]
ok thanks, closed ^^

**Comment by greg-rychlewski** [comment]
It might help to see how pg_recvlogical is doing things. They are a simple CLI tool that listens to logical replication: https://github.com/postgres/postgres/blob/master/src/bin/pg_basebackup/pg_recvlogical.c

**Comment by DaemonSnake** [comment]
> It might help to see how pg_recvlogical is doing things. They are a simple CLI tool that listens to logical replication: https://github.com/postgres/postgres/blob/master/src/bin/pg_basebackup/pg_recvlogical.c

looks like it's saved using a static variable and can be supplied by arguments.
So in both cases I think the last lsn should be stored somewhere and be used once the service starts.
Hoped that it would be the restart_lsn in the  pg_replication_slot view:

> The address (LSN) of oldest WAL which still might be required by the consumer of this slot and thus won't be automatically removed during checkpoints.

but doesn't look like it's the case.

**Comment by greg-rychlewski** [comment]
It's been a few years since I played around with it, but I remember something similar. I don't remember the exact behaviour being described in the Postgres docs to a level of detail where I was comfortable. I remember digging through old Postgres mailing list discussions and looking at code like pg_recvlogical and Debezium.

**Comment by DaemonSnake** [comment]
> Oh I thought of one other thing. Are you creating a new replication slot every time you restart or re-using the old one?

the second, I keep the old one but restart for now at 0/0, need to replace this with the appropriate address.
The postgres docs are indeed pretty shy in term of example in that regard 😢

**Comment by greg-rychlewski** [comment]
You can also maybe query for `confirmed_flush_lsn pg_lsn` from ` pg_replication_slots` and set it that way on restart.

**Comment by DaemonSnake** [comment]
thanks @greg-rychlewski ^^
FYI for my case where I'm doing change capture I need to actually store the LSN of each transaction I actually processed to avoid duplication the processing of events
