### ISSUE TITLE
Preserve time precision when we decode a time

### ISSUE THREAD

**Issue by thenrio** [elixir-ecto/postgrex#675]
### Elixir version

1.15.6

### Database and Version

16

### Postgrex Version

0.17.5

### Current behavior

Current parse of time always comes with millisecond precision, even when the the precision is second.

### Expected behavior

Don't put millisecond precision, with 0 millisecond, when precision is second.

```
assert [[~T[01:02:03]]] = query("SELECT $1::time", [~T[01:02:03]])
```

**Comment by josevalim** [comment]
Closing in favor of the PR!
