### ISSUE TITLE
Hex link points to a different repository and description is incorrect

### ISSUE THREAD

**Issue by scudelletti** [elixir-ecto/postgrex#679]
### Elixir version

-

### Database and Version

-

### Postgrex Version

-

### Current behavior

Go to [postgrex](https://hex.pm/packages/postgrex) on Hex.
Under links click on `github`, you'll end up in `nileshtrivedi/autogen`.

The current description is: `Elixir port of Microsoft's multi-agent AI framework Autogen`.

### Expected behavior

It should link to `elixir-ecto/postgrex`
The description should be the correct one.

**Comment by scudelletti** [comment]
Screenshot:
![Screenshot 2024-06-03 at 08 39 12](https://github.com/elixir-ecto/postgrex/assets/410080/df98e834-3702-4499-a0d1-78b04a4ce59b)

**Comment by ericmj** [comment]
Fixed now. Thanks for the report.
