### ISSUE TITLE
Database connections keeps on getting disconnected

### ISSUE THREAD

**Issue by aakashjhawar** [elixir-ecto/postgrex#680]
### Elixir version

1.11

### Database and Version

PostgresQL 11

### Postgrex Version

0.16.3

### Current behavior

Too many errors in the logs. This is affecting the performance of the application.

Error:
```
Postgrex.Protocol (#PID<0.3690.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.16480.114> exited
```

### Expected behavior

It should query the database and return the response.

**Comment by josevalim** [comment]
Can you please provide more information? If this is happening, it is because there is a process crashing while it holds the database connection. The reason why the process crashes is most often application specific, so we would need to understand why it is happening in your cases.
