### ISSUE TITLE
failed to start child: Postgrex.Notifications

### ISSUE THREAD

**Issue by mxgrn** [elixir-ecto/postgrex#690]
### Elixir version

1.16.0

### Database and Version

Postgres 16.1

### Postgrex Version

0.18.0

### Current behavior

I generated a vanilla Phoenix 1.7.14 app, then added this to the list of Application children, as described in the docs:

`{Postgrex.Notifications, name: PhxVanilaLatest.Notifications}`

After this, running `iex -S mix` gives the following error:

```
** (Mix) Could not start application phx_vanila_latest: PhxVanilaLatest.Application.start(:normal, []) returned an error: shutdown: failed to start child: Postgrex.Notifications
    ** (EXIT) {:bad_return_from_init, {:stop, %ArgumentError{message: "missing the :database key in options for nil"}, %Postgrex.SimpleConnection{idle_interval: 5000, protocol: nil, auto_reconnect: false, reconnect_backoff: 500, state: {Postgrex.Notifications, %Postgrex.Notifications{from: nil, ref: nil, auto_reconnect: false, connected: false, listeners: %{}, listener_channels: %{}}}}}}
```

### Expected behavior

Any hint to help me get this running?

**Comment by wojtekmach** [comment]
Thank you for the report. You need to pass the database you're connecting to, e.g.:

```elixir
{Postgrex.Notifications, name: PhxVanilaLatest.Notifications, database: "foo"}
```

We'll improve docs.

**Comment by mxgrn** [comment]
Thanks Wojtek, then, for Phoenix, it'll probably be:

`{Postgrex.Notifications, name: MyApp.Notifications, database: MyApp.Repo.config()[:database]}`

**Comment by mxgrn** [comment]
And while we're on that docs page, here's another suggested fix:

`NOTIFY "channel", "Oh hai!";` -> `NOTIFY channel, `Oh hai!`;`

**Comment by wojtekmach** [comment]
Btw I created https://github.com/wojtekmach/mix_install_examples/blob/main/postgrex_notifications.exs for posterity!
