### ISSUE TITLE
Dialyzer error with Duration

### ISSUE THREAD

**Issue by oliver-kriska** [elixir-ecto/postgrex#700]
### Elixir version

1.17.2-otp-27

### Database and Version

PostgreSQL 16

### Postgrex Version

0.19.0

### Current behavior

error is
```
deps/postgrex/lib/postgrex/type_module.ex:1084:pattern_match
The pattern can never match the type.

Pattern:
Duration

Type:
Postgrex.Interval
```

### Expected behavior

I suspect that this doesn't work correctly but no idea how to fix it
https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/extensions/interval.ex#L58

**Comment by greg-rychlewski** [comment]
@oliver-kriska Thanks for the report. Could you please try the latest commit on this repo to confirm it solves your issue?

**Comment by oliver-kriska** [comment]
@greg-rychlewski  didn't help or another issue:
```
deps/postgrex/lib/postgrex/type_module.ex:1084:call
The function call will not succeed.

:erlang.band(_mod :: nil, 65535)

will never return since the 1st arguments differ
from the success typing arguments:

(integer(), integer())
```
