### ISSUE TITLE
Dialyzer errors after 0.18.0 -> 0.19.0

### ISSUE THREAD

**Issue by Billzabob** [elixir-ecto/postgrex#703]
### Elixir version

1.17.0

### Database and Version

PostgreSQL 16.3

### Postgrex Version

0.19.0

### Current behavior

After upgrading to 0.19.0, when running dialyzer we get this error:
```
deps/postgrex/lib/postgrex/type_module.ex:1084:pattern_match
The pattern can never match the type.

Pattern:
Duration

Type:
Postgrex.Interval
```

Here is our type definition:

```
Postgrex.Types.define(
  Core.PostgresTypes,
  [Geo.PostGIS.Extension] ++ Ecto.Adapters.Postgres.extensions(),
  json: Jason
)
```

We've tried adding the `interval_decode_type` option of both `Duration` and `Postgrex.Interval` and neither fixes the error.

### Expected behavior

No Dialyzer error.

**Comment by josevalim** [comment]
Please try main. We pushed some fixes already.

**Comment by josevalim** [comment]
new version out
