### ISSUE TITLE
Missing git tag on v0.19.3

### ISSUE THREAD

**Issue by 03juan** [elixir-ecto/postgrex#719]
### Elixir version

n/a

### Database and Version

n/a

### Postgrex Version

0.19.3

### Current behavior

The hexdoc "View source" links result in GitHub 404.

e.g. Clicking through https://hexdocs.pm/postgrex/0.19.3/Postgrex.html#prepare/4 to https://github.com/elixir-ecto/postgrex/blob/v0.19.3/lib/postgrex.ex#L389

<img src="https://github.com/user-attachments/assets/c67a1b33-c6c1-48f5-85be-22279486a354" alt="GitHub 404 error" width="250px">

### Expected behavior

"View source" links should work as per previous releases:

Clicking on https://hexdocs.pm/postgrex/0.19.2/Postgrex.html#prepare/4 correctly navigates to https://github.com/elixir-ecto/postgrex/blob/v0.19.2/lib/postgrex.ex#L364

**Comment by josevalim** [comment]
Fixed
